### ISSUE TITLE
Sync with MoveIt master

### ISSUE THREAD

**Issue by henningkayser** [ros-planning/moveit2#101]
We should have a fresh sync with the MoveIt master branch. I think it makes most sense to do this after we synced up with Acutronic's fork since otherwise it would be more difficult to identify the remaining progress. I'm happy to do this, @rhaschke help/feedback are appreciated ;)

**Comment by davetcoleman** [comment]
@henningkayser just reported in weekly meeting this will happen tomorrow, Dec 4th
