### ISSUE TITLE
What's the difference between `/planning_scene`, `/planning_scene_world`,  `/monitored_planning_scene`?

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#1042]
I think it's confusing to have all of these topics, and it's not clear what the difference is. Consider removing one or two of them.

**Comment by AndyZe** [comment]
I poked around a bit and it seems `/monitored_planning_scene` is subscribed to by rviz2. Maybe a renaming is appropriate:

`/moveit_rviz_planning_scene`

**Comment by tylerjw** [comment]
Potentially similar to https://github.com/ros-planning/moveit2/issues/924

**Comment by AndyZe** [comment]
This doc answers the question:  https://moveit.picknik.ai/galactic/doc/concepts/planning_scene_monitor.html
