### ISSUE TITLE
Porting stand alone commits

### ISSUE THREAD

**Issue by JafarAbdi** [ros-planning/moveit2#108]
### Description

Some commits are applied for multiple packages at once, I would recommend porting these commits as they are rather than applying the change to each package and committing it, I'll list them below

- [Converting all libraries to SHARED](https://github.com/AcutronicRobotics/moveit2/commit/d280abb3a4e309dfdd4634d075b6d4eba6ed090b#diff-468186bdf99c33116a2d2ece4e3398c3)

- When porting trajectory_execution_manager these commits change files outside the package
  - [1](https://github.com/AcutronicRobotics/moveit2/commit/2e690e1f74ae02c13fb914681d827333ddf978b5#diff-a73d62e96e18091b247a4b7ca1851703) 
  - [2](https://github.com/AcutronicRobotics/moveit2/commit/ca5bcd1a6db87c547c087fb13d0cc410d3f4393c#diff-a73d62e96e18091b247a4b7ca1851703)
  - [3](https://github.com/AcutronicRobotics/moveit2/commit/62846b40453e2b2d6a17292e6c861b9a237e773a#diff-a73d62e96e18091b247a4b7ca1851703)
  - [4](https://github.com/AcutronicRobotics/moveit2/commit/62846b40453e2b2d6a17292e6c861b9a237e773a#diff-a73d62e96e18091b247a4b7ca1851703)
  - [5](https://github.com/AcutronicRobotics/moveit2/commit/e05e309387fd3736df0fdb07a63d2a00036c85f2#diff-a73d62e96e18091b247a4b7ca1851703)
  - [6](https://github.com/AcutronicRobotics/moveit2/commit/ed7b0af6b045dfcbe1893fdbe457e94fe55febef#diff-a73d62e96e18091b247a4b7ca1851703)

- plan_execution
  - [1](https://github.com/AcutronicRobotics/moveit2/commit/db14a9b414b58669342c8eb2addcf2ad70d4d3d0#diff-c9a3d7b259cf72d310de1415934db9e6)
- planning_scene_monitor
  - [1](https://github.com/AcutronicRobotics/moveit2/commit/3c709af339fed709b492a0f423a75e47b5952b6c#diff-a46d004b080429e380be5b5206b1dd62)
- constraint_sampler_manager_loader
  - [1](https://github.com/AcutronicRobotics/moveit2/commit/a2a75449c7f96c3f68e4cdaf37de7059183dd83f#diff-2abb688eb29b35d82a5951fd1055f2a6)

**Comment by henningkayser** [comment]
All libraries should be shared by default. I would just add a new commit for each PR.
I'll look into those other commits.
