### ISSUE TITLE
Refactoring and Testing Calculations

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2#1082]
### Need

As a user of MoveIt
I want routines for calculations to be separated from side-affect-causing code so it can be re-used and tested easily.

### Acceptance

4 PRs landed that:
* refactor out a calculation from a section of code that has side effects to a pure function
* add a test of that pure function

### Notes

I'm defining a `Calculation` as a block of code that always produces the same output given the same inputs and is not dependent on the number of times it is run.  This means that Calculations are pure sections of code and do not depend on or cause side effects.

This task is inspired by the book [Grokking Symplicity](https://www.manning.com/books/grokking-simplicity).

**Comment by tylerjw** [comment]
@mamoll suggested extracting Signed Distance Fields from CHOMP.  Please edit this comment to clarify.

**Comment by litmus-zhang** [comment]
Hi @tylerjw  how can i also contribute to this?

**Comment by Mech-Mon** [comment]
Hello @tylerjw , I am interested in helping out. Noob to contributing.

**Comment by TaMaN2031A** [comment]
Good morning,
If I could ask, where can I find this "calculation" part? or do you mean that this problem is widespread in the whole code?
Thank you.

**Comment by Abhishek-k-kori** [comment]
I m intrested to help you through GSOC ,

**Comment by Henry-YiW** [comment]
Hi, I'm very interested in this project through GSOC.

**Comment by tylerjw** [comment]
I'm closing this as it was an odd issue that is not specific enough.
