### ISSUE TITLE
moveit in ROS 2 Rolling has not been released on Ubuntu Jammy 

### ISSUE THREAD

**Issue by nuclearsandwich** [ros-planning/moveit2#1092]
### Description

The ROS 2 Rolling Ridley distribution recently [migrated to Ubuntu 22.04 Jammy](https://github.com/ros/rosdistro/pull/32036) using the rosdistro migration tool.

This repository is one which failed to bloom during the migration because the `python-lxml` dependency is not available in Ubuntu Jammy. Since this is a python2 package it is unlikely that this dependency will be available on Ubuntu Jammy in the future and the packages relying on it may need to be patched to use an alternative.
Once this dependency issue is addressed it should be possible to release this repository in Rolling again by running bloom normally.

Packages which are not released in Rolling may not be automatically added to future stable ROS 2 distributions.

### Your environment
* ROS Distro: Rolling
* OS Version: Ubuntu 22.04
* Source or Binary build? bloom release
* If binary, which release version? 2.4.0

### Steps to reproduce

bloom-release -r rolling moveit

**Comment by ijnek** [comment]
@tylerjw and @henningkayser thanks for your work, would it be possible to make a rolling release available since it seems like Rolling CI is enabled and is passing?
