### ISSUE TITLE
c++ api - compute all planned solutions 

### ISSUE THREAD

**Issue by sancelot** [ros-planning/moveit2#1093]
## Background

I want to compute solutions with the c++ api in order to go from pose A to pose B

How to obtain all the planned solutions ?

Is it possible to act on speed factors ? by joint ? or general speed ?

**Comment by henningkayser** [comment]
@sancelot did you proceed with your questions in the meantime? I assume you are using `MoveItCpp`. There you can query the solutions using `PlanningComponent::getLastPlanSolution()`. General velocity and acceleration factors can be specified using the `PlanRequestParameters` here https://github.com/ros-planning/moveit2/blob/main/moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/planning_component.h#L110. It's not supported to dynamically set these factors by joint currently. Joint limits can only be configured in the urdf or the `joint_limits.yaml` file.
