### ISSUE TITLE
error while loading libbackward.so 

### ISSUE THREAD

**Issue by aaryanmurgunde** [ros-planning/moveit2#1094]
### Description
When the move_group node is executed, it immidiatly dies with the following error `moveit_ros_move_group/move_group: error while loading shared libraries: libbackward.so: cannot open shared object file: No such file or directory`

![image](https://user-images.githubusercontent.com/44398228/155896774-b3952b51-3645-4d52-9a8f-6ae43a2c9f31.png)

This seems to be caused by the missing package ros_backwards.
**This dependency should have been installed directly by the binary itself.**

### Fix from @tylerjw 
`sudo apt install ros-galactic-backward-ros` or `sudo apt install ros-<ROS DISTRO>-backward-ros`

### Environment
* ROS Distro: Galactic
* OS Version: Ubuntu 20.04
* Binary: Package: ros-galactic-moveit
Version: 2.3.4-1focal.20220208.011441

**Comment by JafarAbdi** [comment]
I'm not %100 sure, but I think it's because we have moveit_common as a `build_depend` rather than `depend`

**Comment by v4hn** [comment]
On Tue, Mar 08, 2022 at 06:02:04AM -0800, Jafar Abdi wrote:
> I'm not %100 sure, but I think it's because we have moveit_common as a `build_depend` rather than `depend`

No, the problem is that libbackward.so & backward_ros are installed on the buildfarm when the package is built, so cmake picks them up.
We wanted to have this linked only when building yourself with backward_ros installed on your system instead of making it a fixed dependency.

@jspricke probably can support here.

**Comment by jspricke** [comment]
>On Tue, Mar 08, 2022 at 06:02:04AM -0800, Jafar Abdi wrote:
>> I'm not %100 sure, but I think it's because we have moveit_common as a `build_depend` rather than `depend`

Correct, plus that you inject backward_ros everywhere:

https://github.com/ros-planning/moveit2/blob/1faa2b16c94271a9290a6106181f8ef856f9a4ca/moveit_common/cmake/moveit_package.cmake#L36

>No, the problem is that libbackward.so & backward_ros are installed on the buildfarm when the package is built, so cmake picks them up.
>We wanted to have this linked only when building yourself with backward_ros installed on your system instead of making it a fixed dependency.

Then you should drop the dependency in the package.xml:

https://github.com/ros-planning/moveit2/blob/4c75dcf0bf4c98e1baf56765095b69d4297aabcf/moveit_common/package.xml#L21

**Comment by tylerjw** [comment]
From my perspective, I don't see a problem injecting backward_ros into our release binaries.  My intention was that it would always be there in the releases and not that it would require installing it separately.

**Comment by v4hn** [comment]
Seems there was some disagreement then on the original intention. :-)
I don't care much either way. I just think it is much more useful with a `Debug` build over our default `Release`.
But there is probably not much harm having it everywhere (just another dependency).
@JafarAbdi could you patch the dependencies everywhere?
