### ISSUE TITLE
Wrong source command in instructions

### ISSUE THREAD

**Issue by T2FF** [ros-planning/moveit2#1105]
Hello everyone, I am new at ROS,

when I tried to follow the [MoveIt instructions](https://moveit.picknik.ai/galactic/doc/tutorials/getting_started/getting_started.html) after installing ROS2 Galactic on Ubuntu 20.04 it did not work.

After a bit of trouble shooting I noticed the command `source /opt/ros/rolling/setup.bash` which should probably be `source /opt/ros/galactic/setup.bash` as the instructions described here refer to the Galactic distribution.

**Comment by henningkayser** [comment]
This is being fixed by https://github.com/ros-planning/moveit2_tutorials/pull/339
