### ISSUE TITLE
Unable to run MSA (Moveit Setup Assistant)

### ISSUE THREAD

**Issue by RoboHack04** [ros-planning/moveit2#1146]
### Description

I was trying to use MSA in ROS2 Galactic distro for a new robot. I couldn't run the 'moveit_setup_assistant' node since any appropriate executable is present in the cmake file. i wanted to know if the reason is just because of some naming errors or is this package still in WIP for ROS2 distro.

### Your environment
* ROS2 Distro: [Galactic]
* OS Version: e.g. Ubuntu 20.04
* Source Build
* Galactic/main branch

### Steps to reproduce
Run the below mentioned command with appropriate urdf path.
```
ros2 run moveit_setup_assistant moveit_setup_assistant --urdf <path_to_urdf/xacro>
```

### Expected behaviour
GUI of MSA should load or some interface to generate moveit_config package for the robot.

### Actual behaviour
It will run into '_No executable found_' error. 
It makes sense as no executable is linked at the moment.

### Backtrace or Console output

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by okvik** [comment]
MSA hasn't yet been fully ported to ROS2. You can find the WIP version on the `feature/msa` branch, though I don't think it currently generates all the files needed to use MoveIt2. It's been getting closer recently, and I'm very much looking forward to having this tool generally available. Right now it seems we're supposed to be using the ROS1 version and updating some of the files to ROS2 needs.

**Comment by RoboHack04** [comment]
@okvik  thanks for your reply!

I am little new to Moveit in general, so it would be great if you could please share some insights on the steps that need to be done after creating the config package in ROS1 (i mean a little more explanation of all the changes that needs to be done for ROS2)

**Comment by okvik** [comment]
@RoboHack04 Sorry, but I didn't try to take the proposed path myself since I'm not familiar with ROS1 at all, nor really with MoveIt, so reconciling the differences seemed like too much pain for questionable gain. I instead took a look at some of the existing MoveIt configs for other robots / workcells and manually adapted them for my setup / robot. It's not fun, but it (mostly) worked. Sorry for not being of more help...

**Comment by RoboHack04** [comment]
@okvik ah alright...anyways thanks for your inputs!

**Comment by JafarAbdi** [comment]
@RoboHack04 We're planning to have MSA ready by Humble release, until then https://github.com/ros-planning/moveit_resources/tree/ros2/panda_moveit_config is a good example for how moveit config package looks like in ROS2

**Comment by 0smile** [comment]
@RoboHack04 Hi, my notes may can help you, I compared the moveit configuration for a same Panda robot arm in moveit and moveit2, check it here:
http://www.lxshaw.com/tech/ros/2022/02/22/msa%e4%bd%bf%e7%94%a8%e4%bb%a5%e5%8f%8a%e5%af%b9moveit2%e7%9a%84%e9%80%82%e9%85%8d/
However I write it in chinese, so you may need to use a translator.
