### ISSUE TITLE
Porting from AcutronicRobotics repo progress table

### ISSUE THREAD

**Issue by JafarAbdi** [ros-planning/moveit2#116]
| Package name | Package name | Package name                     |        PR opened             | PR merged            | Notes    |
|:------------:|:------------:|:--------------------------------:|:----------------------------:|:--------------------:|:--------:|
|moveit_ros    |              |                                  | :white_medium_square:        | :white_medium_square:|          |
|              | planning     |                                  | :white_medium_square:        | :white_medium_square:|          |
|              |              | robot_model_loader               | :heavy_check_mark:           |  :heavy_check_mark: |          |
|              |              | trajectory_execution_manager     | :heavy_check_mark:           | :white_medium_square:|          |
|              |              | planning_request_adapter_plugins | :heavy_check_mark:           |  :heavy_check_mark: |          |
|              |              | constraint_sampler_manager_loader| :heavy_check_mark:           |  :heavy_check_mark: |          |
|              |              | rdf_loader                       | :heavy_check_mark:           |  :heavy_check_mark: |          |
|              |              | planning_pipeline                | :heavy_check_mark:        | :heavy_check_mark:||
|              |              | plan_execution                   | :heavy_check_mark:           | :white_medium_square:|          |
|              |              | kinematics_plugin_loader         | :heavy_check_mark:           |  :heavy_check_mark: |          |
|              |              | planning_components_tools        | :heavy_check_mark:        | :heavy_check_mark:|No progress made for porting|
|              |              | collision_plugin_loader          | :heavy_check_mark:           | :white_medium_square:|          |
|              |              | planning_scene_monitor           | :heavy_check_mark:           | :white_medium_square:|          |
|              |benchmarks    |                                  | :heavy_check_mark:        | :heavy_check_mark:|No progress made for porting|
|              |manipulation  |                                  | :white_medium_square:        | :white_medium_square:||
|              |move_group    |                                  | :white_medium_square:        | :white_medium_square:||
|              |perception    |                                  | :heavy_check_mark:        | :heavy_check_mark:|No progress made for porting|
|              |planning_interface|                              | :white_medium_square:        | :white_medium_square:||
|              |              | py_bindings_tools        | :white_medium_square:        | :white_medium_square:||
|              |              | common_planning_interface_objects        | :white_medium_square:        | :white_medium_square:||
|              |              | planning_scene_interface        | :white_medium_square:        | :white_medium_square:||
|              |              | move_group_interface        | :white_medium_square:        | :white_medium_square:||
|              |              | robot_interface        | :white_medium_square:        | :white_medium_square:||
|              |              | test        | :white_medium_square:        | :white_medium_square:||
|              |robot_interaction|                               | :white_medium_square:        | :white_medium_square:||
|              |visualization |                                  | :white_medium_square:        | :white_medium_square:||
|              |warehouse     |                                  | :white_medium_square:        | :white_medium_square:||
|moveit_core   |              |                                  | :heavy_check_mark:           | :heavy_check_mark:   ||
|moveit_experimental   |              |                                  | :heavy_check_mark:          | :heavy_check_mark:   |No progress made for porting|
|moveit_kinematics   |              |                                  | :white_medium_square:          | :white_medium_square:   ||
| |cached_ik_kinematics_plugin|| :heavy_check_mark:| :heavy_check_mark:   |No progress made for porting|
| |ikfast_kinematics_plugin|| :heavy_check_mark:| :heavy_check_mark:   |No progress made for porting|
| |kdl_kinematics_plugin|| :white_medium_square:| :white_medium_square:   ||
| |lma_kinematics_plugin|| :white_medium_square:| :white_medium_square:   ||
| |srv_kinematics_plugin|| :white_medium_square:| :white_medium_square:   ||
| |test|| :white_medium_square: | :white_medium_square:   ||
|moveit_planners   |              |                                  | :white_medium_square:          | :white_medium_square:   ||
| |chomp|| :heavy_check_mark:| :heavy_check_mark:   |No progress made for porting|
| |ompl|| :white_medium_square:| :white_medium_square:   ||
| |sbpl|	| :heavy_check_mark:| :heavy_check_mark:   |No progress made for porting|
|moveit_plugins   |              |                                  | :white_medium_square:          | :white_medium_square:   ||
| | moveit_controller_manager_example | | :heavy_check_mark: | :heavy_check_mark: |No progress made for porting|
| | moveit_ros_control_interface | | :heavy_check_mark: | :heavy_check_mark: | No progress made for porting |
| | moveit_fake_controller_manager | | :white_medium_square: | :white_medium_square: ||
| | moveit_simple_controller_manager | | :white_medium_square: | :white_medium_square: ||
| moveit_setup_assistant| || :heavy_check_mark:| :heavy_check_mark:   |No progress made for porting|

**Comment by JafarAbdi** [comment]
This's a [link](https://docs.google.com/spreadsheets/d/1aPb3hNP213iPHQIYgcnCYh9cGFUlZmi_06E_9iTSsOI/edit?usp=sharing) to GSheet that show the progress

**Comment by henningkayser** [comment]
Closing this since it's documented in the Readme
