### ISSUE TITLE
Testing CI is broken with new version of rclcpp

### ISSUE THREAD

**Issue by vatanaksoytezer** [ros-planning/moveit2#1178]
We have a broken ci-testing with the changes from https://github.com/ros2/rclcpp/pull/1913. Currently working on fixing these.

**Comment by vatanaksoytezer** [comment]
They did a sync and now main is also broken: https://discourse.ros.org/t/preparing-for-rolling-sync-2022-04-12/25091

**Comment by vatanaksoytezer** [comment]
Example CI failure: https://github.com/ros-planning/moveit2/runs/6026254800?check_suite_focus=true

**Comment by DLu** [comment]
Possible fix: #1181
