### ISSUE TITLE
World MoveIt Day Tracks 2022

### ISSUE THREAD

**Issue by henningkayser** [ros-planning/moveit2#1219]
Tracks for World MoveIt Day 2022. These will have separate chat rooms with maintainers supporting groups of participants in working on various parts of MoveIt. The goal is to allow users to self-select based on their background and interests into different tracks where they can contribute.

**Contributors**: Please let us know what tracks or other work you are interested in.

**Tracks**:
* #1288
* #1293 
* #1292 
* #1291 
* #1290 
* #1289

**Comment by AndyZe** [comment]
I'm interested in tutorial cleanup and integrating the OMPL orientation constraints from #1273 (and the corresponding tutorial)
