### ISSUE TITLE
Plan and Execute in MoveGroupInterface return 'false' instead of MoveItErrorCode

### ISSUE THREAD

**Issue by tbastiaens-riwo** [ros-planning/moveit2#1239]
### Description
Plan, Execute and Move methods in MoveGroupInterface erroneously return 'false' instead of MoveItErrorCode 

### Your environment
* ROS Distro: Foxy
* OS Version: Ubuntu 20.04
* Source or Binary build? Source, foxy

### Steps to reproduce
- Call movegroupinterface.plan(Plan& plan), movegroupinterface.move(bool wait) or movegroupinterface.execute(const moveit_msgs::msg::RobotTrajectory& trajectory, bool wait) with a path that cannot succesfully be planned or executed, for whatever reason.

### Expected behaviour
Expected behaviour is to return a [MoveItErrorCode](https://github.com/ros-planning/moveit_msgs/blob/152f6f6ac1ec83e0028c806831a4fbca32008f5e/msg/MoveItErrorCodes.msg)

### Actual behaviour
The methods return 'false' if the error code is not 'rclcpp_action::ResultCode::SUCCEEDED'. This happens because of the following lines: [plan](https://github.com/ros-planning/moveit2/blob/4f83466a6a0de56ed8dcd670b46ecb7cdeb82f5c/moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp#L789), [move](https://github.com/ros-planning/moveit2/blob/4f83466a6a0de56ed8dcd670b46ecb7cdeb82f5c/moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp#L869), [execute](https://github.com/ros-planning/moveit2/blob/4f83466a6a0de56ed8dcd670b46ecb7cdeb82f5c/moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp#L939). This results in the MoveItErrorCode being interpreted as a value of '0', which is undefined according to [MoveItErrorCode](https://github.com/ros-planning/moveit_msgs/blob/152f6f6ac1ec83e0028c806831a4fbca32008f5e/msg/MoveItErrorCodes.msg)

### Suggested fix
Remove the 3 lines mentioned above such that 'return false' does not happen and instead the MoveItErrorCode is correctly returned.

**Comment by JafarAbdi** [comment]
Thanks @tbastiaens-riwo for the bug report, do you mind opening a PR that fixes this issue?

**Comment by tbastiaens-riwo** [comment]
Yes. It can be found here: [PR #1266](https://github.com/ros-planning/moveit2/pull/1266#issue-1243068938)
