### ISSUE TITLE
Humble Release

### ISSUE THREAD

**Issue by henningkayser** [ros-planning/moveit2#1269]
Tracking issue for the Humble Release steps:

- [x] Docker images, CI jobs #1270
- [x] Build Instructions https://github.com/ros-planning/moveit.ros.org/pull/717
- [x] Tag Release version
- [x] Bloom

**Comment by vatanaksoytezer** [comment]
Released!: https://github.com/ros/rosdistro/pull/33378

**Comment by bernharl** [comment]
While it's now been released, I still cannot install it using apt. Is there anywhere I can check on the progress of getting it in the ROS2 humble repos?

**Comment by gavanderhoorn** [comment]
[status_page/ros_humble_default.html?q=moveit](https://repo.ros2.org/status_page/ros_humble_default.html?q=moveit).

If/when the last square in the right column is green, you can use `apt` to install it from the main repositories.

You could already do it if you'd setup the testing repository though.

**Comment by vatanaksoytezer** [comment]
We are just waiting a new sync from OR, and you'll be able to use in the main repos. You should be able to apt install if you include testing repositories as in https://github.com/ros-planning/moveit2/blob/main/.docker/ci-testing/Dockerfile#L9
