### ISSUE TITLE
Re-implement dynamic_reconfigure

### ISSUE THREAD

**Issue by henningkayser** [ros-planning/moveit2#129]
We need to re-implement runtime updates of node parameters using `dynamic_reconfigure`.
A rather straight-forward approach would use parameter event callbacks as shown in this example:
https://github.com/ros2/tutorials/blob/master/rclcpp_tutorials/src/parameters/parameter_events.cpp

The only downside I see is that we don't automatically register "configurable nodes" and there is no `reconfigure_gui` anymore. Also, we will need to update the client sides or at least provide migration steps.

One example where `dynamic_reconfigure` is used in the ompl planner interface: https://github.com/ros-planning/moveit2/blob/cd27142259e13d4b34072bdc6e823288cc234d99/moveit_planners/ompl/ompl_interface/src/ompl_planner_manager.cpp#L262

@mkhansen-intel how did you handle this with navigation2?

**Comment by mkhansen-intel** [comment]
Henning, I believe rqt_reconfigure is available now for dashing:
https://github.com/ros-visualization/rqt_reconfigure/tree/dashing

We have not implemented the reconfigure callbacks as of yet, but here is one PR to do so for AMCL.
https://github.com/ros-planning/navigation2/pull/1378

**Comment by henningkayser** [comment]
> Henning, I believe rqt_reconfigure is available now for dashing:
> https://github.com/ros-visualization/rqt_reconfigure/tree/dashing
> 

Thanks, I wasn't aware of this one.

> We have not implemented the reconfigure callbacks as of yet, but here is one PR to do so for AMCL.
> [ros-planning/navigation2#1378](https://github.com/ros-planning/navigation2/pull/1378)

Great to have this as an example.

**Comment by mkhansen-intel** [comment]
Henning, there is also a PR in progress to create a ParameterEventsSubscriber class in rclcpp:
https://github.com/ros2/rclcpp/pull/829

If you have time please take a look at it and provide any feedback if it is useful for MoveIt2.

**Comment by henningkayser** [comment]
With https://github.com/PickNikRobotics/generate_parameter_library being applied, this issue can be closed.
