### ISSUE TITLE
WMD Track: MSA

### ISSUE THREAD

**Issue by vatanaksoytezer** [ros-planning/moveit2#1290]
This track would support getting MSA into the main branch. The main issues we would like to resolve in WMD include

- #1261
- #1262
- #1263

#1261 is the big priority here since it is the main blocker. In the end, we would like to merge the [feature/msa](https://github.com/ros-planning/moveit2/pull/1254) branch. It is mainly being held up since the generated launch files do not work straight out of the box.

**Comment by abake48** [comment]
@vatanaksoytezer @DLu I would love to help take on one of these issues if no one has already signed up to do so.

**Comment by mikeferguson** [comment]
World MoveIt Day is over, looks like most of these are merged now with the feature/msa branch merged. Remaining work remains ticketed separately.
