### ISSUE TITLE
WMD Track: Tutorial cleanup

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#1293]
This track will be about tutorial cleanup (https://github.com/ros-planning/moveit2_tutorials).

I'll help people select and scope their work, and guide them to get contributions finished and merged.

There are tons of things to clean up. Here are a few that come to mind:

- Finish and merge PR's that are already open (https://github.com/ros-planning/moveit2_tutorials/pulls)

- There are two MoveIt Task Constructor tutorials. We should consolidate to one. Suggest deleting this one:  https://moveit.picknik.ai/humble/doc/examples/moveit_task_constructor/moveit_task_constructor_tutorial.html

- A dual-arm tutorial. There was one started [here](https://github.com/ros-planning/moveit2_tutorials/pull/391) and I can give excellent guidance on this task.

Anybody (@tylerjw) please feel free to add more ideas.

**Comment by AndrejOrsula** [comment]
Hello!

If it is alright and available, I would take a look at [`moveit_calibration`](https://github.com/ros-planning/moveit_calibration/tree/ros2).
Primary objectives:
1. See what is missing from [moveit_calibration#101 ([WIP] ROS2 Port)](https://github.com/ros-planning/moveit_calibration/pull/101) and attempt to finalise it. Last messages under the related [issue#99](https://github.com/ros-planning/moveit_calibration/issues/99) claim that it is not currently functional.
2. *[If deemed relevant]* Setup simulation environments in ~Ignition~ Gazebo (target `fortress`) to provide a simplified method of testing/demonstrating/developing both `eye-in-hand` and `eye-to-hand` scenarios, without having to hassle with real robot setups. I am not sure if something like that already exists, so please correct me if I am wrong.
3. Update [Hand-Eye Calibration tutorial](https://github.com/ros-planning/moveit2_tutorials/blob/f21b6b3b99f7d8d9a9619a3793bdf053f9b9e193/doc/examples/hand_eye_calibration/hand_eye_calibration_tutorial.rst) for ROS 2

Please, let me know what you think. Thank you.

PS: I am not sure what WMD Track this would belong to, but this issue seemed like the best place for it. :smile:

---

Also, if you think there is anything relevant for tutorials / MSA in any of these repositories (and not already present/planned in `moveit2` repos), then I would be happy to work on that as well. 
- [pymoveit2](https://github.com/AndrejOrsula/pymoveit2)
- [ign_moveit2_examples](https://github.com/AndrejOrsula/ign_moveit2_examples)
- [panda_ign_moveit2](https://github.com/AndrejOrsula/panda_ign_moveit2)

**Comment by vatanaksoytezer** [comment]
Hey @AndrejOrsula thanks for all the work so far!

> Also, if you think there is anything relevant for tutorials / MSA in any of these repositories (and not already present/planned in `moveit2` repos), then I would be happy to work on that as well.

Although I think calibration would be a higher priority, eventually,  a tutorial that demonstrates how to use ~Ignition~ Gazebo with MoveIt 2 and ros2_control would be very valuable.

**Comment by AndyZe** [comment]
Is anybody interested in taking on a dual-arm tutorial? I can give guidance and I have example code to refer to. That seems like a high priority

**Comment by pabloinigoblasco** [comment]
We tried to make work any demo of ros2_control, moveit and multiple arms a few times in these last months. We didnt success and I think that is not currently possible. I will try to explain our conclusions:

- There are like a few possible strategies:
    - using namespaces
    - using remapping
    - using one single robot and one single moveit_interface_client for the whole robot

General conclusions:
  - ros2_control likes topic/action remapping for multiple arms (over controllers in namespaces)
  - moveit likes namespaces for multiple arms (over multiple nodes in the same level and remapping)

- **It is not possible to work with a mixture solution.** if movegroup works in a namespace it looks like it cant connect with a controller manager in the root level.

- **moveit does not work well with topic/actions remapping in the same namespace**, we found this is specially clear when you work with multiple moveit_client_interfaces. There isnt a way to avoid collisions between move_groups and move_group_interface clients just with action/topic remapping (without namespaces)

The only potential solution we did not test is something like having one single robot description with two arms. In our case we wanted to use ur5, and that would have been implied to do a lot of work on ur5_description to work well in the same robot.

That's it.

**Comment by tiffanyec** [comment]
I'll consolidate the task constructor tutorials. The one we want to keep is this one right? https://moveit.picknik.ai/main/doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.html

**Comment by AndyZe** [comment]
Correct! Thank you  :+1:

**Comment by AndyZe** [comment]
Closing because World MoveIt Day is over. Thanks everybody.
