### ISSUE TITLE
[moveit_configs_utils] Load sensors_3d.yaml 

### ISSUE THREAD

**Issue by DLu** [ros-planning/moveit2#1297]
One of the standard MSA-generated files is `config/sensors_3d.yaml` but `moveit_configs_utils` never loads it. 

A new data field should be added to the structure [here](https://github.com/ros-planning/moveit2/blob/main/moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py#L103) along with a method in the `MoveItConfigsBuilder` to load it.

**Comment by mikeferguson** [comment]
I'm gonna self-assign this - I have it working locally (although it looks like we also need to update the sensors_3d.yaml) and will work on getting a PR going over the next day or two

**Comment by mikeferguson** [comment]
Ticketed the MSA updates separately here: https://github.com/ros-planning/moveit2/issues/1388
