### ISSUE TITLE
Release Branch Naming

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit2#130]
I'd like to propose for MoveIt 2 we break away from the old "legacy" approach to branch naming we've been following in MoveIt 1. Our current branching strategy in MoveIt 1:

``master`` - development branch
``kinetic-devel`` - release branch for ROS Kinetic / 16.04
``melodic-devel`` - release branch for ROS Melodic / 18.04

As someone with fresh eyes @jliukkonen just pointed out, we should remove the "-devel" part.

For MoveIt 2, how about something like:

``master`` - development branch
``eloquent`` - release branch for ROS 2 Eloquent / 18.04
``foxy`` - release branch for ROS 2 Foxy

On top of this, we will continue to use git ``tags`` to release specific version numbers e.g. ``2.1`` ``2.2`` 

I'm very open to other ideas - thoughts? @henningkayser  @rhaschke @v4hn

Let's not close this issue until we document the decision on our website or else where.

**Comment by henningkayser** [comment]
I'm closing this. We've been dropping `-devel` from the start and `main` is our dev target. I think we've sufficiently documented the meaning of the branches in the [install instructions now](https://moveit.ros.org/install-moveit2/source/).
