### ISSUE TITLE
`ompl_interface` does not support `start_state_max_bounds_error` parameter

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#1323]
Grepping in the ompl_interface package, I don't see that the `start_state_max_bounds_error` parameter is used anywhere.

**Comment by henningkayser** [comment]
It's being used by the start_state_max_bounds planner adapter https://github.com/ros-planning/moveit2/blob/main/moveit_ros/planning/planning_request_adapter_plugins/src/fix_start_state_bounds.cpp#L202
