### ISSUE TITLE
distanceToCollision returning -1 for custom robot URDF

### ISSUE THREAD

**Issue by rohantiw1996** [ros-planning/moveit2#1362]
### Description

Overview of your issue here.
distanceToCollision in planning_scene,h always returns -1 for custom robot URDF. I am using  FCL collision checker.
### Your environment
* ROS2 Distro: Galactic 
* OS Version: Ubuntu 20.04

### Expected behaviour
Return the minimum distance to collision object

### Actual behaviour
Returns -1 for all cases

**Comment by henningkayser** [comment]
@rohantiw1996 have you tried with Humble or Rolling? Galactic is eol, so I'm closing this for now. Please report back if it exists for supported distros.
