### ISSUE TITLE
Chainable Admittance Controller

### ISSUE THREAD

**Issue by pac48** [ros-planning/moveit2#1371]
My primary goal is to reduce P-stop during trajectory execution. 

This can be achieved via admittance control, but it will require some open source contribution. First, Denis' admittance controller (https://github.com/ros-controls/ros2_controllers/pull/173) needs to be refactored into the new chainable controller pattern (https://github.com/ros-controls/ros2_control/pull/667). Second, Denis' controller depended on a kinematics interface, but it never made it into ros2_control. Third, I need to make a PR and merge the refactored admittance controller into ros2_controllers. This can be broken into sub goals:

- Create a kinematics interface with KDL implementation under ros-control organization: (see https://github.com/ros-controls/kinematics_interface/pull/1)
- Create a generic node interface for moveit2, so its kinematics/inverse kinematics can be used in the ROS 2 control loop: see (https://github.com/ros-planning/moveit2/pull/1329)
- Create a moveit2 implementation for the kinematics plugin (probably will be located in moveit2 repo) 
- Create admittance controller that conforms to the chainable controller interface (will merge into ros2_controllers) 

Integrating the admittance controller into ros2_controllers will help ensure that it is supported long term.

**Comment by mhubii** [comment]
Hi @pac48. Random question, did you manage to run the chainable admittance controller with MoveIt in the end?

I am struggling to have MoveIt play along nicely with the joint names that are exposed by chainable controllers. E.g. MoveIt is configured to use `joint_xyz`, but chainable controllers expose `controller_name/joint_xyz`.

Thank you for the help!
