### ISSUE TITLE
Release Rolling 2.6

### ISSUE THREAD

**Issue by henningkayser** [ros-planning/moveit2#1410]
A new Rolling release is due by mid July, possibly also for Humble.
Rolling should be bumped to 2.6, Humble to 2.5.2.

**Comment by vatanaksoytezer** [comment]
@henningkayser if we want we can cut it earlier, since MSA is merged and this would be the first release containing MSA.

**Comment by vatanaksoytezer** [comment]
Also shouldn't we do 2.5.2 on Rolling as well, given we did not diverge for Humble yet.

**Comment by henningkayser** [comment]
I think we did converge, at least with the sync? Of course we could cut it earlier, though.

**Comment by Llavrih** [comment]
Any updates for Humble?

**Comment by vatanaksoytezer** [comment]
@Llavrih we will cut a new release for both Humble and Rolling within this week. An eatlier version was already released to Humble and available as binary if you need to use though.

**Comment by jure-no** [comment]
Hello, can we expect to get humble version over the weekend?

**Comment by vatanaksoytezer** [comment]
@jure-no yes, we will cut the release, but it may take a few days for ros folks to merge our PR to rosdistro, and a few weeks to get it synced to main repositories.

**Comment by vatanaksoytezer** [comment]
2.5.2 and 2.5.3 are released, thus closing this.
