### ISSUE TITLE
Add optional thread priority setting to Servo

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#1438]
Similar to what was done here:

https://github.com/ros-controls/ros2_control/pull/768

https://github.com/ros-controls/ros2_control/pull/781

**Comment by Kzernobog** [comment]
Hi, I was wondering if there was anyone on this. Was planning to start working on the library and wanted your opinion if this was a good first issue?

**Comment by AndyZe** [comment]
Thanks for offering, @Kzernobog! Some of the work was already done. For example, see:  https://github.com/ros-planning/moveit2/blob/8bfe782d6254997d185644fa3eb358d2b79d69b2/moveit_ros/moveit_servo/src/servo_calcs.cpp#L71

I think you could improve this by making the thread priority a parameter instead of a hard-coded constant like this:

`int const THREAD_PRIORITY = 40;`

**Comment by AndyZe** [comment]
If you want to make a more significant contribution, here are some bigger ideas we could talk about:  https://moveit.ros.org/events/2023-google-summer-of-code/#improved-realtime-control-with-moveit-servo

**Comment by AndyZe** [comment]
This was completed in #1464

**Comment by Kzernobog** [comment]
Count me in @AndyZe. How do I get started on this?

**Comment by AndyZe** [comment]
Awesome. Let me have a meeting with @henningkayser then I'll get back to you next week with a plan

**Comment by Kzernobog** [comment]
Sure thing @AndyZe. Shall I apply via GSoC?

**Comment by AndyZe** [comment]
Here's the website link (in case you haven't found it already) with some hints at the bottom:  https://moveit.ros.org/events/2023-google-summer-of-code/
