### ISSUE TITLE
Automatically choose the number of waypoints passed to Ruckig at once

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#1439]
The Ruckig trajectory smoother currently stretches the entire trajectory in time until all kinematic limits are obeyed. This works but it can slow the trajectory more than necessary. It's better to feed in just a few waypoints at once so only the waypoints needing it get stretched.

The downside of passing just a few waypoints at once is very long runtimes if the trajectory is very large. So, I think the number of waypoints passed to Ruckig should be chosen in a smarter way.

Attached is some code to feed in a configurable number of waypoints.

[process_waypoints_in_chunks.txt](https://github.com/ros-planning/moveit2/files/9150216/process_waypoints_in_chunks.txt)

A good way to select the number of waypoints is probably:

- The smaller of (100 waypoints, 10% of waypoints)

**Comment by swiz23** [comment]
Hi @AndyZe,

Decided to test out the PR for adjustable waypoint batch sizes yesterday. Saw something interesting. Refer to the table below and the attached 2 CSV files showing all waypoints. You'll notice that when ruckig is run in batches, it can lengthen the trajectory an unexpected amount. It's unclear to me why. Any ideas? Note that I left the default arguments in runRuckigInBatches.

![Screenshot from 2023-01-06 13-48-33](https://user-images.githubusercontent.com/31753673/211078776-cc0c2006-e4ed-4d19-8c1f-dd0880131b4d.png)

[Motion_1.txt](https://github.com/ros-planning/moveit2/files/10362381/Motion_1.txt)

[Motion_2.txt](https://github.com/ros-planning/moveit2/files/10362383/Motion_2.txt)

**Comment by AndyZe** [comment]
@swiz23 thanks for testing. I'll likely be looking into this soon. I'll open a new issue for this.

Closing this issue b/c it was completed by #1719

**Comment by AndyZe** [comment]
New issue to track the bug noticed by @swiz23:  #1960
