### ISSUE TITLE
Cleanup of servo example launch file

### ISSUE THREAD

**Issue by wyattrees** [ros-planning/moveit2#1441]
The [example servo launch file](https://github.com/ros-planning/moveit2/blob/b9543801be0fdcac6b157d3907d5f33c83ef438c/moveit_ros/moveit_servo/launch/servo_example.launch.py#L107-L118) contains some commented out code for making the servo node a `ComposableNode`, but it's unclear if it would actually work that way.

We should test if it works properly & if performance is improved and either:
- Uncomment it and remove the standalone servo node below the `ComposableNodeContainer`
- Remove the commented code

**Comment by henningkayser** [comment]
the launch files have been re-implemented, closing this
