### ISSUE TITLE
Error calling IKCallbackFn from IK Solver

### ISSUE THREAD

**Issue by ravnicas** [ros-planning/moveit2#1447]
### Description

On humble and higher an error is thrown using a port of trac-ik solver. Error wasn't obvious or didnt trigger on galactic or lower, until 2.4.x.

### Your environment
* ROS Distro: Humble
* OS Version: Ubuntu 22
* Source or Binary build? Source
* If binary, which release version? Humble, tags: 2.5.0, 2.5.1, 2.5.2

### Steps to reproduce
Clone and build this [repo](https://github.com/ravnicas/trac_ik). Plan any robot with a Pose Goal.

### Expected behaviour
A solution should be returned.

### Actual behaviour
This error is thrown.

As far as got, the solver does actually solve the ik problem, the error is thrown somewhere in the IKCallbackFn.

### Backtrace or Console output
[backtrace](https://gist.github.com/ravnicas/690ead6978118bb978a850bf784b1657)

**Comment by vatanaksoytezer** [comment]
Hello @ravnicas, thank you very much for reporting the issue. Which port of trac-ik are you using? I haven't seen something similar before with other IK solvers, so I'm questioning whether it might be related to trac-ik port you are using.

**Comment by ravnicas** [comment]
I linked the port of trac-ik which I'm using. The lib was ported by another user, I mostly ported the plugin part.

It was functional on foxy and galactic.

**Comment by ravnicas** [comment]
i didn't see the change from boost::bind to std::bind immediatly.. therefore my solution_callback was wrong in newer versions.
