### ISSUE TITLE
Convert parameter lookup separator

### ISSUE THREAD

**Issue by JafarAbdi** [ros-planning/moveit2#147]
In the MoveIt2 codebase, we are using `/` as a separator which isn't the case for ROS2, we should use `.` as a separator

References:
- [1](https://github.com/ros2/rclcpp/blob/master/rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp#L791)
- [2](https://answers.ros.org/question/321243/ros-2-layered-yaml-config-file/)

**Comment by henningkayser** [comment]
@JafarAbdi do we still need to track this here?

**Comment by JafarAbdi** [comment]
They're fixed in the current main branch
