### ISSUE TITLE
Create Docker containers for MoveIt2

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit2#15]
- Should be built on top of [OSRF's ROS2 docker containers](https://hub.docker.com/r/osrf/ros2/). 
- Is hosted at: https://cloud.docker.com/u/moveit/repository/docker/moveit/moveit2

**Comment by vmayoral** [comment]
@LanderU, you've got tons of experience with this, any chance you can help with it?

**Comment by davetcoleman** [comment]
Can create a PR for that to start the conversation?

**Comment by davetcoleman** [comment]
@henningkayser is going to help migrate the moveit1 dockers and set it up on dockerhub:

https://github.com/ros-planning/moveit/tree/master/.docker
