### ISSUE TITLE
robot_description parameter syncing

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2#1511]
A single node should receive the robot_description config and all other nodes that share the need for that parameter should get it from that one node. The way this works should be made simpler and standardized.

If this is via a global parameter server, latched topics, or the ROS 2 parameter interface, should be investigated for the various tradeoffs to each approach.

**Comment by mikeferguson** [comment]
I think the "standard" approach for ROS2 is to use the "robot_description" topic - usually published by the "robot_state_publisher". RVIZ supports this and so far in my experience, moveit2 is the only thing managing a second copy of the robot_description in it's parameters.

**Comment by henningkayser** [comment]
While parameter syncing is a very valid approach, we have already had topic syncing implemented for a while.. I'm closing this for now, we can address this again once we are dealing with synchronization issues with things like dynamic robot models.
