### ISSUE TITLE
Revise XML-RPC parameter lookup 

### ISSUE THREAD

**Issue by JafarAbdi** [ros-planning/moveit2#155]
One suggested [approach](https://github.com/ros-planning/moveit2/pull/148#discussion_r360469027), [2](https://github.com/ros-planning/moveit2/pull/158#issuecomment-578187165)

**Comment by henningkayser** [comment]
I think currently the yaml approach is the way to go. In addition, I think we should make use of `rclcpp::Node::declare_parameter()` for all (even optional) parameters. This enables much better control about what parameters should be provided, for instance by providing additional descriptions with the declaration.
