### ISSUE TITLE
Mixed constraints support issue

### ISSUE THREAD

**Issue by jih189** [ros-planning/moveit2#1552]
Based on what stephanie-eng:seng/multiple-constraints(https://github.com/ros-planning/moveit2/pull/1319) has, the mixed constraints should be supported, but the code looks strange to me. In the planning_context_manager.cpp, line 539 to line [544,](https://github.com/stephanie-eng/moveit2/blob/68da67770605628c1043abaf9c60c2d331951036/moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp#L542), it still said "Mixed constraints are not supported", and it only allows one constraint based on the if statement.
`  if (constrained_planning_iterator != pc->second.config.end() &&
      boost::lexical_cast<bool>(constrained_planning_iterator->second) &&
      ((req.path_constraints.position_constraints.size() == 1) !=
       (req.path_constraints.orientation_constraints.size() == 1)))`

_Originally posted by @jih189 in https://github.com/ros-planning/moveit2/issues/1319#issuecomment-1237524367_

**Comment by tylerjw** [comment]
@stephanie-eng
