### ISSUE TITLE
Tutorial panda robot not shown in rviz2

### ISSUE THREAD

**Issue by Gleis1234** [ros-planning/moveit2#1596]
### Description

In the Getting Started tutorial https://moveit.picknik.ai/humble/doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.html Step 1 the demo is launched. The panda robot arm should be shown in rviz2. This does not work

### Your environment
* ROS Distro: Humble 
* OS Version: 22.04
* Binary build
* If binary, which release version?
* If source, which branch?

### Steps to reproduce
Launch demo: 
``` 
ros2 launch moveit2_tutorials demo.launch.py rviz_tutorial:=true 
```
The motion planning display style is already selected, also /panda_link0 as fixed frame is entered.

### Expected behaviour
Rviz2 opens and the robot arm is shown in the window.

### Actual behaviour
Rviz2 opens, but the window shows an empty grid.

### Backtrace or Console output
[[rviz2-1] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occurred with plugin factory for class rviz_default_plugins::displays::InteractiveMarkerDisplay. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
[rviz2-1]          at line 253 in /opt/ros/humble/include/class_loader/class_loader/class_loader_core.hpp
[rviz2-1] [ERROR] [1664800782.948878720] [moveit_ros_visualization.motion_planning_frame]: Action server: /recognize_objects not available
[rviz2-1] [INFO] [1664800782.977610024] [moveit_ros_visualization.motion_planning_frame]: MoveGroup namespace changed: / -> . Reloading params.
[rviz2-1] [INFO] [1664800782.988861299] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00549758 seconds
[rviz2-1] [INFO] [1664800782.988957820] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[rviz2-1] [INFO] [1664800783.541611722] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00391155 seconds
[rviz2-1] [INFO] [1664800783.541687151] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[rviz2-1] [ERROR] [1664800783.559800993] [moveit_background_processing.background_processing]: Exception caught while processing action 'loadRobotModel': parameter 'robot_description_planning.joint_limits.panda_joint1.max_velocity' has invalid type: Wrong parameter type, parameter {robot_description_planning.joint_limits.panda_joint1.max_velocity} is of type {double}, setting it to {string} is not allowed.
[rviz2-1] [INFO] [1664800783.562051220] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00222893 seconds
[rviz2-1] [INFO] [1664800783.562092566] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[rviz2-1] [ERROR] [1664800783.567869445] [moveit_background_processing.background_processing]: Exception caught while processing action 'loadRobotModel': parameter 'robot_description_planning.joint_limits.panda_joint1.max_velocity' has invalid type: Wrong parameter type, parameter {robot_description_planning.joint_limits.panda_joint1.max_velocity} is of type {double}, setting it to {string} is not allowed.

]

During the build there is an error noted:

[stderr: moveit_setup_srdf_plugins                                             
/home/guenther/ws_moveit2/src/moveit2/moveit_setup_assistant/moveit_setup_srdf_plugins/include/moveit_setup_srdf_plugins/rotated_header_view.hpp:0: Note: No relevant classes found. No output generated.
]

**Comment by Nils-ChristianIseke** [comment]
@Gleis1234 Can not reproduce the error. As soon as i add the MotionPlanning Plugin (following the [tutorial](https://moveit.picknik.ai/humble/doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.html)) the robot is shown in rviz.

I had the same issue some time ago, i think i solved it by doing a clean build, therefore removing the workspace:

```
rm -r ~/ws_moveit2/
```
After that following the [tutorial](https://moveit.picknik.ai/humble/doc/tutorials/getting_started/getting_started.html) again helped. Following the tutorial you need to switch to the humble branch of moveit2 after the command` vcs import < moveit2_tutorials/moveit2_tutorials.repos` : 
```
cd ~/ws_moveit2/src/moveit2
git switch humble
cd ..
```

**Comment by Gleis1234** [comment]
@Nils-ChristianIseke Do you build from the src dir or from the workspace dir?

**Comment by AndyZe** [comment]
Can you paste a screenshot of RViz after you add the Motion Planning Display?

Also, can you please try switching to Cyclone DDS? It's very easy to switch, just install it:

  `sudo apt install ros-rolling-rmw-cyclonedds-cpp`
  
Then source it. You may want to add this to ~/.bashrc to source it automatically
  
  `export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp`

**Comment by Gleis1234** [comment]
![Screenshot_RVIZ](https://user-images.githubusercontent.com/36842709/193628927-1e3e1e2a-bd54-446c-9837-8a08424bb6a7.png)
I wonder that "Motion Planning", "Trajectory" and "Planning Scene" were already added to the Displays window.
I will try to switch to Cyclone DDS.

**Comment by AndyZe** [comment]
You could also add a `tf` display and verify that the tf frames are there. I bet they will be.

**Comment by Gleis1234** [comment]
@AndyZe Did you see the exception 
```
[rviz2-1] [ERROR] [1664800783.559800993] [moveit_background_processing.background_processing]: Exception caught while processing action 'loadRobotModel': parameter 'robot_description_planning.joint_limits.panda_joint1.max_velocity' has invalid type: Wrong parameter type, parameter {robot_description_planning.joint_limits.panda_joint1.max_velocity} is of type {double}, setting it to {string} is not allowed.
```
?

**Comment by AndyZe** [comment]
I did not. That parameter comes from here:   https://github.com/ros-planning/moveit_resources/blob/ros2/panda_moveit_config/config/joint_limits.yaml

Seems OK to me?

I'll fire up my Ubuntu22 and test it

**Comment by Gleis1234** [comment]
I think I found the point. I had activated german locals.
Thank you for the support. The hint to the yaml showed my the the right way.
