### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by vmayoral** [ros-planning/moveit2#16]
@LanderU, I see you fixed CI in https://github.com/AcutronicRobotics/moveit2/tree/master.

I started a branch at https://github.com/AcutronicRobotics/moveit2/tree/ci for making a PR once it was working (now is!). Would you like me to go ahead and cherry-pick all your changes and then submit the PR myself or would you rather like to do it yourself?

**Comment by davetcoleman** [comment]
Much needed testing!

**Comment by vmayoral** [comment]
We will also take care of this ticket, work in progress for now.

**Comment by vmayoral** [comment]
@LanderU, after a few days of testing, I'd say our CI prototype is ready for a PR. We need to submit only the CI-related changes. Would you like to submit the PR yourself or should I go ahead an do it?

**Comment by LanderU** [comment]
> Would you like to submit the PR yourself or should I go ahead an do it?

Feel free to go ahead.

**Comment by davetcoleman** [comment]
@mlautman is going to help convert https://github.com/ros-planning/moveit_ci/ to be ros2 compatible. its been a many years effort to build a very comprehensive set of tests for the code base, between myself and @rhaschke

**Comment by vmayoral** [comment]
That is great to hear, thanks @davetcoleman. We will monitor the progress and contribute by ensuring we pick this in our hardware tests. To do so more easily, https://github.com/ros-planning/moveit_resources/pull/24 should probably be considered. It would also help very much getting a unified infrastructure altogether with the hardware CI we are planning.

@ahcorde and @LanderU this will be interesting for you.

**Comment by davetcoleman** [comment]
@henningkayser can this issue be closed?
