### ISSUE TITLE
Enable deprecated declarations warning as error in move_group_interface

### ISSUE THREAD

**Issue by Abishalini** [ros-planning/moveit2#1608]
Revert PR #1598 once humble support is discontinued on the main branch.

Replace `rmw_qos_profile_services_default` with `rclcpp::SystemDefaultsQoS()` in the `create_client` functin call in `move_group_interface.cpp`

**Comment by tylerjw** [comment]
@Abishalini I think I found a way to do this and still support Humble and Rolling from the main branch here: https://github.com/ros-planning/moveit2/pull/1620

Would you mind reviewing that change?
