### ISSUE TITLE
'std::length_error' on load Planning scene in foxy

### ISSUE THREAD

**Issue by SmarkSauer** [ros-planning/moveit2#1625]
### Description
* ROS Distro: Foxy
* OS Version:Ubuntu 20.04
* Binary

Rviz Crashes on loading a planning scene:

[rviz2-1] [INFO] [1666187620.931024455] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[rviz2-1] [INFO] [1666187620.934407915] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/monitored_planning_scene'
[rviz2-1] terminate called after throwing an instance of 'std::length_error'
[rviz2-1]   what():  Exceeded upper bound

**Comment by henningkayser** [comment]
@SmarkSauer have you found out a bit more about this in the meantime? It's hard to debug this without more context 
 like a backtrace log. Would switching to a new distro like Humble work for you?

**Comment by henningkayser** [comment]
Foxy is deprecated
