### ISSUE TITLE
TrajectoryExecutionManager's default controller selection logic incorrectly prefers to use inactive controllers

### ISSUE THREAD

**Issue by schornakj** [ros-planning/moveit2#1631]
### Your environment
* Humble
* Ubuntu 22.04
* 2.5.3

### Steps to reproduce
Use a robot with two controllers that both actuate the same set of joints, and code where MoveIt has to independently select which controller to use for a given trajectory (i.e., no user-specified controller).

### Expected behaviour
The TrajectoryExecutionManager uses the already-active controller to execute the trajectory.

### Actual behaviour
The TrajectoryExecutionManager deactivates the already-active controller, activates the inactive controller, and attempts to use it to execute the trajectory (without success, since this controller does not necessarily accept FollowJointTrajectory action goals).

### Suspicious Code

I think [these lines in `trajectory_execution_manager.cpp`](https://github.com/ros-planning/moveit2/blob/b050890a2632a723dd95c08542ef6ed57d77fb06/moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp#L500-L504) are at fault:

```
    if (nractive[a] < nractive[b])
      return true;
    if (nractive[a] > nractive[b])
      return false;
```

As written, the comparison gives a higher rank to controllers where `nractive` is smaller, which is the case where the controller is not active.

**Comment by henningkayser** [comment]
@schornakj any updates for this issue?
