### ISSUE TITLE
Typo in ControllerManager deprecation warning

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#1687]
There's a typo here, it should say:

      RCLCPP_WARN(LOGGER, "moveit_ros_control_interface/MoveItControllerManager is deprecated. Replace with "
                          "`moveit_ros_control_interface/Ros2ControllerManager.`");

https://github.com/ros-planning/moveit2/blob/8c29ad9fa3e8a1fdd8e0c8d232b9273bc5754997/moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp#L139

**Comment by AndyZe** [comment]
Maybe a good issue for @abhijelly ? I'll approve quickly   ;)

**Comment by abhijelly** [comment]
> Maybe a good issue for @abhijelly ? I'll approve quickly ;)

i got you :)  #1688
