### ISSUE TITLE
Remove _ suffix from struct member variables

### ISSUE THREAD

**Issue by sjahr** [ros-planning/moveit2#1689]
The _ suffix is a naming convention for private member variables of classes, not public struct members. Therefore, the _ suffix of members of [MotionPlanResponse](https://github.com/ros-planning/moveit2/blob/8c29ad9fa3e8a1fdd8e0c8d232b9273bc5754997/moveit_core/planning_interface/include/moveit/planning_interface/planning_response.h#L46) and [MotionPlanDetailedResponse](https://github.com/ros-planning/moveit2/blob/8c29ad9fa3e8a1fdd8e0c8d232b9273bc5754997/moveit_core/planning_interface/include/moveit/planning_interface/planning_response.h#L59) should be removed.

**Comment by JoaoVitorMenezesMagalhaes** [comment]
Hello @sjahr!! Can you assign me to this issue, please ?

**Comment by JoaoVitorMenezesMagalhaes** [comment]
I believe i have fixed it with my PR #1693

**Comment by AlexWebb03** [comment]
Hiya, I'd like to work on this. Should I finish @JoaoVitorMenezesMagalhaes MR or open a new one?

**Comment by sjahr** [comment]
@AlexWebb03 Great thank you!

> Should I finish @JoaoVitorMenezesMagalhaes PR or open a new one?

Whatever you prefer :+1:
