### ISSUE TITLE
Add ability to load robot description of RobotState plugin from topic and file

### ISSUE THREAD

**Issue by JafarAbdi** [ros-planning/moveit2#169]
Copying Mike's comment from this [PR](https://github.com/ros-planning/moveit2/pull/168)

> I still think that the robot_description should be able to come from either a parameter, topic, or file like the RobotModelDisplay. Just using parameters doesn't make that much sense as it requires Rviz to be launched with special arguments

I think this's the rdf_loader responsibility, we should add a new constructor for rdf_loader to do so

**Comment by henningkayser** [comment]
Continued in #755
