### ISSUE TITLE
Fix private github actions

### ISSUE THREAD

**Issue by rhaschke** [ros-planning/moveit2#1705]
@JafarAbdi and @vatanaksoytezer,
your github actions used for CI require an update to get rid of CI warnings:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands

**Comment by JafarAbdi** [comment]
Should be fixed with https://github.com/JafarAbdi/latest-rosdistro-release-date-action/commit/4bd1c0ce4261b03d85c3ef29b0e507f20d2d60b1

**Comment by henningkayser** [comment]
Looks like it's fixed for both actions
