### ISSUE TITLE
Migrate to clang-format-14

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2#1736]
As we are now firmly on Ubuntu 22.04 it makes sense to migrate to clang-format-14.

**Comment by henningkayser** [comment]
reopening for keeping track of the other PRs

**Comment by henningkayser** [comment]
I started fixing the clang-format versions in the other packages and figured that some packages don't even install clang-format. So, doesn't pre-commit already take care of that for us? Also, was there a reason we haven't switched to [pre-commit.ci](https://pre-commit.ci/) yet? (tagging @vatanaksoytezer)

**Comment by JafarAbdi** [comment]
Fixed with https://github.com/ros-planning/moveit2/pull/1877
