### ISSUE TITLE
Possible slowdown of RRT Connect when migrating from Foxy to Humble 

### ISSUE THREAD

**Issue by prajd3d** [ros-planning/moveit2#1802]
### Description

I am considering a migration of my codebase from Foxy to Humble.
In this process, I noted a slowdown of RRT Connect (and in general other planners as well) in Humble. RRT Connect is about 3 times slower in Humble than in Foxy.

I am working on a Dockerfile and a minimal example to show the performance difference.
Code was compiled using GCC 9.4 and targeted for a ARM64 (M1) machine.

Meanwhile, I was wondering if it is a known issue that someone is working on.

### Your environment
* ROS Distro: Foxy
* OS Version: e.g. Ubuntu 20.04
* Source or Binary build? Source
* If binary, which release version?
* If source, which branch? foxy

**Comment by sjahr** [comment]
Thanks for reporting this issue. A couple of question:

> In this process, I noted a slowdown of RRT Connect (and in general other planners as well) in Humble.

Are you talking about all MoveIt2 planners (OMPL, Pilz and CHOMP) or just planners of OMPL (for example RRTConnect, PRM, etc)?
 How are you measuring the time difference and Which OMPL version are you using on Foxy and Humble?

**Comment by prajd3d** [comment]
Sorry it took this long to get back with a Dockerized example.

I am only using OMPL RRT Connect. I am measuring the solve-time by taking an average over 100 runs of the same motion plan request. I am using the default version of OMPL for both Foxy and Humble (as in the `moveit/moveit2:humble-release` and `moveit/moveit2:foxy-release` Docker images).

Here is my repo for showing the difference in time-performances of OMPL RRT Connect. The instructions are also included and I have automated most of the setup via bash scripts to make it easy for reviewers.

https://github.com/prajd3d/moveit2_performance_issue_1802

**Comment by marioprats** [comment]
I tracked this down to a call to OMPL `print()`, which is expensive.
And looks like this was fixed already in https://github.com/ros-planning/moveit2/pull/2608, so this can be closed (should be already fixed in `iron`).

**Comment by sea-bass** [comment]
> I tracked this down to a call to OMPL `print()`, which is expensive. And looks like this was fixed already in #2608, so this can be closed (should be already fixed in `iron`).

Should we backport that PR to Humble, then? Seems pretty important.
