### ISSUE TITLE
Method for changing planning algorithm for a particular instance of a PlanningComponent.

### ISSUE THREAD

**Issue by Mariunil** [ros-planning/moveit2#181]
We are a couple of master students using Moveit 2 as our motion planning framework in our master's thesis, and are having difficulties changing the planning algorithm that is used for a chosen `PlanningComponent`. We are using OMPL as our planning pipeline, similar to the "run_moveit_cpp" demos. 

In the `PlanningComponent` class, we would like to have a method allowing us to specify what planner  from our loaded planning_pipeline we would like to use for this particular `PlanningComponent`.  

An alternative could be an option to change the default planner in `MoveitCpp`. For instance, it could be an optional parameter in the construction of the `MoveitCpp` instance, or a `set_default_planner(...)` method in the `MoveitCpp` class.

If there already exists ways of changing either the planner used for a particular `PlanningComponent` or the default planner, help finding these would be greatly appreciated.

**Comment by JafarAbdi** [comment]
Hi @Mariunil, Shouldn't calling `PlanningComponent::plan(const PlanRequestParameters& parameters)` with `planner_id` and `planning_pipeline` set do what you're looking for .?

Cheers,

**Comment by Mariunil** [comment]
Yes it would, must have missed that option. Thank you very much.
