### ISSUE TITLE
Planning Scene Monitor ignores planning_scene topic name

### ISSUE THREAD

**Issue by g-argyropoulos** [ros-planning/moveit2#1820]
### Description

It seems to me that the PlanningSceneMonitor ignores the topic name given as an argument to the function [startPublishingPlanningScene](https://github.com/ros-planning/moveit2/blob/main/moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp#L388l). This is, I think, because during construction ([step1](https://github.com/ros-planning/moveit2/blob/main/moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp#L116), [step2](https://github.com/ros-planning/moveit2/blob/main/moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp#L316), [step3](https://github.com/ros-planning/moveit2/blob/main/moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp#L640)), it creates a publisher with the default topic name which cannot be changed unless the function [stopPublishingPlanningScene](https://github.com/ros-planning/moveit2/blob/main/moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp#L374) is called.

In the case of MoveItCpp, the relevant piece of code lies [here](https://github.com/ros-planning/moveit2/blob/main/moveit_ros/planning/moveit_cpp/src/moveit_cpp.cpp#L105). An easy, albeit ugly, fix would be to call _stopPublishingPlanningScene_ just before that but this is relevant only to MoveItCpp whereas the problem is with PlanningSceneMonitor.

### Your environment
* ROS Distro: Humble (binary)
* OS Version: Ubuntu 22.04
* MoveIt2 from source (humble branch)

### Steps to reproduce
```
ros2 launch moveit2_tutorials moveit_cpp_tutorial.launch.py
```

### Expected behaviour
The planning scene monitor should publish the maintained planning scene on '/moveit_cpp/monitored_planning_scene' as per the relevant parameter in the [yaml configuration file](https://github.com/ros-planning/moveit2_tutorials/blob/main/doc/examples/moveit_cpp/config/moveit_cpp.yaml).

### Actual behaviour
The planning scene monitor publishes the maintained planning scene on '/monitored_planning_scene' which is the default topic name.

**Comment by henningkayser** [comment]
Hi @g-argyropoulos this is indeed annoying. The perfect way to fix this seems like refactoring the parameter layout using the (gen_parameters_library)[https://github.com/PickNikRobotics/generate_parameter_library] (started with https://github.com/ros-planning/moveit2/issues/335), and allowing to pass in a struct config with adequate topic names. For the current case, I would approve stopping the publisher initially as a workaround just to fix the intended behavior, and until a parameter refactoring is ready. I would add the `stopPublishingPlanningScene()` function to the beginning of `startPublishingPlanningScene()` as it's already done for other cases (see https://github.com/ros-planning/moveit2/blob/main/moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp#L1216). Would you mind filing a PR that does this, along with a note that this should be handled using the parameter API?
