### ISSUE TITLE
Suggestion: Remove library name from Loggers names (Migration)

### ISSUE THREAD

**Issue by ddengster** [ros-planning/moveit2#183]
So following the guidelines set out [here](https://github.com/ros-planning/moveit2/blob/master/doc/MIGRATION_GUIDE.md), I have a really long name like the following:

`static const rclcpp::Logger LOGGER = rclcpp::get_logger("moveit_move_group_default_capabilities.apply_planning_scene_service_capability");
`
May I suggest removing the library name requirement from that? Besides the obvious verbosity of the logging, most of the time when I search I only need the name of the cpp file.

**Comment by sjahr** [comment]
Closing this, since #1723 is opened now as an issue with an action item. Please re-open this issue if you feel to re-open this issue or comment in #1723 if you feel something is missing.
