### ISSUE TITLE
 Unknown CMake command "pkg_check_modules".

### ISSUE THREAD

**Issue by DreamLFairy** [ros-planning/moveit2#186]
I am building the moveit2 on windows 10.
When I build the moveit2,moveit_core not find pkg_config,so I pip install pkg_config.
but when I colcon build --merge-install ,it happend the Error:

CMake Error at CMakeLists.txt:32 (pkg_check_modules):
  Unknown CMake command "pkg_check_modules".

What should I do?Thanks for your reply

**Comment by JafarAbdi** [comment]
This should be fixed in the main branch
