### ISSUE TITLE
Filling position constraints is awkward

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#1871]
It's tedious to fill a position constraint or orientation constraint:  https://github.com/ros-planning/moveit_msgs/blob/master/msg/PositionConstraint.msg

It would be nice if there were convenience functions to easily add a position/orientation constraint for all links.

**Comment by henningkayser** [comment]
Here you go https://github.com/ros-planning/moveit2/blob/main/moveit_core/kinematic_constraints/include/moveit/kinematic_constraints/utils.h#L189

**Comment by AndyZe** [comment]
Thank you!
