### ISSUE TITLE
FastDDS runtime issues [Humble, Rolling]

### ISSUE THREAD

**Issue by henningkayser** [ros-planning/moveit2#1874]
This is a meta-issue for tracking the current situation with performance regressions, freezes and crashes with FastDDS.

* https://github.com/ros-planning/moveit2/issues/1848
* https://github.com/ros-planning/moveit2/issues/1842
* https://github.com/ros-planning/moveit2/issues/1810
* https://github.com/ros-planning/moveit2/issues/1596
* https://github.com/ros-planning/moveit2/issues/1474

**Workaround**

Currently, the only known workaround for most of these issues is to switch to the RMW vendor CycloneDDS:

```
sudo apt install ros-rolling-rmw-cyclonedds-cpp
```

Then export the env variable. You may want to add this to ~/.bashrc to set it automatically.

```
export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
```

**Comment by vatanaksoytezer** [comment]
@henningkayser should we pin this issue, so it is more visible?

**Comment by henningkayser** [comment]
> @henningkayser should we pin this issue, so it is more visible?

I've listed it in "Known Issues", isn't that enough for now?

**Comment by robinsonmm** [comment]
We are interested and monitoring this one, as RMW interoperability is of great interest. Thanks!

**Comment by JafarAbdi** [comment]
@henningkayser Should we close this? The issue was fixed in the latest release and all the issues related to this are closed
