### ISSUE TITLE
moveit_exceptions library not found

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#188]
### Description

When running:

 `colcon build --event-handlers desktop_notification- status- --cmake-args -DCMAKE_BUILD_TYPE=Release`

I get:

```
--- stderr: moveit_ros_occupancy_map_monitor
CMake Error at /home/andyz/ws_ros2/install/moveit_core/share/moveit_core/cmake/ament_cmake_export_libraries-extras.cmake:48 (message):
  Package 'moveit_core' exports the library 'moveit_exceptions' which
  couldn't be found
```

### Your environment
* ROS Distro: Eloquent, binary installation
* OS Version:  Ubuntu 18.04
* Building moveit2 from source (master branch)
* I've triple-checked that I'm sourcing install/setup.bash
* I ran:
`rosdep install --from-paths src --ignore-src --rosdistro eloquent -y --skip-keys "console_bridge fastcdr fastrtps libopensplice67 libopensplice69 rti-connext-dds-5.3.1 urdfdom_headers"`
* Also tried: 
`rosdep install -r --from-paths . --ignore-src --rosdistro eloquent -y`

**Comment by JafarAbdi** [comment]
This seems similar to this https://github.com/ros-planning/moveit2/issues/182, could you please check if the comments there helps .?

**Comment by AndyZe** [comment]
^ that did work. Previous usage of `--symlink-install` was my issue too. Thanks, and sorry for not finding it myself

**Comment by tylerjw** [comment]
I just ran into this... maybe we should add ament_cmake as a source dependency?

**Comment by JafarAbdi** [comment]
This should be fixed in the latest main branch
