### ISSUE TITLE
Servo: Returns to last sent position when unpaused

### ISSUE THREAD

**Issue by HX2003** [ros-planning/moveit2#1885]
If joint positions move by some other method when servo is paused or commands are stale, upon receiving new commands that are zero it returns to last sent position. Hence, there is a sudden movement; I don't think that is supposed to be the intended behaviour?
https://github.com/ros-planning/moveit2/blob/e2e0003c0e170a05747c699da05258382a338edf/moveit_ros/moveit_servo/src/servo_calcs.cpp#L452-L453

**Comment by AndyZe** [comment]
Thanks for tracking down one of the lines involved. I'll file a PR to fix this soon. Can you test it for me?

**Comment by henningkayser** [comment]
Is this issue related to https://github.com/ros-planning/moveit2/issues/1036?

**Comment by AndyZe** [comment]
I'm starting to look at this. Servo has these flags, `latest_twist_cmd_is_nonzero_` and `latest_joint_cmd_is_nonzero_`. The original thinking was, Servo should skip publishing commands if the user is requesting zero velocity. This was done to reduce spammy messages to ros_control.

I'm now thinking, those flags should just be dropped. No harm done if Servo publishes zero-velocity commands always.

**Comment by AndyZe** [comment]
@HX2003 can you please test #1904?

**Comment by HX2003** [comment]
@AndyZe I can confirm that the proposed fix works as intended. Additionally, can you expose the paused/unpaused status as a topic, I have multiple nodes that need to know whether servo is active.

**Comment by AndyZe** [comment]
Isn't there a topic for this already, something like `/servo_server/status`?

Thanks for testing it so quickly!

**Comment by HX2003** [comment]
There is a topic similar to it, but it does not reflect anything about pause status.
https://github.com/ros-planning/moveit2/blob/2fe4b30266fff91580234cbe0f05c6d1e1cefe8e/moveit_ros/moveit_servo/include/moveit_servo/status_codes.h

**Comment by AndyZe** [comment]
OK. Well, I probably won't have time to make that PR in the next couple weeks. If you can make, I'll review, though.

Feel free to open a new issue requesting the feature, too.

**Comment by HX2003** [comment]
Would it just involve publishing the paused status here as a separate topic? In that case I should be able to make a PR. And I should close this issue soon.
https://github.com/ros-planning/moveit2/blob/2fe4b30266fff91580234cbe0f05c6d1e1cefe8e/moveit_ros/moveit_servo/src/servo_calcs.cpp#L1232-L1235

**Comment by AndyZe** [comment]
I think it would be nice if you could add a Paused status code to this list -- https://github.com/ros-planning/moveit2/blob/2fe4b30266fff91580234cbe0f05c6d1e1cefe8e/moveit_ros/moveit_servo/include/moveit_servo/status_codes.h

And publish to the same topic, `servo_server/status`.

Basically, I don't see why a new topic is necessary ?

**Comment by HX2003** [comment]
Alright, I'll see what I can so.
