### ISSUE TITLE
franka moveit config crushes after the external activation device is pressed down

### ISSUE THREAD

**Issue by YuLiHN** [ros-planning/moveit2#1919]
### Description

While the terminal is running
`ros2 launch franka_moveit_config moveit.launch.py robot_ip:=my_robot_ip`
and I press external activation device which makes the display light turn from blue to white, the moveit node crushes because of the exception `what(): libfranka: Move command aborted: User Stop pressed!`. But in ros1 it is not the case. In ros1 the moveit node is still running after I bring the external activation device to the activated state (white light).

### Your environment
* ROS Distro: [Foxy]
* OS Version:Ubuntu 20.04
* Source build
* branch foxy

### Steps to reproduce
`ros2 launch franka_moveit_config moveit moveit.launch.py robot_ip:=ip`
and then press the activation external device.

### Expected behaviour

The moveit node should still running. After sending a errorrecover message the moveit node is supposed to be working again.

### Actual behaviour
The moveit node crushed `what(): libfranka: Move command aborted: User Stop pressed!`

### Backtrace or Console output
[console output](https://gist.github.com/YuLiHN/0754a9ff9099bb8ebffcc7beba68f3c1)

**Comment by JafarAbdi** [comment]
Seems to be a bug in the driver itself, I see you already opened an issue there.
