### ISSUE TITLE
Replace unhelpful cmake variable PROJECT_NAME with actual package name

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2#1920]
![image](https://user-images.githubusercontent.com/2490389/216648502-651610ed-33ca-4a81-82c5-fd30b2e22461.png)

`${PROJECT_NAME}` is a variable that is found in many of our cmake files. [here is one example](https://github.com/ros-planning/moveit2/blob/2105b91f89ea213a0fc3fc6b3735d296b5d57c3f/moveit_kinematics/CMakeLists.txt#L68). The project name in the linked to example is found at the top of the file `project(moveit_kinematics)`. It would make this file more readable if all instances of `${PROJECT_NAME}` was replaced with `moveit_kinematics`.

Tasks:
- [ ] Find `${PROJECT_NAME}` in cmake files
- [ ] Replace with the project name.
- [ ] Be Happy!

**Comment by rudra2112** [comment]
Hi, I am new to open source. I would like to work on this issue, can you assign me this issue, and help me a little more where should I start working from.

**Comment by tylerjw** [comment]
You can't do it. Let me know what questions you have.

**Comment by rudra2112** [comment]
I have fixed a lot of instances in PR[#1929](https://github.com/ros-planning/moveit2/pull/1929) can you check it and let me know, how can I improve.

**Comment by AdarshSingh-14** [comment]
Is the issue fixed? if not and no one is working on it I would like to help with this.

**Comment by henningkayser** [comment]
It looks like we now have two open PRs more or less applying the same fixes #1978, #1929
