### ISSUE TITLE
Specify LANGUAGE CXX in cmake where appropriate

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2#1923]
Specifying that a package is a C++ package to cmake is helpful in speeding up build times as it lets cmake know that it only needs to verify you have a working C++ compiler before building the package. If you don't specify this it checks for all sorts of other things your build probably doesn't need. [here is an example of how you specify that a package is a C++ package to CMake](https://github.com/ros-controls/ros2_control/blob/c8b843a9d4ec11bc1c0efe4d3339bca2b02fd586/controller_interface/CMakeLists.txt#L2)

Tasks:
- [ ] Find CMake packages in MoveIt that are C++ packages
- [ ] Add the config to the CMake
- [ ] Be happy!

I'm up for mentoring this issue, please ask any questions you have.

**Comment by sameergupta4873** [comment]
@tylerjw can I take this issue ?

**Comment by tylerjw** [comment]
Yes, please do. Let me know if you have any questions.

**Comment by tylerjw** [comment]
@sameergupta4873 fixed this issue, thank you!

**Comment by sameergupta4873** [comment]
> @sameergupta4873 fixed this issue, thank you!

It's my pleasure, contributing in here.
