### ISSUE TITLE
Investigate and document ways for using logging namespaces

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2#1926]
MoveIt is full of inconsistencies in how we use logging namespaces. Much of this is a hold-over from moveit being many different libraries that were joined into one library back in MoveIt 1 days. Here is an example of what I'm talking about:

https://github.com/ros-planning/moveit2/blob/3abf65d9d8d1cd39f9203059cb3b53b29fa57966/moveit_core/collision_detection_fcl/src/collision_env_fcl.cpp#L51

It would be really nice to refactor these logging namespaces to make them more useful, but before we can do that we need to investigate the ways we use logging namespaces.

Here is a link to a thread where we started discussing this:
https://github.com/ros-planning/moveit2/pull/1801#discussion_r1047152297

Tasks:
- [ ] Investigate and write notes on filtering logs based on namespaces (in ROS 1 there was a config file you could use to set the level per namespace, does that still work?)
- [ ] Investigate if the ROS project itself has standards for how these should be named
- [ ] Add a "How to use Logging to Debug Moveit" tutorial here: [moveit2_tutorials](moveit.picknik.ai) which lists the various ways logging can be configured
- [ ] Open a [discussion](https://github.com/ros-planning/moveit2/discussions) suggesting a standard for how we should name logging namespaces.
- [ ] Create `good first issue` issues for cleaning up our use of logging
 
I'd be happy to mentor this issue. This is a great one for someone who wants to get a deeper understanding of ROS logging and wants to improve the experience of debugging moveit.

**Comment by sameergupta4873** [comment]
Hey @tylerjw, I would like to work on this issue if it's suitable for me or anyone isn't working on it.
