### ISSUE TITLE
MoveIt Python Library: Replace Traditional For Loops with Range-based For Loops

### ISSUE THREAD

**Issue by peterdavidfagan** [ros-planning/moveit2#1930]
## Background

The MoveIt python binding code contains traditional for loops that are less readable than range-based for loops. This issue is used to track the removal of range-based for loops in the python library binding code.  

## Instructions
Replace traditional for loops with range-based for loops where possible. 

[example case](https://github.com/peterdavidfagan/moveit2/blob/2e406103c24f58003445a3693bdb79e136e1cbcc/moveit_py/src/moveit/moveit_py_utils/src/copy_ros_msg.cpp#L278)

### 🤔 What you will need to know.

For details on range-based for loops you can consult: https://en.cppreference.com/w/cpp/language/range-for.

**Comment by Sujeendra** [comment]
Hi, I have created a pull request for this issue. Can you please review and merge my changes?

**Comment by peterdavidfagan** [comment]
Awesome, thanks @Sujeendra I will review this over the weekend along with @JafarAbdi's pr.

**Comment by peterdavidfagan** [comment]
Thanks @Sujeendra I have cherry picked your changes and assigned you as the commit author on the pull request.

**Comment by peterdavidfagan** [comment]
Reopening due to build failure upon testing: https://github.com/peterdavidfagan/moveit2/pull/12

**Comment by Sujeendra** [comment]
Hi peter, Is there any documentation for building the code in local environment? this will help me build my code before check-in my changes.

**Comment by sshaizkhan** [comment]
@peterdavidfagan I have created a PR for the same and the code can build successfully through `moveit/moveit2:humble-ci-testing`  docker image. Please check the description for more info. Thanks

**Comment by peterdavidfagan** [comment]
Hi @Sujeendra,

Apologies for the delay in response. The following documentation outlines the process for performing a source build of MoveIt. Using docker as @sshaizkhan has is also a good choice for building MoveIt in an environment separate to the host environment. 

Thanks @sshaizkhan I will test this shortly also to confirm.

**Comment by peterdavidfagan** [comment]
Thanks @sshaizkhan for resolving this issue.

**Comment by peterdavidfagan** [comment]
> Hi peter, Is there any documentation for building the code in local environment? this will help me build my code before check-in my changes.

@Sujeendra happy to discuss further in case you wish to build locally and contribute to the project.

**Comment by sshaizkhan** [comment]
@peterdavidfagan I would love to contribute more given my background in robotics and a long history with MoveIt. Let me know. Thanks

**Comment by sshaizkhan** [comment]
Hi @peterdavidfagan 
sure you can start tagging me to new issues. Thanks

**Comment by Sujeendra** [comment]
HI @peterdavidfagan I was able to setup my local and build it. But, I have one question regarding running unit test cases. How to execute the test cases in local before releasing the code? I saw that there is a folder in moveit_py for running test cases but I get import error when I execute the python code. Can you please help me with this?

**Comment by peterdavidfagan** [comment]
> I saw that there is a folder in moveit_py for running test cases but I get import error when I execute the python code. Can you please help me with this?

Thanks for notifying me of this, there is a bug in the unittest code,  they are based on the old library.

**Comment by peterdavidfagan** [comment]
https://github.com/ros-planning/moveit2/pull/1979
