### ISSUE TITLE
Moveit2 Octomap not visualising 

### ISSUE THREAD

**Issue by HokulS** [ros-planning/moveit2#1940]
When I try to use Moveit2 to display octomaps I do not get any visual.  My initial point cloud has data, but the filtered point cloud has no data.

Humble Binary install
Ubuntu 22.04
Cyclone DDS

Im getting this message from octomap

Listening to '/kuka_lidar/points' using message filter with target frame 'world '

But nothing after that. 
sensors3d.yaml
`sensors:
  - default_sensor
default_sensor:
  filtered_cloud_topic: out_cloud
  max_range: 1000.0
  max_update_rate: 1.0
  padding_offset: 0.1
  padding_scale: 1.0
  point_cloud_topic: /kuka_lidar/points
  point_subsample: 1
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater '

Launch file
    octomap_config = load_yaml('solar_truck_moveit_config', 'config/sensors_3d.yaml')
    print(octomap_config);

    octomap_updater = {'octomap_frame': 'world',
                       'octomap_resolution': 0.05,
                       'max_range': 1000.0}

    move_group = Node(
        package="moveit_ros_move_group",
        executable="move_group",
        output="screen",
        parameters=[config_dict, octomap_updater, octomap_config],
        )

Full log after launching
ros2 launch solar_truck_moveit_config moveit_rviz.launch.py
[INFO] [launch]: All log files can be found below /home/hokul/.ros/log/2023-02-09-14-17-51-704888-hokul-XPS-15-9520-1392504
[INFO] [launch]: Default logging verbosity is set to INFO
Using load_yaml() directly is deprecated. Use xacro.load_yaml() instead.
Using load_yaml() directly is deprecated. Use xacro.load_yaml() instead.
{'sensors': ['default_sensor'], 'default_sensor': {'filtered_cloud_topic': 'out_cloud', 'max_range': 1000.0, 'max_update_rate': 1.0, 'padding_offset': 0.1, 'padding_scale': 1.0, 'point_cloud_topic': '/kuka_lidar/points', 'point_subsample': 1, 'sensor_plugin': 'occupancy_map_monitor/PointCloudOctomapUpdater'}}
[INFO] [ruby $(which ign) gazebo-1]: process started with pid [1392505]
[INFO] [static_transform_publisher-2]: process started with pid [1392508]
[INFO] [robot_state_publisher-3]: process started with pid [1392510]
[INFO] [parameter_bridge-4]: process started with pid [1392513]
[INFO] [create-5]: process started with pid [1392515]
[INFO] [move_group-6]: process started with pid [1392517]
[INFO] [static_transform_publisher-7]: process started with pid [1392519]
[INFO] [rviz2-8]: process started with pid [1392521]
[static_transform_publisher-7] [INFO] [1675916271.933802752] [static_transform_publisher0]: Spinning until stopped - publishing transform
[static_transform_publisher-7] translation: ('0.000000', '0.000000', '0.000000')
[static_transform_publisher-7] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
[static_transform_publisher-7] from 'world' to 'platform'
[static_transform_publisher-2] [INFO] [1675916271.935518806] [static_transform_publisher_GI955fYKrm61bQMD]: Spinning until stopped - publishing transform
[static_transform_publisher-2] translation: ('0.000000', '0.000000', '0.000000')
[static_transform_publisher-2] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
[static_transform_publisher-2] from 'kuka_lidar' to 'robot/kuka_rev_two/kuka_lidar'
[create-5] [INFO] [1675916271.937156423] [ros_gz_sim]: Requesting list of world names.
[robot_state_publisher-3] [INFO] [1675916271.959886015] [robot_state_publisher]: got segment kuka
[robot_state_publisher-3] [INFO] [1675916271.959957398] [robot_state_publisher]: got segment kuka_lidar
[robot_state_publisher-3] [INFO] [1675916271.959966069] [robot_state_publisher]: got segment kuka_rev_five
[robot_state_publisher-3] [INFO] [1675916271.959971455] [robot_state_publisher]: got segment kuka_rev_four
[robot_state_publisher-3] [INFO] [1675916271.959976577] [robot_state_publisher]: got segment kuka_rev_one
[robot_state_publisher-3] [INFO] [1675916271.959980364] [robot_state_publisher]: got segment kuka_rev_six
[robot_state_publisher-3] [INFO] [1675916271.959983159] [robot_state_publisher]: got segment kuka_rev_three
[robot_state_publisher-3] [INFO] [1675916271.959985947] [robot_state_publisher]: got segment kuka_rev_two
[robot_state_publisher-3] [INFO] [1675916271.959988896] [robot_state_publisher]: got segment pile
[robot_state_publisher-3] [INFO] [1675916271.959991922] [robot_state_publisher]: got segment platform
[robot_state_publisher-3] [INFO] [1675916271.959994689] [robot_state_publisher]: got segment world
[move_group-6] [INFO] [1675916271.964919188] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0 seconds
[move_group-6] [INFO] [1675916271.964959593] [moveit_robot_model.robot_model]: Loading robot model 'robot'...
[move_group-6] [WARN] [1675916271.965004418] [moveit_robot_model.robot_model]: Link kuka_lidar has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.
[move_group-6] [ERROR] [1675916271.966875816] [moveit_kinematics_base.kinematics_base]: Group 'kuka' is not a chain
[move_group-6] [ERROR] [1675916271.966885302] [kinematics_plugin_loader]: Kinematics solver of type 'kdl_kinematics_plugin/KDLKinematicsPlugin' could not be initialized for group 'kuka'
[move_group-6] [ERROR] [1675916271.966893530] [moveit_ros.robot_model_loader]: Kinematics solver could not be instantiated for joint group kuka.
[move_group-6] [INFO] [1675916271.973043398] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-6] [INFO] [1675916271.973118252] [moveit.ros_planning_interface.moveit_cpp]: Listening to 'joint_states' for joint states
[move_group-6] [INFO] [1675916271.973284299] [moveit_ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
[move_group-6] [INFO] [1675916271.973490239] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/attached_collision_object' for attached collision objects
[move_group-6] [INFO] [1675916271.973497387] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[move_group-6] [INFO] [1675916271.973893302] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/planning_scene'
[move_group-6] [INFO] [1675916271.973900065] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[move_group-6] [INFO] [1675916271.974047615] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'collision_object'
[move_group-6] [INFO] [1675916271.974183650] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'planning_scene_world' for planning scene world geometry
[move_group-6] [INFO] [1675916271.976900744] [moveit.ros.perception.pointcloud_octomap_updater]: Listening to '/kuka_lidar/points' using message filter with target frame 'world '
[move_group-6] [INFO] [1675916271.976914965] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'ompl'
[move_group-6] [INFO] [1675916271.983344107] [moveit.ros_planning.planning_pipeline]: Using planning interface 'OMPL'
[move_group-6] [INFO] [1675916271.984854887] [moveit_ros.add_time_optimal_parameterization]: Param 'ompl.path_tolerance' was not set. Using default value: 0.100000
[move_group-6] [INFO] [1675916271.984863517] [moveit_ros.add_time_optimal_parameterization]: Param 'ompl.resample_dt' was not set. Using default value: 0.100000
[move_group-6] [INFO] [1675916271.984866059] [moveit_ros.add_time_optimal_parameterization]: Param 'ompl.min_angle_change' was not set. Using default value: 0.001000
[move_group-6] [INFO] [1675916271.984877900] [moveit_ros.fix_workspace_bounds]: Param 'ompl.default_workspace_bounds' was not set. Using default value: 10.000000
[move_group-6] [INFO] [1675916271.984886545] [moveit_ros.fix_start_state_bounds]: Param 'ompl.start_state_max_bounds_error' was set to 0.100000
[move_group-6] [INFO] [1675916271.984889620] [moveit_ros.fix_start_state_bounds]: Param 'ompl.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-6] [INFO] [1675916271.984895651] [moveit_ros.fix_start_state_collision]: Param 'ompl.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-6] [INFO] [1675916271.984898605] [moveit_ros.fix_start_state_collision]: Param 'ompl.jiggle_fraction' was not set. Using default value: 0.020000
[move_group-6] [INFO] [1675916271.984901301] [moveit_ros.fix_start_state_collision]: Param 'ompl.max_sampling_attempts' was not set. Using default value: 100
[move_group-6] [INFO] [1675916271.984907366] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Add Time Optimal Parameterization'
[move_group-6] [INFO] [1675916271.984909279] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Resolve constraint frames to robot links'
[move_group-6] [INFO] [1675916271.984910956] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
[move_group-6] [INFO] [1675916271.984928274] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
[move_group-6] [INFO] [1675916271.984929902] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
[move_group-6] [INFO] [1675916271.984931441] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
[move_group-6] [INFO] [1675916271.985613407] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'chomp'
[move_group-6] [INFO] [1675916271.987408595] [moveit.ros_planning.planning_pipeline]: Using planning interface 'CHOMP'
[move_group-6] [INFO] [1675916271.988338463] [moveit_ros.fix_workspace_bounds]: Param 'chomp.default_workspace_bounds' was not set. Using default value: 10.000000
[move_group-6] [INFO] [1675916271.988349301] [moveit_ros.fix_start_state_bounds]: Param 'chomp.start_state_max_bounds_error' was set to 0.100000
[move_group-6] [INFO] [1675916271.988351842] [moveit_ros.fix_start_state_bounds]: Param 'chomp.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-6] [INFO] [1675916271.988357703] [moveit_ros.fix_start_state_collision]: Param 'chomp.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-6] [INFO] [1675916271.988360720] [moveit_ros.fix_start_state_collision]: Param 'chomp.jiggle_fraction' was set to 0.050000
[move_group-6] [INFO] [1675916271.988363557] [moveit_ros.fix_start_state_collision]: Param 'chomp.max_sampling_attempts' was not set. Using default value: 100
[move_group-6] [INFO] [1675916271.988369870] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Add Time Parameterization'
[move_group-6] [INFO] [1675916271.988371578] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Resolve constraint frames to robot links'
[move_group-6] [INFO] [1675916271.988373011] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
[move_group-6] [INFO] [1675916271.988374428] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
[move_group-6] [INFO] [1675916271.988375723] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
[move_group-6] [INFO] [1675916271.988377023] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
[move_group-6] [INFO] [1675916271.988809605] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'pilz_industrial_motion_planner'
[move_group-6] [INFO] [1675916271.990177413] [moveit.pilz_industrial_motion_planner.joint_limits_aggregator]: Reading limits from namespace robot_description_planning
[move_group-6] [INFO] [1675916271.991704617] [moveit.pilz_industrial_motion_planner]: Available plugins: pilz_industrial_motion_planner/PlanningContextLoaderCIRC pilz_industrial_motion_planner/PlanningContextLoaderLIN pilz_industrial_motion_planner/PlanningContextLoaderPTP 
[move_group-6] [INFO] [1675916271.991711643] [moveit.pilz_industrial_motion_planner]: About to load: pilz_industrial_motion_planner/PlanningContextLoaderCIRC
[move_group-6] [INFO] [1675916271.992283876] [moveit.pilz_industrial_motion_planner]: Registered Algorithm [CIRC]
[move_group-6] [INFO] [1675916271.992289833] [moveit.pilz_industrial_motion_planner]: About to load: pilz_industrial_motion_planner/PlanningContextLoaderLIN
[move_group-6] [INFO] [1675916271.992680103] [moveit.pilz_industrial_motion_planner]: Registered Algorithm [LIN]
[move_group-6] [INFO] [1675916271.992684281] [moveit.pilz_industrial_motion_planner]: About to load: pilz_industrial_motion_planner/PlanningContextLoaderPTP
[move_group-6] [INFO] [1675916271.993074976] [moveit.pilz_industrial_motion_planner]: Registered Algorithm [PTP]
[move_group-6] [INFO] [1675916271.993079267] [moveit.ros_planning.planning_pipeline]: Using planning interface 'Pilz Industrial Motion Planner'
[move_group-6] [INFO] [1675916272.004912494] [moveit.plugins.moveit_simple_controller_manager]: Added FollowJointTrajectory controller for kuka_controller
[move_group-6] [INFO] [1675916272.004992514] [moveit.plugins.moveit_simple_controller_manager]: Returned 1 controllers in list
[move_group-6] [INFO] [1675916272.005005711] [moveit.plugins.moveit_simple_controller_manager]: Returned 1 controllers in list
[move_group-6] [INFO] [1675916272.005147260] [moveit_ros.trajectory_execution_manager]: Trajectory execution is managing controllers
[move_group-6] [INFO] [1675916272.005172425] [move_group.move_group]: MoveGroup debug mode is ON
[move_group-6] [INFO] [1675916272.013488695] [move_group.move_group]: 
[move_group-6] 
[move_group-6] ********************************************************
[move_group-6] * MoveGroup using: 
[move_group-6] *     - ApplyPlanningSceneService
[move_group-6] *     - ClearOctomapService
[move_group-6] *     - CartesianPathService
[move_group-6] *     - ExecuteTrajectoryAction
[move_group-6] *     - GetPlanningSceneService
[move_group-6] *     - KinematicsService
[move_group-6] *     - MoveAction
[move_group-6] *     - MotionPlanService
[move_group-6] *     - QueryPlannersService
[move_group-6] *     - StateValidationService
[move_group-6] ********************************************************
[move_group-6] 
[move_group-6] [INFO] [1675916272.013513623] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[move_group-6] [INFO] [1675916272.013519692] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context initialization complete
[move_group-6] Loading 'move_group/ApplyPlanningSceneService'...
[move_group-6] Loading 'move_group/ClearOctomapService'...
[move_group-6] Loading 'move_group/MoveGroupCartesianPathService'...
[move_group-6] Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
[move_group-6] Loading 'move_group/MoveGroupGetPlanningSceneService'...
[move_group-6] Loading 'move_group/MoveGroupKinematicsService'...
[move_group-6] Loading 'move_group/MoveGroupMoveAction'...
[move_group-6] Loading 'move_group/MoveGroupPlanService'...
[move_group-6] Loading 'move_group/MoveGroupQueryPlannersService'...
[move_group-6] Loading 'move_group/MoveGroupStateValidationService'...
[move_group-6] 
[move_group-6] You can start planning now!
[move_group-6] 
[rviz2-8] [INFO] [1675916272.094499751] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-8] [INFO] [1675916272.094591676] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-8] [INFO] [1675916272.105356596] [rviz2]: Stereo is NOT SUPPORTED
[create-5] [INFO] [1675916272.356996592] [ros_gz_sim]: Waiting messages on topic [/robot_description].
[create-5] [INFO] [1675916272.456623188] [ros_gz_sim]: Requested creation of entity.
[create-5] [INFO] [1675916272.456664313] [ros_gz_sim]: OK creation of entity.
[INFO] [create-5]: process has finished cleanly [pid 1392515]
[INFO] [ros2-9]: process started with pid [1392737]
[parameter_bridge-4] [INFO] [1675916272.961825925] [ros_gz_bridge]: Creating GZ->ROS Bridge: [kuka_lidar/points (ignition.msgs.PointCloudPacked) -> kuka_lidar/points (sensor_msgs/msg/PointCloud2)] (Lazy 0)
[parameter_bridge-4] [INFO] [1675916272.964133328] [ros_gz_bridge]: Creating ROS->GZ Bridge: [kuka_lidar/points (sensor_msgs/msg/PointCloud2) -> kuka_lidar/points (ignition.msgs.PointCloudPacked)] (Lazy 0)
[parameter_bridge-4] [INFO] [1675916272.965457822] [ros_gz_bridge]: Creating GZ->ROS Bridge: [clock (ignition.msg.Clock) -> clock (rosgraph_msgs/msg/Clock)] (Lazy 0)
[parameter_bridge-4] [WARN] [1675916272.965528028] [ros_gz_bridge]: Failed to create a bridge for topic [clock] with ROS2 type [clock] to topic [rosgraph_msgs/msg/Clock] with Gazebo Transport type [ignition.msg.Clock]
[ruby $(which ign) gazebo-1] [INFO] [1675916273.110275614] [ignition_ros_control]: [ign_ros2_control] Fixed joint [pile_joint] (Entity=39)] is skipped
[ruby $(which ign) gazebo-1] [INFO] [1675916273.110389580] [ignition_ros_control]: [ign_ros2_control] Fixed joint [platform_joint] (Entity=40)] is skipped
[ruby $(which ign) gazebo-1] [INFO] [1675916273.217206427] [ignition_ros_control]: connected to service!! robot_state_publisher asking for robot_description
[ruby $(which ign) gazebo-1] [INFO] [1675916273.218081020] [ignition_ros_control]: Received URDF from param server
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222268519] [ignition_ros_control]: Loading joint: kuka_joint_one
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222305717] [ignition_ros_control]: 	State:
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222315018] [ignition_ros_control]: 		 position
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222354614] [ignition_ros_control]: 			 found initial value: 0.000000
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222361923] [ignition_ros_control]: 		 velocity
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222378539] [ignition_ros_control]: 	Command:
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222382276] [ignition_ros_control]: 		 position
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222416764] [ignition_ros_control]: Loading joint: kuka_joint_two
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222420885] [ignition_ros_control]: 	State:
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222424198] [ignition_ros_control]: 		 position
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222427727] [ignition_ros_control]: 			 found initial value: 0.000000
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222431448] [ignition_ros_control]: 		 velocity
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222434705] [ignition_ros_control]: 	Command:
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222437760] [ignition_ros_control]: 		 position
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222454338] [ignition_ros_control]: Loading joint: kuka_joint_three
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222457813] [ignition_ros_control]: 	State:
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222461236] [ignition_ros_control]: 		 position
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222464514] [ignition_ros_control]: 			 found initial value: 0.000000
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222468093] [ignition_ros_control]: 		 velocity
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222471235] [ignition_ros_control]: 	Command:
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222474386] [ignition_ros_control]: 		 position
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222480287] [ignition_ros_control]: Loading joint: kuka_joint_four
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222483624] [ignition_ros_control]: 	State:
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222486624] [ignition_ros_control]: 		 position
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222489421] [ignition_ros_control]: 			 found initial value: 0.000000
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222492792] [ignition_ros_control]: 		 velocity
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222495888] [ignition_ros_control]: 	Command:
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222498815] [ignition_ros_control]: 		 position
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222503744] [ignition_ros_control]: Loading joint: kuka_joint_five
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222507425] [ignition_ros_control]: 	State:
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222510422] [ignition_ros_control]: 		 position
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222514235] [ignition_ros_control]: 			 found initial value: 0.000000
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222517768] [ignition_ros_control]: 		 velocity
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222520793] [ignition_ros_control]: 	Command:
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222523712] [ignition_ros_control]: 		 position
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222528987] [ignition_ros_control]: Loading joint: kuka_joint_six
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222532260] [ignition_ros_control]: 	State:
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222535170] [ignition_ros_control]: 		 position
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222537882] [ignition_ros_control]: 			 found initial value: 0.000000
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222541225] [ignition_ros_control]: 		 velocity
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222544366] [ignition_ros_control]: 	Command:
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222547283] [ignition_ros_control]: 		 position
[ruby $(which ign) gazebo-1] [INFO] [1675916273.222913513] [resource_manager]: Initialize hardware 'IgnitionSystem' 
[ruby $(which ign) gazebo-1] [WARN] [1675916273.222919648] [ignition_ros_control]: On init...
[ruby $(which ign) gazebo-1] [INFO] [1675916273.223047491] [resource_manager]: Successful initialization of hardware 'IgnitionSystem'
[ruby $(which ign) gazebo-1] [INFO] [1675916273.223085149] [resource_manager]: 'configure' hardware 'IgnitionSystem' 
[ruby $(which ign) gazebo-1] [INFO] [1675916273.223087303] [ignition_ros_control]: System Successfully configured!
[ruby $(which ign) gazebo-1] [INFO] [1675916273.223091976] [resource_manager]: Successful 'configure' of hardware 'IgnitionSystem'
[ruby $(which ign) gazebo-1] [INFO] [1675916273.223095575] [resource_manager]: 'activate' hardware 'IgnitionSystem' 
[ruby $(which ign) gazebo-1] [INFO] [1675916273.223097491] [resource_manager]: Successful 'activate' of hardware 'IgnitionSystem'
[ruby $(which ign) gazebo-1] [INFO] [1675916273.223118865] [ignition_ros_control]: Loading controller_manager
[ruby $(which ign) gazebo-1] [INFO] [1675916273.422407008] [controller_manager]: Loading controller 'joint_state_broadcaster'
[ruby $(which ign) gazebo-1] [INFO] [1675916273.426183891] [controller_manager]: Setting use_sim_time=True for joint_state_broadcaster to match controller manager (see ros2_control#325 for details)
[ruby $(which ign) gazebo-1] libEGL warning: egl: failed to create dri2 screen
[ruby $(which ign) gazebo-1] libEGL warning: egl: failed to create dri2 screen
[ruby $(which ign) gazebo-1] ../src/intel/isl/isl.c:2216: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
[ruby $(which ign) gazebo-1] libEGL warning: egl: failed to create dri2 screen
[ruby $(which ign) gazebo-1] libEGL warning: egl: failed to create dri2 screen
[ruby $(which ign) gazebo-1] ../src/intel/isl/isl.c:2216: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
[ruby $(which ign) gazebo-1] [INFO] [1675916274.211598353] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[ruby $(which ign) gazebo-1] [INFO] [1675916274.211688075] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[ros2-9] Sucessfully loaded controller joint_state_broadcaster into state active
[INFO] [ros2-9]: process has finished cleanly [pid 1392737]
[INFO] [ros2-10]: process started with pid [1393267]
[ruby $(which ign) gazebo-1] [INFO] [1675916275.567990275] [controller_manager]: Loading controller 'kuka_controller'
[ruby $(which ign) gazebo-1] [INFO] [1675916275.573980845] [joint_trajectory_controller.interpolation_methods]: No interpolation method parameter was given. Using the default, VARIABLE_DEGREE_SPLINE.
[ruby $(which ign) gazebo-1] [INFO] [1675916275.574006095] [controller_manager]: Setting use_sim_time=True for kuka_controller to match controller manager (see ros2_control#325 for details)
[ruby $(which ign) gazebo-1] [INFO] [1675916275.589693238] [controller_manager]: Configuring controller 'kuka_controller'
[ruby $(which ign) gazebo-1] [INFO] [1675916275.589819237] [kuka_controller]: No specific joint names are used for command interfaces. Using 'joints' parameter.
[ruby $(which ign) gazebo-1] [INFO] [1675916275.589870767] [kuka_controller]: Command interfaces are [position] and state interfaces are [position velocity].
[ruby $(which ign) gazebo-1] [INFO] [1675916275.589890896] [joint_trajectory_controller.interpolation_methods]: No interpolation method parameter was given. Using the default, VARIABLE_DEGREE_SPLINE.
[ruby $(which ign) gazebo-1] [INFO] [1675916275.589894073] [kuka_controller]: Using 'splines' interpolation method.
[ruby $(which ign) gazebo-1] [INFO] [1675916275.590484235] [kuka_controller]: Controller state will be published at 50.00 Hz.
[ruby $(which ign) gazebo-1] [INFO] [1675916275.590898860] [kuka_controller]: Action status changes will be monitored at 20.00 Hz.
[ros2-10] Sucessfully loaded controller kuka_controller into state active
[INFO] [ros2-10]: process has finished cleanly [pid 1393267]
[move_group-6] [INFO] [1675916285.122537810] [move_group]: Message Filter dropping message: frame 'robot/kuka_rev_two/kuka_lidar' at time 0.004 for reason 'the timestamp on the message is earlier than all the data in the transform cache

**Comment by JaouadROS** [comment]
Did you solve the bug?
I have the same issue with gazebo on ubuntu 22.04.

**Comment by HokulS** [comment]
> Did you solve the bug? I have the same issue with gazebo on ubuntu 22.04.

No I wasn't able to unfortunately

**Comment by JaouadROS** [comment]
I solved mine, it was a problem related to CPU/GPU usage. Check [this](https://github.com/gazebosim/docs/blob/master/fortress/troubleshooting.md#problems-with-dual-intel-and-nvidia-gpu-systems), it might help you.

**Comment by tejasps28** [comment]
Hi everyone, has anyone been able to find a solution for this?
