### ISSUE TITLE
TrajectoryExecutionManager::known_controllers_ needs to be protected from concurrent read/write access

### ISSUE THREAD

**Issue by schornakj** [ros-planning/moveit2#1943]
### Description

Many `TrajectoryExecutionManager` functions directly access `known_controllers_`. It's possible to have one ROS callback trigger controller rediscovery while other independent callbacks are using `known_controllers_`, which can cause trajectory execution failures when the map of controllers is unexpectedly cleared.

We need to add a mutex lock or similar mechanism to prevent this type of issue.

**Comment by AndyZe** [comment]
You already know my opinion here, but I think we should just do away with the automatic controller selection. It's not needed by `moveit_cpp` anymore; the user can specify the controller they want directly.  (#1838) We could do the same thing for move_group by putting the controller name in the action request field.
