### ISSUE TITLE
pick() and place() functions in moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp commented

### ISSUE THREAD

**Issue by atuldivekar** [ros-planning/moveit2#1951]
### Description

pick() and place() functions in moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp 
are commented which causes code to fail.

There is no documentation to indicate this is deprecated and tutorials such as 
  https://github.com/ros-planning/moveit2_tutorials/blob/main/doc/examples/pick_place/src/pick_place_tutorial.cpp
still use these functions

* ROS Distro: Humble
* OS Version: Ubuntu 22.04
* Binary build for ROS2 Humble , source build for MoveIt2 Humble branch
Cyclone DDS

### Steps to reproduce

I tried to create a simple pick and place demo.

The relevant lines are : 
 
#include <moveit/planning_scene_interface/planning_scene_interface.h>
#include <moveit/move_group_interface/move_group_interface.h>

...

move_group_interface_ptr_     = new MoveGroupInterface(node_,"panda_arm");
move_group_interface_ptr_->pick("object", grasps);   

Compiler error:
>>  error: ‘class moveit::planning_interface::MoveGroupInterface’ has no member named ‘pick’

The code for pick() etc. appears to be commented in 
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

If this is deprecated, this should be documented and the tutorials updated.
If deprecated, what is the alternative to use? MoveIt Task Constructor?

**Comment by DaniGarciaLopez** [comment]
I am also interested to know why these functions are commented out. If they are deprecated in Humble I would like to find a simple alternative to pick up objects from the planning scene without the use of Moveit Task Constructor. Thanks!

**Comment by henningkayser** [comment]
@atuldivekar the tutorial states that it is deprecated and, the pick place capability has been removed a while ago (https://github.com/ros-planning/moveit2/pull/1177). However, you are right that commented code in the main repo is not great. Would you mind filing a PR to remove it along with the tutorial?

And yes, MoveIt Task Constructor is really the best solution for pick and place tasks.https://moveit.picknik.ai/humble/doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.html

**Comment by antonio1matos** [comment]
@DaniGarciaLopez  did you found a way to pick up objects from the planning scene avoiding the use of Moveit Task Constructor?

**Comment by DaniGarciaLopez** [comment]
@antonio1matos We decided to use MoveIt Task Constructor. It has many introspection tools and it's worth a try for simple pick/place tasks as well.
