### ISSUE TITLE
MoveIt Python Library: Handling uninitialised joints

### ISSUE THREAD

**Issue by peterdavidfagan** [ros-planning/moveit2#1972]
### Description

When binding the ``moveit_cpp`` library it was noted that a segmentation fault arises after attempting to plan when certain joints in the RobotState are uninitialised. To prevent this issue we set all joints to default values in the setStartState method of the planning component ([see here](https://github.com/ros-planning/moveit2/pull/1546#discussion_r1114191170)). This is an imperfect solution, the purpose of this item is to address this issue. See the following [issue](https://github.com/ros-planning/moveit/pull/3008) for related discussion.

**Comment by henningkayser** [comment]
I don't think this is a bug. If we are not happy with the default-default values, the alternatives are A) always waiting for the complete robot state using the CSM or B) requiring the user to pass initial values for each instance. While those might be very useful, I don't think that they would be a requirement.
