### ISSUE TITLE
Cartesian Planning with TCP Velocity 

### ISSUE THREAD

**Issue by ClaBirk** [ros-planning/moveit2#1993]
# 6DOF Planner for cartesian movement with speed constrain (m/s) and orientation constrain (TCP)
looking for a Motion planner wich is able to control the **linear movement** of 6DOF Robot with a given speed in m/s. And detection if the set speed exceeds the joint limits. 
I couldnt find this feature or a demo for linear movement with variable speed.

Is Pilz_Industrial_Motion Planner already integrated in Moveit2 Humble?
Hence i need the TCP Velocity feature should i move to rosindustrial ?

**Comment by henningkayser** [comment]
@ClaBirk the PILZ industrial planner is available. Please take a look at the tutorials, cartesian limits are documented here https://moveit.picknik.ai/humble/doc/examples/pilz_industrial_motion_planner/pilz_industrial_motion_planner.html#cartesian-limits

**Comment by tylerjw** [comment]
Please re-open this issue if the above link doesn't answer your questions.
