### ISSUE TITLE
For convenience, add a vector version of `RobotState::getVariableVelocities()`

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#2018]
It would be convenient to add a std::vector-ized version of this:

```
  const double* getVariableVelocities() const
  {
    return velocity_;
  }
```

**Comment by henningkayser** [comment]
There is already https://moveit.picknik.ai/humble/api/html/classmoveit_1_1core_1_1RobotState.html#a3c2938fb8c9467dff253db4b5c1992ca. But if you think the copy functions are missing for the all-variable getters, I'd say it would be consistent to add them

**Comment by ibrahiminfinite** [comment]
Hi,

While going through [robot_state.h](https://github.com/ros-planning/moveit2/blob/main/moveit_core/robot_state/include/moveit/robot_state/robot_state.h) .
 I noticed that it contains a good number of definitions.
At first I though this was mostly for `const` return functions. but then realized that was not the case.

Is there a reason why some functions like `setVariableAccelerations()` has one of the overloads defined in the `robot_state.h` while the other overloads are in the `robot_state.cpp` ?

**Comment by Tejal-19** [comment]
Hey, I have tried doing the same and created a PR #2023. Please let me know if anything else is required.

**Comment by AndyZe** [comment]
@ibrahiminfinite that's a good point! I think you should open another issue about that and file a PR about it if you have time. I'd call it something like "Consistent function definitions in RobotState"

As a rule of thumb for robot_state.h, perhaps we can say:

- If a function definition is 2 lines or less, put it in `robot_state.h`
- If a function definition is >2 lines, put it in `robot_state.cpp`

I'm curious what @henningkayser and @tylerjw think about this rule of thumb

**Comment by ibrahiminfinite** [comment]
I am not a fan of definitions in the header,  unless it is a single line return.
But if the rule of thumb you stated is the way things are done within moveit ,  we can go with that.

**Comment by Tejal-19** [comment]
@AndyZe do you want me to make any changes to the PR ?

**Comment by AndyZe** [comment]
@Tejal-19 let's wait for the response to this comment:  https://github.com/ros-planning/moveit2/pull/2023#issuecomment-1475089319

**Comment by ibrahiminfinite** [comment]
I also think it would be nice to have a  method  that returns a vector rather than copy it into one.
Especially useful in places where we don't  just need use the result without storing.

We can close this if such a method won't be of much use.
