### ISSUE TITLE
Infinite loop in TOTG if zero max acceleration is specified

### ISSUE THREAD

**Issue by sea-bass** [ros-planning/moveit2#2066]
### Description

If you pass in a zero max acceleration limit to TOTG, you will actually get stuck in an [infinite loop](https://github.com/ros-planning/moveit2/blob/main/moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp#L520) because of the [`integrateForward()`](https://github.com/ros-planning/moveit2/blob/main/moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp#L512) function.

While zero acceleration limit is physically meaningless since it means the joints won't be able to move, we should at least have an error/warning. Whether we actually throw an exception or just return a no-op trajectory is up to the implementer.

### Your environment
* ROS Distro: Rolling
* OS Version: Ubuntu 22.04

**Comment by AndyZe** [comment]
Quick comment: you might as well check for 0 vel and 0 jerk limits, too
