### ISSUE TITLE
Use zero-phase filtering in Servo

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#2076]
We should be able to filter forward, then backward to nearly eliminate phase shift. It would be the equivalent of MATLAB `filtfilt`

**Comment by Shobuj-Paul** [comment]
> We should be able to filter forward, then backward to nearly eliminate phase shift. It would be the equivalent of MATLAB `filtfilt`

Could you point me towards this code?

**Comment by AndyZe** [comment]
Sure. Here's a decent writeup on the concept:

https://community.sw.siemens.com/s/article/butterworth-filter-regular-and-zero-phase

And here's the code:

https://github.com/ros-planning/moveit2/blob/548f5fe3e2f3f83b6de97a7a0abba23ffbca0438/moveit_core/online_signal_smoothing/src/butterworth_filter.cpp#L50

Although reading up on it now, the zero-phase filtering technique only applies to _offline_ filtering. Not online filtering like MoveIt Servo requires. So I guess this issue does not make any sense. Closing it. Sorry @Shobuj-Paul !
