### ISSUE TITLE
Use of `make_shared_from_pool` in MoveIt Servo

### ISSUE THREAD

**Issue by ibrahiminfinite** [ros-planning/moveit2#2100]
There is a `make_shared_from_pool.h` header in MoveIt Servo package,  the intended use appears to be efficient creation of message objects that are published from within servo, however , while it is included in most of the other files, presently it is only used in `pose_tracking.cpp`.

Having the required message type as a member variable and reusing it might be a good alternative.
Unless there is a reason not to go that way.

**Comment by ibrahiminfinite** [comment]
@AndyZe 
This is still left.
Currently used in `pose_tracking.cpp` , [here](https://github.com/ros-planning/moveit2/blob/dc7643502adbeaa41dfd370605460cfd45f26b7f/moveit_ros/moveit_servo/src/pose_tracking.cpp#L279) and [here](https://github.com/ros-planning/moveit2/blob/dc7643502adbeaa41dfd370605460cfd45f26b7f/moveit_ros/moveit_servo/src/pose_tracking.cpp#L330).

Should this be applied  to other parts or do we want to remove this utility from the codebase ?

**Comment by AndyZe** [comment]
let's ask @tylerjw

**Comment by ibrahiminfinite** [comment]
Closing this since it is taken care of in the new refactor.
And doesn't need to be addressed in the current version.
