### ISSUE TITLE
controller_manager_plugin

### ISSUE THREAD

**Issue by liuminL** [ros-planning/moveit2#2105]
### Description
See
https://github.com/ros-planning/moveit2/blob/ac104953348ece6c0e134cc85447a0cc2e7df32c/moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp#L426
I think this should be :
`claimed_resources.left.erase(c->second.name);`  
because there is no name in the right view，
Perhaps I didn't fully understand why use right view

**Comment by JafarAbdi** [comment]
Thanks @liuminL for the issue, please take a look at https://github.com/ros-planning/moveit2/pull/2116 for a proposed fix
