### ISSUE TITLE
Wrong equations used in Servo twist transformations

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#2150]
It was pointed out to me that Servo uses the wrong equations to transform twist. Servo does this:

`w' = R * w` and `v' = R * v`

Probably equation 3.83 or 3.84 from here should be used instead:

http://hades.mech.northwestern.edu/images/7/7f/MR.pdf

Whether it's Eq. 3.83 or 3.84 depends on whether the frame is fixed or attached to a robot link.

This is only an issue for large angular velocities.

**Comment by abhijelly** [comment]
@AndyZe where is this twist transform occurring in Servo class? I cannot seem to find those transforms in `moveit_servo::Servo` or `moveit_servo:::ServoCalcs`?

**Comment by AndyZe** [comment]
Hi @abhijelly,

@ibrahiminfinite is tackling this issue.
