### ISSUE TITLE
Should 'moveit_setup_assistant' exec_depend on 'moveit_configs_utils'?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-planning/moveit2#2182]
### Description

`apt install`-ing just `ros-humble-moveit-setup-assistant` and trying to `ros2 launch moveit_setup_assistant setup_assistant.launch.py` results in:

```
[INFO] [launch]: All log files can be found below /.../.ros/log/2023-05-17-11-37-59-890354-ecb941c48331-4395
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught exception when trying to load file of format [py]: No module named 'moveit_configs_utils'
```

I tried checking whether `moveit_configs_utils` is an `exec_depend` of one of the packages under `moveit_setup_assistant`.

On `main` it is, but only as a `test_depend` (`moveit_setup_controllers`).

On `humble` it doesn't seem to be mentioned at all in any manifest.

Is an `exec_depend` missing?

### Your environment
* ROS Distro: Humble
* OS Version: Ubuntu 22.04
* binaries, `apt`, `2.5.4`
* Which RMW: irrelevant, as this is the MSA not starting

**Comment by gavanderhoorn** [comment]
seems it is a `depend` of `moveit_setup_app_plugins` on `main`, so perhaps this is just a `humble` issue?

**Comment by gavanderhoorn** [comment]
Then again, `moveit_setup_assistant` directly depends on `moveit_configs_utils` (`main` and `humble`):

https://github.com/ros-planning/moveit2/blob/cc1ef618d9c02728bfc58723f15b29ed1efc6aa2/moveit_setup_assistant/moveit_setup_assistant/launch/setup_assistant.launch.py#L2-L5

so it should state its own dependencies.

**Comment by henningkayser** [comment]
This looks like an `exec_depend` to me. Then, however, I'm not convinced that `add_debuggable_node` and `DeclareBooleanLaunchArg` are worth the dependency, if no config features are actually being used.

So.. https://github.com/ros-planning/moveit2/pull/1962 has been merged into main, but wasn't backported. I'll fix that.
