### ISSUE TITLE
Use rclcpp::SystemDefaultsQoS() instead of magic numbers (or document magic numbers)

### ISSUE THREAD

**Issue by sjahr** [ros-planning/moveit2#2225]
In many places throughout the codebase, we're still using magic numbers to configure QoS for publishers and subscribers for example:
[here](https://github.com/ros-planning/moveit2/blob/55df0bccd5e884649780b4ceeee80891e563b57b/moveit_ros/planning/planning_scene_monitor/src/current_state_monitor_middleware_handle.cpp#L77), [here](https://github.com/ros-planning/moveit2/blob/55df0bccd5e884649780b4ceeee80891e563b57b/moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp#L1130) or [here](https://github.com/ros-planning/moveit2/blob/55df0bccd5e884649780b4ceeee80891e563b57b/moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp#L186).

I think we should replace this in all cases with rclcpp::SystemDefaultsQoS() for consistency and maybe more stability. @henningkayser + @tylerjw What do you think?

**Comment by SANTHOSH-MAMIDISETTI** [comment]
@henningkayser  @sjahr  I would love to work on it , Can I be assigned it ?

**Comment by sjahr** [comment]
You can just start working on it :smile: Once you've opened a PR we can link it to this issue

**Comment by Shobuj-Paul** [comment]
Hi @sjahr 
Could you check the draft PR if this was what you were looking for? If this is correct I shall look for more instances and make the changes.
