### ISSUE TITLE
Parameter jump_threshold of computeCartesianPath isn't documented

### ISSUE THREAD

**Issue by andrey-pr** [ros-planning/moveit2#2233]
There is function computeCartesianPath of MoveGroup, [it documented in doxygen](http://docs.ros.org/en/jade/api/moveit_ros_planning_interface/html/classmoveit_1_1planning__interface_1_1MoveGroup.html#ad6b02d15000d5b17c89b15a0f744b47c) but there is no information how big should be jump_threshold. 0.1? 1? 10? 1000? For my robot, if this value lower than 10, it computes only several percents of path. What value should I set?

**Comment by marioprats** [comment]
Hi, sorry it took so long to look at this. From the documentation:

```
 No more than jump_threshold is allowed as change in distance in the configuration space of the robot (this is to prevent 'jumps' in IK solutions).
```

This is maximum distance in radians for revolute joints, or meters for prismatic joints, for consecutive waypoints. The exact value to use depends on your application, but typically you want something very small (maybe around 0.1 rad). Solvable paths shouldn't require jumps much higher than that. If you are not getting solutions, it probably means that the path can't be solved.
