### ISSUE TITLE
Noisy output with MoveIt Servo and ForwardVelocityController

### ISSUE THREAD

**Issue by Pomorondza** [ros-planning/moveit2#2246]
### Description

In brief, I am using MoveIt Servo to control the velocity of the UR3e robot in real time. As the figure suggests, the velocity of the end effector _measured_ at the output is very noisy, as opposed to the input _desired_ signal, which follows the control law as implemented in my code.
![git](https://github.com/ros-planning/moveit2/assets/26152420/499cc754-1ea9-43bc-9720-c7ee424cdcf3)

Recently, I have also posted [this issue](https://github.com/ros-controls/ros2_controllers/issues/649) over ROS2_controllers repo, yet got no reply. Does anyone have an idea what might me causing the noise?

### Your environment
* ROS Distro: Humble
* OS Version: Ubuntu 22.04
* MoveIt Servo main branch source build (9952bdd)

**Comment by sjahr** [comment]
How are you measuring the velocities? What is your DDS configuration (we recommend cyclone_dds at the moment)? What does your network setup generally look like?

@ibrahiminfinite @sea-bass FYI
