### ISSUE TITLE
Cannot import moveit_py

### ISSUE THREAD

**Issue by faheemkhaskheli9** [ros-planning/moveit2#2250]
I create a ros2 package, ros2 node working fine. 
Trying to import moveit_py.

Import moveit
#error moveit not found

Import moveit_py
#error not found

Import MoveItPy
#error not found. 

I sourced moveit_ws, still not working. 
Created project in moveit ws, still not working.

**Comment by faheemkhaskheli9** [comment]
Trying to run this code. 

```Python
rclpy.init()
logger = rclpy.logging.get_logger("moveit_py.pose_goal")

# instantiate MoveItPy instance and get planning component
panda = MoveItPy(node_name="moveit_py")
panda_arm = panda.get_planning_component("panda_arm")
logger.info("MoveItPy instance created")

```

**Comment by RobinHeitz** [comment]
Can you tell me what you've found out? Am sitting at the same problem.
