### ISSUE TITLE
colcon build issue in moveit2 ros2 

### ISSUE THREAD

**Issue by faheem-khaskheli** [ros-planning/moveit2#2263]
# Error

ws_moveit/src/moveit2/moveit_setup_assistant/moveit_setup_srdf_plugins/include/moveit_setup_srdf_plugins/rotated_header_view.hpp:0: Note: No relevant classes found. No output generated.

**Comment by sjahr** [comment]
Sorry but with so little information I cannot help you, so I am closing this issue for now. Feel free to re-open and ask a question + provide the complete build terminal output. To install moveit2 you can follow the install instructions: https://moveit.ros.org/install-moveit2/source/
