### ISSUE TITLE
Load robot_description from topic

### ISSUE THREAD

**Issue by Noel215** [ros-planning/moveit2#2291]
Hi,

I would like to be able to load the robot description from the `/robot_description` topic instead of passing it as a parameter. 
This feature would be great in order to centralize the way of getting the description for all nodes. Right now I need to load the robot description and do the proper substitutions on each different launcher I have, as in [tiago_moveit_config/launch/move_group.launch.py](https://github.com/pal-robotics/tiago_moveit_config/blob/humble-devel/launch/move_group.launch.py#L57-L67), [tiago_moveit_config/launch/moveit_rviz.launch.py](https://github.com/pal-robotics/tiago_moveit_config/blob/humble-devel/launch/moveit_rviz.launch.py#L57-L67) and the topic, which sometimes leads to different robot descriptions.

I'm not really sure if that's possible with the current implementation but I've seen some other issues mentioning it as https://github.com/ros-planning/moveit2/issues/169, https://github.com/ros-planning/moveit2/issues/755, https://github.com/ros-planning/moveit2/issues/1511, among others. I've also found that the node is able to publish the robot description, but nothing about reading it from a topic.

Could you please let me know if that feature is available right now? 
If not, is it planned to add soon to MoveIt 2?

Thanks :)

**Comment by Noel215** [comment]
Hi,

Could I have a response on this, please?

**Comment by saikishor** [comment]
Hello!

We would like to have this feature on our robots. Is it possible to have this in the near future?

Thank you,

**Comment by henningkayser** [comment]
This has already been implemented a while ago in https://github.com/ros-planning/moveit2/pull/765, and since https://github.com/ros-planning/moveit2/pull/1806 all you need to do is leave the robot_description parameter empty in your launch file, so that MoveIt loads it from `/robot_description`. I'm closing this issue. If you would improve the documentation in a way that would have prevented you from filing this issue, that would be greatly appreciated.

**Comment by lubro-crypto** [comment]
Hi, has this been pulled into the Humble branch? 
In my current version (v2.5.6), if the robot description field of the MoveItConfigsBuilder is left empty, then it will look for a xacro file in the package at a default location. Has this been updated in a later commit?

**Comment by mhubii** [comment]
same, in the `.setup_assistant` file, it has an entry:

```yaml
moveit_setup_assistant_config:
  urdf:
    package: ...
    relative_path: ...
```

once the `urdf` block is removed, the description is forcefully loaded from the `/robot_description` topic, and this warning is printed:

```shell
WARNING:root:Cannot infer URDF from `path_to_package`. -- using xyz.urdf
WARNING:root:"File path_to_package/xyz.urdf doesn't exist"
WARNING:root:The robot description will be loaded from /robot_description topic 
WARNING:root:"File path_to_package/xyz.urdf doesn't exist"
WARNING:root:The robot description will be loaded from /robot_description topic 
```

loading from different sources leads to potentially dangerous behavior, e.g. when the robot pose is configurable with arguments. Then what MoveIt loads from file and what the actual system is may deviate.

this can be avoided on the user side through correct configuration at launch:

```python
MoveItConfigsBuilder(...).robot_description(mappings=...)
```

but maybe a single source might make sense here.

(this runs on jazzy)
