### ISSUE TITLE
Please backport #1856  to Humble - Pilz multi-group incompatibility

### ISSUE THREAD

**Issue by firesurfer** [ros-planning/moveit2#2305]
**Is your feature request related to a problem? Please describe.**
As described in #1856 the Pilz planner assume wrong starting states for multi-group systems. This makes them unusable in some setups. 

**Describe the solution you'd like**
Please backport the PR to Humble as many users are still using humble

**Comment by sjahr** [comment]
Can you test https://github.com/ros-planning/moveit2/pull/2306 and verify that it works on the latest version of the humble branch?
