### ISSUE TITLE
Requesting new ROS Iron Release

### ISSUE THREAD

**Issue by sloretz** [ros-planning/moveit2#2327]
May I request a new Iron release? The last one was in May (https://github.com/ros/rosdistro/pull/37271), and there [are quite a few changes since then](https://github.com/ros-planning/moveit2/compare/2.7.4...iron).

**Comment by tylerjw** [comment]
I'm happy to do this if no one objects to cutting one. I'll also cut a rolling release. @henningkayser did you make a iron branch yet?

**Comment by henningkayser** [comment]
we do have an iron branch, but it could probably use some updates before cutting the release.

**Comment by henningkayser** [comment]
iron branch was updated, new release was bloomed
