### ISSUE TITLE
[Servo] Using TF lookup instead of robot state for transforms causing drift

### ISSUE THREAD

**Issue by sea-bass** [ros-planning/moveit2#2352]
I was seeing some weird drift in the new MoveIt Servo, and finally found the source of the issue.

In new servo we're doing conversions to the planning frame using a TF buffer:

```cpp
const auto planning_to_command_tf =
    transform_buffer_.lookupTransform(command.frame_id, servo_params_.planning_frame, rclcpp::Time(0));
```

In the old servo, we're doing conversions to the planning frame using the robot state:

```cpp
moveit::core::RobotStatePtr robot_state = planning_scene_monitor_->getStateMonitor()->getCurrentState();
const Eigen::Isometry3d planning_to_command_tf_eigen =
   robot_state->getGlobalLinkTransform(servo_params_.planning_frame).inverse() *
   robot_state->getGlobalLinkTransform(command.frame_id);
```

While functionally this is the same, it's causing significant drift in these systems.

New servo (even after the correction in https://github.com/ros-planning/moveit2/pull/2350):
https://github.com/ros-planning/moveit2/assets/4603398/43caf2e6-bb25-42ab-a115-884b57a9c1f6

Old servo (actually, this is new servo but with the transform approach reverted as above):
https://github.com/ros-planning/moveit2/assets/4603398/c4b778fe-59f3-4f12-a94a-9763fed33d49

---

So, I think we should have some kind of check on whether the frame name can be retrieved using the robot model or not, and that should decide whether to use TF.

@AndyZe @ibrahiminfinite

**Comment by AndyZe** [comment]
sounds ok to me  :+1:

**Comment by ibrahiminfinite** [comment]
Yeah, I agree as well.

**Comment by sea-bass** [comment]
BTW the `doTransform()` method applied on an Eigen 6d vector will automatically apply the spatial twist w/ translation and rotation, so I made some tweaks on that other PR related to this.

**Comment by sea-bass** [comment]
Here's what I'm thinking:

* The implementation of `RobotState::getLinkModel()` shown [here](https://github.com/ros-planning/moveit2/blob/main/moveit_core/robot_model/src/robot_model.cpp#L1345-L1346) has the code necessary to find, in O(1) time, whether a link exists in the robot model. So we should pull that out into its own function that won't log an error every time we look it up.
* So, if the link is found in the robot model, grab it directly that way; otherwise, use the TF lookup.

If this sounds good, I can work on the change.

**Comment by sea-bass** [comment]
One more bug... I found the issue with TF was because the transform we were looking up was reversed... that and we were always using the spatial twist. TF works fine now.

**Comment by ibrahiminfinite** [comment]
I remember fixing the reversed TF issue in the original PR itself, after Andy noticed the wrong behaviour, so the fix was the bug? LoL

**Comment by sea-bass** [comment]
Might have been that the `doTransform()` function does the full spatial twist calculation instead of just the rotation portion, and flipping the transform back around maybe made this behavior less apparent?

I still think my incoming PR should be checked by you guys because at this point I've made a bunch of changes.
