### ISSUE TITLE
[Servo] Increased CPU utilisation.

### ISSUE THREAD

**Issue by ibrahiminfinite** [ros-planning/moveit2#2353]
It was reported that the new Servo implementation has increased CPU utilisation compared to the old one.
This issue will track the efforts to reduce the CPU usage. 

Possible reasons:

1. Usage of `Eigen::Vector` rather than `std::vector`, for smaller vectors with simple operations, `std::vector` appears to perform better. 
2. Dynamic fetching of things like planning group, IK solver etc.

**Comment by sea-bass** [comment]
Should we close this? I think the leading culprit was the extra TF buffer and we got rid of that.
