### ISSUE TITLE
Moveit Python Library: Failed to load any planning pipelines

### ISSUE THREAD

**Issue by RemiFabre** [ros-planning/moveit2#2409]
### Description

Hi,
I'm trying to use the Python bidings for MoveIt! In its current state, I'm able to use MoveIt's capabilities using RViZ GUI interface and Gazebo. e.g I'm able to path plan and execute moves. So the moveit_config seems fine.

However, I'm unable to use the Python bindings as MoveItPy() crashes. This is a minimalistic python code that creates the issue:
```
rclpy.init()
    logger = get_logger("moveit_py.pose_goal")
    logger.info("Starting moveit_py test ##########################################################################################################")
    # instantiate MoveItPy instance and get planning component
    reachy = MoveItPy(node_name="moveit_py")
    logger.info("MoveItPy instance created ##########################################################################################################")
``` 
This is the console output of the node:
https://gist.github.com/RemiFabre/bf635bb9a1bf2415875cd8a7577d60af

The parameters received by the python node seem fine. This is a copy/paste of the temporary file created by the launch file to give the node the parameters, e.g "moveit_test --ros-args -r __node:=moveit_py --params-file /tmp/launch_params_cxx5c3zq". I just edited out the URDF file and the SRDF file to make it shorter:
https://gist.github.com/RemiFabre/507fe47b51ee29c8cadba3c767a52af0

I created an ompl_planning.yaml file heavily inspired from the Panda example, here is my file:
https://gist.github.com/RemiFabre/6ba2f00b63525129f020566264076260

Maybe there is a format change or a typo that I'm unable to see here?

### Environment
* ROS Distro: Iron
* OS Version: Ubuntu 22.04
* Binary build, ros-iron-moveit 2.8.0-1jammy.20230912.130911
* Cyclone DDS

Thank you for your work,

**Comment by RemiFabre** [comment]
Ok so we got it to work.

First, we set the path to the "moveit_cpp.yaml" by hand in the launch file, otherwise it takes a default one in /opt/ros/.... For example:
moveit_config = moveit_config.moveit_cpp(file_path=get_package_share_directory("you_config_package")+ "/config/moveit_cpp.yaml")

And in the moveit_cpp.yaml replace:
```
planning_pipelines:
    pipeline_names: ["ompl", "pilz_industrial_motion_planner", "chomp", "ompl_rrt_star"]
```
```
planning_pipelines:
pipeline_names: ["ompl", "pilz_industrial_motion_planner"]
```

**Comment by RobinHeitz** [comment]
Hi, I'm trying to start with python bindings in Moveit2.
@RemiFabre  Can you maybe comment the complete pythons scripts including imports? Or maybe even distribute a small ros2 python pkg with a working example? I'm struggling to find a starting point since the documentation does not tell much.

**Comment by PeterMitrano** [comment]
Here's what I'm using that seems to work:

```
    robot_name = "victor"
    from ament_index_python import get_package_share_directory
    from moveit.planning import MoveItPy
    from moveit_configs_utils import MoveItConfigsBuilder
    moveit_config_builder = MoveItConfigsBuilder(robot_name)
    # This line is key!!!
    moveit_config_builder.moveit_cpp(file_path=get_package_share_directory("victor_moveit_config") + "/config/moveit_cpp.yaml") 
    moveit_config_dict = moveit_config_builder.to_moveit_configs().to_dict()
    robot = MoveItPy(node_name="moveit_py", config_dict=moveit_config_dict)

```

**Comment by Miftahur92** [comment]
> Here's what I'm using that seems to work:
> 
> ```
>     robot_name = "victor"
>     from ament_index_python import get_package_share_directory
>     from moveit.planning import MoveItPy
>     from moveit_configs_utils import MoveItConfigsBuilder
>     moveit_config_builder = MoveItConfigsBuilder(robot_name)
>     # This line is key!!!
>     moveit_config_builder.moveit_cpp(file_path=get_package_share_directory("victor_moveit_config") + "/config/moveit_cpp.yaml") 
>     moveit_config_dict = moveit_config_builder.to_moveit_configs().to_dict()
>     robot = MoveItPy(node_name="moveit_py", config_dict=moveit_config_dict)
> ```

Hi Peter, is this a launch file?

**Comment by PeterMitrano** [comment]
No I think that's just a regular python script

**Comment by Divyam-uga** [comment]
Hi @PeterMitrano,

I have been following your instructions. In my environment, I have a Gazebo simulation with 2 UR manipulators and I'm attempting to control one UR robot using moveit_py. I've followed all the necessary configuration steps as you outlined, and I have also set the 'use_sim_time' param to true in Gazebo and all related nodes. However, I'm encountering an issue where 'current_state_monitor.cpp' is not receiving joint_angles with recent timestamps.

I've verified that joint states are being published in the correct sim time using "ros2 topic echo /joint_states" and "ros2 topic echo /clock", but it seems that the requested time reflects my PC's total run time instead of the current simulation time step. As a beginner in ROS 2 and Moveit 2, I'm unsure how to address this issue. I tried several ways to set the 'use_sim_time' param to true globally before initializing 'moveit_py' but it's not working out.

Any suggestions on resolving this would be greatly appreciated.

Thank you.

**Error message:**
![Screenshot from 2024-07-12 11-06-16](https://github.com/user-attachments/assets/cf5cfc3b-bf49-4c61-b5ee-6f0291b895bc)


**'ur_sort.py':**
![Screenshot from 2024-07-12 11-11-31](https://github.com/user-attachments/assets/306ecd1c-93ea-4a50-a331-5c98b94a5d13)

**Comment by s4lmon** [comment]
@Divyam-uga any luck with the above file? Running into similar issue.

**Comment by HuanyuL** [comment]
Hello, I also had the same issue when I try to build a node directly in python code. Baiscally you need to load ``moveit_configs`` to the node which explictly define ``SRDF`` and ``moviet_cpp``.  To do this, you can either use a launch file with the ``moveit_configs`` to your node's parameter or add ``SRDF`` and ``moveit_cpp`` to your configs.

Here is my code for initializing moveitpy, it works on ros2 jazzy.
```
import rclpy
from moveit.planning import MoveItPy
from moveit_configs_utils import MoveItConfigsBuilder
from pathlib import Path

moveit_config = (
    MoveItConfigsBuilder(robot_name="ur", package_name="ur_moveit_config")
    .robot_description_semantic(Path("srdf") / "ur.srdf.xacro", {"name": "ur10e"})
    .moveit_cpp(Path("config") / "moveit_cpp.yaml")
    .to_moveit_configs()
).to_dict()

rclpy.init()

ur = MoveItPy(node_name="ur", config_dict=moveit_config)
ur_arm = ur.get_planning_component("ur_manipulator")
```
