### ISSUE TITLE
Local Planner Option to Change

### ISSUE THREAD

**Issue by jacob-02** [ros-planning/moveit2#2469]
Hello moveit2 community!

My name is Jacob V Sanoj and I'm looking into how different planners affect the control effort and efficiency of the robotic arm.
In the Hybrid Planning architecture, the documentation specifies that there are multiple Local and Global planners. I know there are options for the Global Planner but I am not seeing an option to change the Local Planner.
**Describe the solution you'd like**
I would like an option to be able to change the Local Planner to one that I desire to see how they affect the overall planning.

Thank you.

**Comment by sjahr** [comment]
At the moment there are not multiple local planner default options available in MoveIt2 but you can implement one yourself. If you're considering to implement one and contributing it to MoveIt2, I am happy to answer questions and review it! Feel free to re-open this issue or another one if you have more questions.
