### ISSUE TITLE
Is moveit_py ready for humble?

### ISSUE THREAD

**Issue by JaisonJose241** [ros-planning/moveit2#2492]
I wanted to ask that is the `moveit_py` in the `main` branch is available for the ROS humble version? or is it still in pipeline?

Is there any way to build the same package in `humble` version?

**Comment by Shobuj-Paul** [comment]
> Is there any way to build the same package in `humble` version?

You can build the main branch [from source](https://moveit.ros.org/install-moveit2/source/#rolling-humble---unstable) for ROS Humble.
