### ISSUE TITLE
moveit_task_constructor_capabilities pkg fails while building.

### ISSUE THREAD

**Issue by kumar-sanjeeev** [ros-planning/moveit2#2531]
### Description
While building the source code to follow the tutorials, the `moveit_task_constructor_capabilities` package fails to build.

### Your environment
* ROS Distro: Humble
* OS Version: Ubuntu 22.04
* Source build
* Master branch for moveit2_tutorials ( but **moveit_task_constructor_capabilities pkg** is from `ros2` branch)
* Cyclone DDS

### Steps to reproduce
Just follow the [Getting Started](https://moveit.picknik.ai/main/doc/tutorials/getting_started/getting_started.html) from Tutorials section.

### Expected behaviour
All packages should be built successfully.

### Actual behaviour
`moveit_task_constructor_capabilities` package failed to build. Hence, I'm not able to run the `ros2 launch moveit2_tutorials demo.launch.py`.

#### Link to Pull Request: For Fix
This issue has been fixed in my pull request [Fix 508](https://github.com/ros-planning/moveit_task_constructor/pull/508).

**Comment by moriarty** [comment]
Closing this issue the humble branch must be used when using humble.

See comment here https://github.com/ros-planning/moveit_task_constructor/pull/508#issuecomment-1812457181
