### ISSUE TITLE
Are there any plans to integrate trajopt into moveit?

### ISSUE THREAD

**Issue by jycc1991** [ros-planning/moveit2#255]
### Description

Overview of your issue here.

### Your environment
* ROS Distro: [Kinetic|Melodic]
* OS Version: e.g. Ubuntu 18.04
* Source or Binary build?
* If binary, which release version?
* If source, which branch?

### Steps to reproduce
Tell us how to reproduce this issue. Attempt to provide a working demo, perhaps using Docker.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Backtrace or Console output

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by AndyZe** [comment]
The answer at the moment is no, because (I believe) trajopt is not even fully functional with MoveIt1 yet.
