### ISSUE TITLE
Allowing individual joint margins for moveit servo

### ISSUE THREAD

**Issue by Nils-ChristianIseke** [ros-planning/moveit2#2570]
My robot consists of prismatic and revolute joints. Just having a joint_limit_margin that is applied to all joints is not enough, because if the margin fits for the revolute joints, it is too big for the prismatic joints. Setting the joint_limit_margin for each individual joint might solve this. If you appreciate this, I could open a pull request for these changes.

**Comment by Nils-ChristianIseke** [comment]
@AndyZe Done in  #2576

**Comment by ibrahiminfinite** [comment]
This makes sense, took a look at the PR, LGTM
