### ISSUE TITLE
Remove redundant namespaces robot_state and robot_model

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit2#263]
Per the [Noetic MIGRATION notes](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md):

> Replace the redundant namespaces robot_state:: and robot_model:: with the actual namespace moveit::core::. **The additional namespaces will disappear in the future (ROS2).**

I propose we remove those namespaces now in MoveIt 2, if they have not already been.

**Comment by doitmaan** [comment]
test in progress 

PR: [https://github.com/ros-planning/moveit2/pull/276#issue-482574830](url)

**Comment by henningkayser** [comment]
Removed with #276
