### ISSUE TITLE
Help needed Random Planning

### ISSUE THREAD

**Issue by jdbravo** [ros-planning/moveit2#2634]
I’m writing a c++ node that moves an arm to a desired Pose, it’s working fine using OMPL, but I want to make that every plan uses random solutions even if the pose is the same.

the idea is that the arm reaches a pose, come back to a desired state and come back to the same pose but using a different trajectory.

is that possible ?

thank you

**Comment by henningkayser** [comment]
OMPL already does exactly that. If trajectories look alike it's probably pure coincidence (or the solution is trivial). If you want to force different goal configurations, you can try using [RobotState::setToRandomPositionsNearBy()](https://moveit.picknik.ai/main/api/html/classmoveit_1_1core_1_1RobotState.html#a0613ebcd26af7d856096447fa66bc069) for sampling goal states. For further usage questions, please open a GitHub discussion.
