### ISSUE TITLE
MoveItPy Blocking Execution

### ISSUE THREAD

**Issue by aoberai** [ros-planning/moveit2#2655]
Not sure why the blocking param was removed from execute, calling execute for me is async.

**Comment by sjahr** [comment]
Not sure what the intend of this issue is. Do you mind elaborating on your problem/ feature request and give some context why you opened this issue?

**Comment by JafarAbdi** [comment]
@aoberai Please take a look at https://github.com/ros-planning/moveit2/pull/2235 for more info about the reasoning behind deleting it from the C++ API
