### ISSUE TITLE
moveit::core::error_code_to_string broken in Humble

### ISSUE THREAD

**Issue by reidchristopher** [ros-planning/moveit2#2688]
### Description

`moveit::core::error_code_to_string` was not updated to match the updated __moveit_msgs/msg/MoveItErrorCodes.msg__ definition. For example, an invalid start state gives -26 (START_STATE_INVALID), but that is not a checked value in the switch statement.It also has no default case, which causes the program to crash if you have a case not accounted for (like START_STATE_INVALID). This is fixed in Iron onwards.

### Your environment
* ROS Distro: Humble
* OS Version: Ubuntu 22.04
* Binary - recent apt install

### Steps to reproduce
Have plan start state in collision and call 
`moveit_cpp::PlanningComponent::PlanSolution plan_solution = planning_component.plan(plan_parameters_);` 
When the plan fails, call `moveit::core::error_code_to_string(plan_solution.error_code)`

### Expected behaviour
Get a string describing the error code

### Actual behaviour
Crash the program (throw std::bad_alloc)

**Comment by henningkayser** [comment]
#2689 is merged, closing this.
