### ISSUE TITLE
[Servo] Demos failing

### ISSUE THREAD

**Issue by ibrahiminfinite** [ros-planning/moveit2#2733]
**Description**

The servo demos (`joint_jog`, `twist` , `pose`) seems to be failing with the following error regarding an `update_period` parameter.

![image](https://github.com/ros-planning/moveit2/assets/12377945/af78006c-982c-41f9-a44b-9a955f4c84f3)

**Expected behavior**

The demos should run without errors.

EDIT: The parameter is for the smoothing plugin, the demo launch files need to include it as well.

cc: @sea-bass

**Comment by sea-bass** [comment]
Yep, seems that the changes are in `demo_ros_api.py` but not the other files in that folder. Should be a quick fix.
