### ISSUE TITLE
Unable to Locate Package ros-humble-gazebo-ros2-control

### ISSUE THREAD

**Issue by Saketh7256** [ros-planning/moveit2#2860]
I am trying to install MoveIt 2 on Ubuntu 22.04 with ROS 2 Humble Hawksbill following the official MoveIt 2 setup tutorial. During the dependency installation step using rosdep, I encountered an error indicating that the package ros-humble-gazebo-ros2-control could not be found.

The document contains the commands I used and the errors encountered

Could you please guide on resolving this issue.

[ros-humble-gazebo-ros2-control.docx](https://github.com/user-attachments/files/15538978/ros-humble-gazebo-ros2-control.docx)

Thank you!

**Comment by rhaschke** [comment]
You mixed up the order of commands. Only in the last step you registered the ROS2 package repository (http://packages.ros.org/ros2/ubuntu is listed for the command `apt update`). Given that, you should be able to install the package. Try again.

**Comment by Saketh7256** [comment]
Thank you for the previous help; I was able to install  successfully. However, I am facing an issue now when I try to launch the _demo and configure the plugin_ using the following command:

**ros2 launch moveit2_tutorials demo.launch.py**

RViz opend for a second and then closed. I tried to manually start it, and it gave me error messages. The details of the error can be found in this document: **"ros2 launch moveit2_tutorials demo launch."**

Could you help me troubleshoot this issue? Any guidance on resolving the URDF-related problem would be greatly appreciated.

Thank you





[ros2 launch moveit2_tutorials demo launch.docx](https://github.com/user-attachments/files/15593992/ros2.launch.moveit2_tutorials.demo.launch.docx)


[MoveIT installation.docx](https://github.com/user-attachments/files/15593996/MoveIT.installation.docx)


https://moveit.picknik.ai/main/doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.html

**Comment by sjahr** [comment]
I'll close this issue now because the original problem is solved. Please file a new issue if you run into new bugs. It would be easier for others to help you if you post the log directly into a comment
```
like this
```
Rather than providing files. Additionally, I'd recommend asking general questions on https://robotics.stackexchange.com/ because there is a broader community to help you with ros2, URDF etc related issues. The moveit2 issue section is mainly intended to report actual bugs in moveit2

**Comment by neonSM** [comment]
im facing the same probleme ,i got this error msg:
        E: Unable to locate package ros-humble-ros-ign-ros2-control
