### ISSUE TITLE
boost system not included?

### ISSUE THREAD

**Issue by brookdpg** [ros-planning/moveit2#295]
Description

Overview of your issue here.

 Your environment
* ROS Distro: [foxy ]
* OS Version: e.g. Ubuntu 20.04
* Source or Binary build? source
HEAD detached at d95e4aecf

### Steps to reproduce
initial compiling of ws_moveit directory 

 Expected behaviour
all packages finish processing successfully

 Actual behaviour
build fails

Backtrace or Console output
[error.txt](https://github.com/ros-planning/moveit2/files/5381591/error.txt)

**Comment by JafarAbdi** [comment]
Looking into the CMakeLists of the package it seems like it's linked correctly against Boost, can you check if the shared library exists on your system by running `find /usr/lib -name libboost_system.so*` or `find /usr/lib -name libboost_*.so*`

**Comment by brookdpg** [comment]
running the search command gives me 

ops@ops-XPS-15-9500:~/ws_ros2$ sudo find /usr/lib -name libboost_*
/usr/lib/x86_64-linux-gnu/libboost_numpy38.so
/usr/lib/x86_64-linux-gnu/libboost_date_time.so
/usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_stacktrace_addr2line.a
/usr/lib/x86_64-linux-gnu/libboost_chrono.a
/usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_stacktrace_noop.a
/usr/lib/x86_64-linux-gnu/libboost_thread.so
/usr/lib/x86_64-linux-gnu/libboost_random.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_type_erasure.a
/usr/lib/x86_64-linux-gnu/libboost_math_tr1.so
/usr/lib/x86_64-linux-gnu/libboost_filesystem.a
/usr/lib/x86_64-linux-gnu/libboost_container.so
/usr/lib/x86_64-linux-gnu/libboost_math_c99l.a
/usr/lib/x86_64-linux-gnu/libboost_stacktrace_backtrace.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_stacktrace_noop.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_math_c99.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_stacktrace_noop.so
/usr/lib/x86_64-linux-gnu/libboost_mpi.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_graph_parallel.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_math_c99f.a
/usr/lib/x86_64-linux-gnu/libboost_math_tr1l.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_mpi_python38.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_atomic.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_graph.a
/usr/lib/x86_64-linux-gnu/cmake/boost_math_c99-1.71.0/libboost_math_c99-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_math_c99-1.71.0/libboost_math_c99-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_coroutine-1.71.0/libboost_coroutine-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_coroutine-1.71.0/libboost_coroutine-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_numpy-1.71.0/libboost_numpy-variant-shared-py3.8.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_numpy-1.71.0/libboost_numpy-variant-static-py3.8.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_unit_test_framework-1.71.0/libboost_unit_test_framework-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_unit_test_framework-1.71.0/libboost_unit_test_framework-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_python-1.71.0/libboost_python-variant-shared-py3.8.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_python-1.71.0/libboost_python-variant-static-py3.8.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_thread-1.71.0/libboost_thread-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_thread-1.71.0/libboost_thread-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_mpi-1.71.0/libboost_mpi-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_mpi-1.71.0/libboost_mpi-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_locale-1.71.0/libboost_locale-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_locale-1.71.0/libboost_locale-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_atomic-1.71.0/libboost_atomic-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_atomic-1.71.0/libboost_atomic-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_context-1.71.0/libboost_context-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_context-1.71.0/libboost_context-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_prg_exec_monitor-1.71.0/libboost_prg_exec_monitor-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_prg_exec_monitor-1.71.0/libboost_prg_exec_monitor-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_math_tr1f-1.71.0/libboost_math_tr1f-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_math_tr1f-1.71.0/libboost_math_tr1f-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_graph_parallel-1.71.0/libboost_graph_parallel-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_graph_parallel-1.71.0/libboost_graph_parallel-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_wave-1.71.0/libboost_wave-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_wave-1.71.0/libboost_wave-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_log_setup-1.71.0/libboost_log_setup-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_log_setup-1.71.0/libboost_log_setup-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_stacktrace_noop-1.71.0/libboost_stacktrace_noop-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_stacktrace_noop-1.71.0/libboost_stacktrace_noop-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_filesystem-1.71.0/libboost_filesystem-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_filesystem-1.71.0/libboost_filesystem-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_timer-1.71.0/libboost_timer-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_timer-1.71.0/libboost_timer-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_fiber-1.71.0/libboost_fiber-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_fiber-1.71.0/libboost_fiber-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_type_erasure-1.71.0/libboost_type_erasure-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_type_erasure-1.71.0/libboost_type_erasure-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_math_c99f-1.71.0/libboost_math_c99f-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_math_c99f-1.71.0/libboost_math_c99f-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_chrono-1.71.0/libboost_chrono-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_chrono-1.71.0/libboost_chrono-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_mpi_python-1.71.0/libboost_mpi_python-variant-static-py3.8.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_mpi_python-1.71.0/libboost_mpi_python-variant-shared-py3.8.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_wserialization-1.71.0/libboost_wserialization-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_wserialization-1.71.0/libboost_wserialization-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_graph-1.71.0/libboost_graph-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_graph-1.71.0/libboost_graph-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_test_exec_monitor-1.71.0/libboost_test_exec_monitor-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_test_exec_monitor-1.71.0/libboost_test_exec_monitor-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_iostreams-1.71.0/libboost_iostreams-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_iostreams-1.71.0/libboost_iostreams-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_math_tr1l-1.71.0/libboost_math_tr1l-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_math_tr1l-1.71.0/libboost_math_tr1l-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_stacktrace_basic-1.71.0/libboost_stacktrace_basic-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_stacktrace_basic-1.71.0/libboost_stacktrace_basic-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_stacktrace_addr2line-1.71.0/libboost_stacktrace_addr2line-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_stacktrace_addr2line-1.71.0/libboost_stacktrace_addr2line-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_log-1.71.0/libboost_log-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_log-1.71.0/libboost_log-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_program_options-1.71.0/libboost_program_options-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_program_options-1.71.0/libboost_program_options-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_regex-1.71.0/libboost_regex-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_regex-1.71.0/libboost_regex-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_system-1.71.0/libboost_system-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_system-1.71.0/libboost_system-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_date_time-1.71.0/libboost_date_time-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_date_time-1.71.0/libboost_date_time-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_stacktrace_backtrace-1.71.0/libboost_stacktrace_backtrace-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_stacktrace_backtrace-1.71.0/libboost_stacktrace_backtrace-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_math_tr1-1.71.0/libboost_math_tr1-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_math_tr1-1.71.0/libboost_math_tr1-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_serialization-1.71.0/libboost_serialization-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_serialization-1.71.0/libboost_serialization-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_container-1.71.0/libboost_container-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_container-1.71.0/libboost_container-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_math_c99l-1.71.0/libboost_math_c99l-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_math_c99l-1.71.0/libboost_math_c99l-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_random-1.71.0/libboost_random-variant-static.cmake
/usr/lib/x86_64-linux-gnu/cmake/boost_random-1.71.0/libboost_random-variant-shared.cmake
/usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.a
/usr/lib/x86_64-linux-gnu/libboost_context.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_mpi.so
/usr/lib/x86_64-linux-gnu/libboost_locale.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_graph.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_coroutine.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_mpi.a
/usr/lib/x86_64-linux-gnu/libboost_graph.so
/usr/lib/x86_64-linux-gnu/libboost_math_tr1f.so
/usr/lib/x86_64-linux-gnu/libboost_math_c99.a
/usr/lib/x86_64-linux-gnu/libboost_python38.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_container.a
/usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_math_c99l.so
/usr/lib/x86_64-linux-gnu/libboost_stacktrace_basic.a
/usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_random.a
/usr/lib/x86_64-linux-gnu/libboost_math_tr1f.a
/usr/lib/x86_64-linux-gnu/libboost_coroutine.so
/usr/lib/x86_64-linux-gnu/libboost_test_exec_monitor.a
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_serialization.a
/usr/lib/x86_64-linux-gnu/libboost_fiber.so
/usr/lib/x86_64-linux-gnu/libboost_stacktrace_backtrace.a
/usr/lib/x86_64-linux-gnu/libboost_log.so
/usr/lib/x86_64-linux-gnu/libboost_timer.so
/usr/lib/x86_64-linux-gnu/libboost_context.a
/usr/lib/x86_64-linux-gnu/libboost_mpi_python38.a
/usr/lib/x86_64-linux-gnu/libboost_atomic.a
/usr/lib/x86_64-linux-gnu/libboost_regex.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_log.a
/usr/lib/x86_64-linux-gnu/libboost_python38.a
/usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_wave.so
/usr/lib/x86_64-linux-gnu/libboost_atomic.so
/usr/lib/x86_64-linux-gnu/libboost_graph_parallel.a
/usr/lib/x86_64-linux-gnu/libboost_wave.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_wave.a
/usr/lib/x86_64-linux-gnu/libboost_log_setup.so
/usr/lib/x86_64-linux-gnu/libboost_math_tr1l.so
/usr/lib/x86_64-linux-gnu/libboost_serialization.so
/usr/lib/x86_64-linux-gnu/libboost_python38.so
/usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so
/usr/lib/x86_64-linux-gnu/libboost_math_c99f.so
/usr/lib/x86_64-linux-gnu/libboost_stacktrace_addr2line.so
/usr/lib/x86_64-linux-gnu/libboost_graph_parallel.so
/usr/lib/x86_64-linux-gnu/libboost_stacktrace_addr2line.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_system.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_wserialization.a
/usr/lib/x86_64-linux-gnu/libboost_timer.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_container.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_filesystem.so
/usr/lib/x86_64-linux-gnu/libboost_math_c99.so
/usr/lib/x86_64-linux-gnu/libboost_system.a
/usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_log_setup.a
/usr/lib/x86_64-linux-gnu/libboost_stacktrace_basic.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_math_tr1l.a
/usr/lib/x86_64-linux-gnu/libboost_date_time.a
/usr/lib/x86_64-linux-gnu/libboost_timer.a
/usr/lib/x86_64-linux-gnu/libboost_log_setup.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_prg_exec_monitor.so
/usr/lib/x86_64-linux-gnu/libboost_iostreams.so
/usr/lib/x86_64-linux-gnu/libboost_math_tr1.a
/usr/lib/x86_64-linux-gnu/libboost_program_options.a
/usr/lib/x86_64-linux-gnu/libboost_context.so
/usr/lib/x86_64-linux-gnu/libboost_fiber.a
/usr/lib/x86_64-linux-gnu/libboost_wserialization.so
/usr/lib/x86_64-linux-gnu/libboost_locale.so
/usr/lib/x86_64-linux-gnu/libboost_type_erasure.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_math_tr1.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_math_c99l.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_numpy38.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_regex.a
/usr/lib/x86_64-linux-gnu/libboost_system.so
/usr/lib/x86_64-linux-gnu/libboost_chrono.so
/usr/lib/x86_64-linux-gnu/libboost_stacktrace_basic.so
/usr/lib/x86_64-linux-gnu/libboost_math_c99f.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_exception.a
/usr/lib/x86_64-linux-gnu/libboost_prg_exec_monitor.a
/usr/lib/x86_64-linux-gnu/libboost_numpy38.a
/usr/lib/x86_64-linux-gnu/libboost_stacktrace_backtrace.so
/usr/lib/x86_64-linux-gnu/libboost_iostreams.a
/usr/lib/x86_64-linux-gnu/libboost_coroutine.a
/usr/lib/x86_64-linux-gnu/libboost_prg_exec_monitor.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_mpi_python38.so
/usr/lib/x86_64-linux-gnu/libboost_wserialization.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_random.so
/usr/lib/x86_64-linux-gnu/libboost_regex.so
/usr/lib/x86_64-linux-gnu/libboost_thread.a
/usr/lib/x86_64-linux-gnu/libboost_program_options.so
/usr/lib/x86_64-linux-gnu/libboost_type_erasure.so
/usr/lib/x86_64-linux-gnu/libboost_locale.a
/usr/lib/x86_64-linux-gnu/libboost_log.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_fiber.so.1.71.0
/usr/lib/x86_64-linux-gnu/libboost_math_tr1f.so.1.71.0
ops@ops-XPS-15-9500:~/ws_ros2$

**Comment by JafarAbdi** [comment]
Both `Boost::filesystem` and `Boost::system` do exist, I'm not sure why the linker can't find the symbols, have you test the latest commit of the main branch .?

**Comment by JafarAbdi** [comment]
This should be fixed in the latest main branch
