### ISSUE TITLE
TF NAN_INPUT: Ignoring transform for child_frame_id "<link_name>" from authority "Authority undetectable" because of a nan value in the transform (-nan -nan -nan) (-nan -nan -nan -nan)

### ISSUE THREAD

**Issue by sachinkum0009** [ros-planning/moveit2#298]
[frames.pdf](https://github.com/ros-planning/moveit2/files/5432489/frames.pdf)
### Description

Overview of your issue here.

The issue is about tf

```bash
TF NAN_INPUT: Ignoring transform for child_frame_id "gripper_link" from authority "Authority undetectable" because of a nan value in the transform (-nan -nan -nan) (-nan -nan -nan -nan)
```

Trying to implement servo_cpp_interface to a custom robot arm of 6 dof

### Your environment
* ROS Distro: [Foxy]
* OS Version: e.g. Ubuntu 20.04
* Source
* main branch

### Backtrace or Console output

![Screenshot from 2020-10-03 20-39-26](https://user-images.githubusercontent.com/19277194/97069607-0a5a7700-15ef-11eb-878f-8b5ae5ba18ce.png)
![Screenshot from 2020-10-24 11-30-15](https://user-images.githubusercontent.com/19277194/97069608-0b8ba400-15ef-11eb-9612-01bc7a78b4c8.png)
![Screenshot from 2020-10-24 11-30-45](https://user-images.githubusercontent.com/19277194/97069610-0cbcd100-15ef-11eb-8873-a198cb3d578c.png)
[log.txt](https://github.com/ros-planning/moveit2/files/5432488/log.txt)

[gist.github.com](https://gist.github.com/sachinkum0009/8931fe3160f5925d89afdbd68608d1fc.js)

**Comment by JafarAbdi** [comment]
I think this's fixed with the main branch, feel free to reopen it if you still see the problem
