### ISSUE TITLE
Select ros2_control commits to be compatible with UR ROS2 package

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#302]
Since ros2_control is under heavy development (see https://docs.google.com/document/d/1818AoYucI2z82awL_-8sAA5pMCV_g_wXCJiM6SQmhSQ/edit?pli=1#) we probably need to select a ros2_control commit and stick with it, for moveit2 and ur2.

I imagine we'll be in a good place to make this selection in about a week.

**Comment by henningkayser** [comment]
We already use fixed commits (see https://github.com/ros-planning/moveit2/blob/main/moveit2.repos), but I would suggest picking a more up-to-date version for ur and we'll bump the ros2 control version here as well

**Comment by AndyZe** [comment]
ros2_control has been released, this is no longer relevant
