### ISSUE TITLE
Ros time and it's differences from ros2 time

### ISSUE THREAD

**Issue by anasarrak** [ros-planning/moveit2#31]
While on the porting procedure, there are different ros::Time / ros::Walltime calls that have to be subtituted by rclcpp time calls. 

The problem is that there is no similar call for ros::Walltime on ros2, I've found that the rclcpp has a member called [WallTimer](http://docs.ros2.org/crystal/api/rclcpp/classrclcpp_1_1WallTimer.html), but it has nothing to do with ros:Walltime.

Right now I'm replacing them with rclcpp::Time, but I would like some input about that, also I would like to know why sometimes Walltime is used instead of Time .

**Comment by wjwwood** [comment]
It's probably an oversight that `rclcpp::WallTime` is not a thing, but you can also just use `std::chrono::system_clock` instead, as `rclcpp::WallTime` would likely just be a thin wrapper around that anyways.
