### ISSUE TITLE
MoveIt Config Redesign - Migrate MSA to ROS 2

### ISSUE THREAD

**Issue by henningkayser** [ros-planning/moveit2#313]
Porting the MSA requires more effort than simply applying the migration steps. With the switch to Python launch files, the new `rclcpp::Parameter` interface and related config changes (dropped XmlRpc support) require non-trivial re-implementation of some parts, including:

1. Initial Migration (#740)
1. Standardized yaml configs and parameter parsing (https://github.com/ros-planning/moveit2/issues/431)
1. New generic launch scripts, available as templates (https://github.com/ros-planning/moveit2/issues/335)
1. Adaption of changed config/launch setups to MSA layout and implementation (https://github.com/ros-planning/moveit2/issues/449)

## Design Ideas

**Config files**
All nodes/classes declare parameters in a standardized way so that it's possible to generate valid config (yaml) files automatically (e.g. `ros2 param dump`), ideally including descriptions and comments. This would allow MSA to generate config files from the actual node implementation. All exceptions should be caught and handled accordingly, parsing and conversion of abstract data types should be handled with proper parameter documentation and runtime messages/warnings. Optionally, node configs include version tags, loading of outdated configs would then result in a deprecation warning.

**Launch files**
MoveIt configs should be static by default and only contain the config (yaml,srdf) files needed to describe the setup configuration. The default launch scripts are not copied into each MoveIt config package, they are only used to initialize a MoveIt setup instance (MoveGroup, MoveItCpp) by reading the config files from a config package. Customization of launch descriptions can be enabled by supporting launch file overrides or exporting/importing of factory functions from the launch scripts. This would allow to keep a standard and reduce redundancy (and maintenance overhead) in launch files. Of course it's up to the devs to copy the whole launch architecture and modify it as needed.

**Comment by DLu** [comment]
# MoveIt Setup Assistant Refactor Proposal

I propose that MSA be reimplemented using pluginlib. Most of the "widgets" would be moved to separate packages and implemented as plugins. The core `moveit_setup_assistant` package would only contain a few key elements.
 * List of available plugins
 * Set of shared data files
 * Functionality for loading some subset of the plugins
 * Framework to populate the GUI (including RViz display)
 * Intro and Outro widgets

The data files need to be shared at the high level because there are multiple configuration steps that operate on the same data file (i.e. the SRDF) and some configuration steps will need to load data from other configuration steps.

The overall control flow might be something like:
 * Show the Initial `SetupScreenWidget` to select the URDF to operate on OR load an existing `moveit_config` package (same as before)
 * With an eye toward #449, ask the user what they want to do.
    * Each of the available plugins could report a hierarchical string describing what that configuration step does. For example, the `VirtualJointsWidget` could report something like `["Configure the SRDF", "Update the Virtual Joints"]` and multiple operations would be grouped under the section "Configure the SRDF"
    * User would then select a subset of the options which would dictate which plugins get loaded.
 * The user would then walk through each of the chosen configuration steps.
    * There needs to be a mechanism for specifying dependencies, so that, for example, you can't specify robot poses until you configure the planning groups.
 * At the end, you are presented with the `ConfigurationFilesWidget` which presents the different shared files that need to be written to.

As much as possible, the GUI logic should be kept separately from the core data-management.

**Comment by v4hn** [comment]
> I propose that MSA be reimplemented using pluginlib.

Reading this from you reminded me of slide 30 [from your 2017 ROSCon talk](https://roscon.ros.org/2017/presentations/ROSCon%202017%20Fundamentals%20of%20Local%20Planning.pdf). :joy:

I would love plugin support for MSA for users to add their own configuration options.
I don't see the merit in "outsourcing" all standard tabs though and would keep them local classes. But, granted, the difference between local class and plugin in the local package is minor.

As you said the defining data structures need to be defined outside the plugins anyway.

Asking what steps to perform later on would be just another technical hurdle for the user.
It's equally possible to always add all plugins/widgets to the list. Maybe invoke them lazily if the user clicks on them.

> As much as possible, the GUI logic should be kept separately from the core data-management.

:+1: It would be great to have cli programs for all functionality, if just to finally write reasonable CI tests for MSA!

**Comment by gavanderhoorn** [comment]
As I don't see it mentioned yet: https://github.com/ros-planning/moveit/pull/1375.

**Comment by henningkayser** [comment]
Hey @DLu I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/moveit-61675936b391800012280f6d/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by cgarry-vs** [comment]
Are you aiming to have this go out with the Humble Hawksbill release?

**Comment by JafarAbdi** [comment]
> Are you aiming to have this go out with the Humble Hawksbill release?

Yes, that's the plan

**Comment by vatanaksoytezer** [comment]
We plan to attempt to merge feature MSA branch very soon after https://github.com/ros-planning/moveit2/pull/1240, and the plan is after some testing next week we will hopefully release Humble with MSA.

**Comment by nlgilbert** [comment]
Any updates on getting MSA in ROS 2? Will we see it in any versions prior to Humble (Foxy or Galactic)?

**Comment by DLu** [comment]
It is in the process of being merged into `main`: https://github.com/ros-planning/moveit2/pull/1254 and will be backported to old releases.

**Comment by jure-no** [comment]
Is there any new information, when will we get MSA for humble? It would really help me a lot

**Comment by jure-no** [comment]
Is this expected to be published in the next 14 days to one month?

**Comment by vatanaksoytezer** [comment]
Don't want to make any promises but, yes hopefully it should be ready in that time interval

**Comment by mikeferguson** [comment]
Branch is merged - kudos to @DLu and @vatanaksoytezer

**Comment by jure-no** [comment]
Really? that is awesome. Where can i get MSA for moveit2 now?

**Comment by vatanaksoytezer** [comment]
@jure-no  You can use the main branch to compile on Humble or Rolling by following the instructions on our webpage, please let us know if you see any issues.

@mikeferguson we can close the ticket, thanks for the heads up!

**Comment by mikeferguson** [comment]
@jure-no I will note, MOST things work with the MSA - but you'll see a few remaining bug tickets for certain more advanced features (and some active PRs) if you search "MSA" in our issue tracker. If you run into any issues, please post an issue (or comment on an existing one if that particular bug is blocking you).
