### ISSUE TITLE
Migrate Python bindings

### ISSUE THREAD

**Issue by henningkayser** [ros-planning/moveit2#314]
Tracking issue to discuss the need and capacity for porting the `py_binding_tools`, `moveit_commander`.

**Comment by rhaschke** [comment]
It's on my todo list (unfortunately, since ages) to migrate python bindings to pybind11 and clean them up in Noetic.
I progressed a lot in MTC on that and hopefully can adapt main MoveIt more easily now.

**Comment by maslovay** [comment]
@rhaschke any news with with migrating py_binding_tools, moveit_commander?

**Comment by WyattAutomation** [comment]
+1 for this enhancement request; critical feature for several use cases I will need it for.  

Would be willing to help test/review if/when this enhancement nears completion.  Thank you for your effort on this, it's definitely appreciated.

**Comment by felixvd** [comment]
Related: https://github.com/ros-planning/moveit/issues/900

**Comment by lorepieri8** [comment]
+1 to see Python fully supported

**Comment by tlpss** [comment]
@rhaschke has there been any update on migrating the python bindings? I might be willing to offer some help as I am really interested in the python bindings, but my experience with Moveit is limited.

**Comment by henningkayser** [comment]
closing in favor of #1279
