### ISSUE TITLE
I want to get goal information from the follow_joint_trajectory action.

### ISSUE THREAD

**Issue by kong2983** [ros-planning/moveit2#319]
I succeeded in running the moveit2 package using the latest ros2_control package.
Packages such as motion planning and fake_joint all run normally.
However, I couldn't find a way to get goal information from follow_joint_trajectory action.
It was confirmed that the status and feedback were returned normally.
By modifying the follow_joint_trajectory_handle.cpp file, it is possible to forcibly receive goal route information.

However, this seems to be wrong. control_msgs::action::FollowJointTrajectory::Goal Is there a good way to get information?

**Comment by vatanaksoytezer** [comment]
This issue seem to gone stale for over a year, thus I am closing, please re-open if you still have the question.
