### ISSUE TITLE
Keeping Isometry3d in ROS2

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit2#32]
A change was made by @rhaschke in ros1/geometry2 that was not forward ported to ros2/geometry2, see https://github.com/ros/geometry2/pull/335.

This change urgently needs to be ported so that there isn't a big regression in the moveit2 codebase as demonstrated here and in the related conversation: https://github.com/ros-planning/moveit2/pull/12#discussion_r258148928

**Comment by vmayoral** [comment]
https://github.com/ros2/geometry2/pull/93 addresses the issue in geometry2. Changes like https://github.com/ros-planning/moveit2/pull/12/commits/94ebbcc191db16d6e3fae760d2d8b8062517d53f should follow.

**Comment by vmayoral** [comment]
Shall we close this @davetcoleman? @mlautman?

**Comment by davetcoleman** [comment]
Let's wait until https://github.com/ros2/geometry2/pull/93 is closed. This should actually auto-close now that I've tagged its dependency on github.

**Comment by anasarrak** [comment]
This issue can be closed, they've merged the changes on https://github.com/ros2/geometry2/pull/90
