### ISSUE TITLE
Migrate moveit_ros_perception to ROS2

### ISSUE THREAD

**Issue by RoboticsYY** [ros-planning/moveit2#327]
- [x] Migrate pointcloud_octomap_updater_plugin to ROS2 (#307)
- [x] Migrate depth_image_octomap_updater_plugin to ROS2 (#354)
- [ ] Enable testing ([link](https://github.com/ros-planning/moveit2/pull/307/files#r552670470))
- [ ] Enable private node ([link](https://github.com/ros-planning/moveit2/pull/307/files#r552671925))

**Comment by henningkayser** [comment]
Closing. Migration is done, remaining test efforts are tracked in https://github.com/ros-planning/moveit2/issues/216
