### ISSUE TITLE
Build conflict in moveit_core `transforms.cpp` with both ROS1/ROS2 exist

### ISSUE THREAD

**Issue by zuxinrui** [ros-planning/moveit2#376]
### Description

I followed the instruction of the Moveit2 tutorial's `build from source`. But when building `moveit_core`, there is a conflict of using reference: tf2_eigen:

error: no matching function for call to ‘transformToEigen(const TransformStamped&)’
  140 |     Eigen::Isometry3d t = tf2::transformToEigen(transform);
      |                                                          ^
In file included from /home/zuxinrui/ws_ros2/src/moveit2/moveit_core/transforms/src/transforms.cpp:39:
/opt/ros/noetic/include/tf2_eigen/tf2_eigen.h:48:20: note: candidate: ‘Eigen::Isometry3d tf2::transformToEigen(const Transform&)’
   48 |  Eigen::Isometry3d transformToEigen(const geometry_msgs::Transform& t) {
      |                    ^~~~~~~~~~~~~~~~
/opt/ros/noetic/include/tf2_eigen/tf2_eigen.h:48:69: note:   no known conversion for argument 1 from ‘const TransformStamped’ {aka ‘const geometry_msgs::msg::TransformStamped_<std::allocator<void> >’} to ‘const Transform&’ {aka ‘const geometry_msgs::Transform_<std::allocator<void> >&’}
   48 |  Eigen::Isometry3d transformToEigen(const geometry_msgs::Transform& t) {
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^

I am building ros2 foxy but it refer to my ROS1 noetic's `tf2-eigen` directory strangely. I think this should be a problem of environment initialization related to setup.bash.

### Your environment
* ROS Distro: [Noetic]
* OS Version: Ubuntu 20.04
* Source or Binary build? Source build
* If binary, which release version?
* If source, which branch? master

### Steps to reproduce
Tell us how to reproduce this issue. Attempt to provide a working demo, perhaps using Docker.

Follow the instruction of the Moveit2 tutorial and in the step:
`colcon build --event-handlers desktop_notification- status- --cmake-args -DCMAKE_BUILD_TYPE=Release
`
### Expected behaviour
Tell us what should happen

It should be successfully built.
### Actual behaviour
Tell us what happens instead

moveit_core failed to build

### Backtrace or Console output

<script src="https://gist.github.com/zuxinrui/ca81f669c0f014ade0895370c2dd71f5.js"></script>

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by JafarAbdi** [comment]
You need to make sure that `CMAKE_PREFIX_PATH` only contains paths for ROS2 workspaces (currently it contains paths for noetic)

To fix this make sure to run `source /opt/ros/foxy/setup.bash` (you may want to run `unset CMAKE_PREFIX_PATH` before sourcing it)
