### ISSUE TITLE
Flaky tests in moveit_servo

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2#397]
### Description

When migrating to GitHub Actions I discovered that two of the moveit_servo tests are flaky.  In that PR I disabled them by commenting out them from the CMakeLists.txt.  This issue is to track fixing those tests.  I'm marking this good-first-issue because it is an isolated task.  However, teasing out why they are flaky might not be trivial.

The tests are:
* unit_test_servo_calcs
* test_servo_pose_tracking

**Comment by NickNair** [comment]
On launching which moveit_servo nodes are these called ?

**Comment by NickNair** [comment]
the Description for unit_test_servo_calcs says - Loads a Servo instance without launching or parameters. Can I get some more description ?
