### ISSUE TITLE
geometric_shapes compile failed and can't load Robot model

### ISSUE THREAD

**Issue by chaos4ros2** [ros-planning/moveit2#411]
### Description

I'm following the instructions to build moveit2 but 1 package failed.（geometric_shapes）
The same problem issue found in the [link](https://github.com/qhull/qhull/issues/78) below but still not fixed.

Ignore it and try to ran MoveItCpp Demo Package by use command 「_ros2 launch run_moveit_cpp run_moveit_cpp.launch.py_」but the RViz GUI didn't launched.

Than I use another terminal to launch rviz by use command「_rviz2 -d ~/ws_moveit2/src/moveit2/moveit_demo_nodes/run_moveit_cpp/launch/run_moveit_cpp.rviz_」,the panda robot's tf flame appeared but urdf model can't show and error is displayed in terminal：
**[INFO] [1617523472.376519700] [moveit_rdf_loader.rdf_loader]: Robot model parameter not found! Did you remap 'robot_description'?
[ERROR] [1617523472.520297400] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Robot model not loaded**

Is this error related to the failed package and how can I fix it?
please help me

### Your environment
* ROS Distro: ROS2 Foxy
* OS Version: Ubuntu 20.04 （wsl2 windsow10）
* Source or Binary build? Source
* If source, which branch? follow this [link](https://moveit.ros.org/install-moveit2/source/) and didn't change anything

### Steps to reproduce
compile in windos10 wsl2

### Expected behaviour
compile success and no rviz2's error 

### Actual behaviour
geometric_shapes compile failed and couldn't load Robot model

**Comment by tylerjw** [comment]
The error about the robot model not being found has nothing to do with the error output from `geometric_shapes`.  Is there more error output than that?

**Comment by chaos4ros2** [comment]
Yes I will show it as detailed as possible.

first,I use  command 「_ros2 launch run_moveit_cpp run_moveit_cpp.launch.py_」
and the message show like below:

_chaos@LAPTOP-CDCTQI88:~/ws_moveit2$ source ~/ws_moveit2/install/setup.bash_
_chaos@LAPTOP-CDCTQI88:~/ws_moveit2$ ros2 launch run_moveit_cpp run_moveit_cpp.launch.py_
**[INFO] [launch]: All log files can be found below /home/chaos/.ros/log/2021-04-06-21-41-50-926321-LAPTOP-CDCTQI88-5800
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [static_transform_publisher-1]: process started with pid [5802]
[INFO] [robot_state_publisher-2]: process started with pid [5804]
[INFO] [rviz2-3]: process started with pid [5806]
[INFO] [run_moveit_cpp-4]: process started with pid [5808]
[INFO] [ros2_control_node-5]: process started with pid [5810]
[INFO] [ros2 run controller_manager spawner.py panda_arm_controller-6]: process started with pid [5812]
[INFO] [ros2 run controller_manager spawner.py joint_state_controller-7]: process started with pid [5814]
[static_transform_publisher-1] [INFO] [1617712911.312092300] [static_transform_publisher]: Spinning until killed publishing transform from 'world' to 'panda_link0'
[robot_state_publisher-2] Parsing robot urdf xml string.
[robot_state_publisher-2] Link panda_link1 had 1 children
[robot_state_publisher-2] Link panda_link2 had 1 children
[robot_state_publisher-2] Link panda_link3 had 1 children
[robot_state_publisher-2] Link panda_link4 had 1 children
[robot_state_publisher-2] Link panda_link5 had 1 children
[robot_state_publisher-2] Link panda_link6 had 1 children
[robot_state_publisher-2] Link panda_link7 had 1 children
[robot_state_publisher-2] Link panda_link8 had 1 children
[robot_state_publisher-2] Link panda_hand had 2 children
[robot_state_publisher-2] Link panda_leftfinger had 0 children
[robot_state_publisher-2] Link panda_rightfinger had 0 children
[robot_state_publisher-2] [INFO] [1617712911.323456400] [robot_state_publisher]: got segment panda_hand
[robot_state_publisher-2] [INFO] [1617712911.323614800] [robot_state_publisher]: got segment panda_leftfinger
[robot_state_publisher-2] [INFO] [1617712911.323641100] [robot_state_publisher]: got segment panda_link0
[robot_state_publisher-2] [INFO] [1617712911.323657900] [robot_state_publisher]: got segment panda_link1
[robot_state_publisher-2] [INFO] [1617712911.323671900] [robot_state_publisher]: got segment panda_link2
[robot_state_publisher-2] [INFO] [1617712911.323685000] [robot_state_publisher]: got segment panda_link3
[robot_state_publisher-2] [INFO] [1617712911.323697900] [robot_state_publisher]: got segment panda_link4
[robot_state_publisher-2] [INFO] [1617712911.323713500] [robot_state_publisher]: got segment panda_link5
[robot_state_publisher-2] [INFO] [1617712911.323730700] [robot_state_publisher]: got segment panda_link6
[robot_state_publisher-2] [INFO] [1617712911.323747200] [robot_state_publisher]: got segment panda_link7
[robot_state_publisher-2] [INFO] [1617712911.323761900] [robot_state_publisher]: got segment panda_link8
[robot_state_publisher-2] [INFO] [1617712911.323775600] [robot_state_publisher]: got segment panda_rightfinger
[run_moveit_cpp-4] [INFO] [1617712911.339648900] [moveit_cpp_demo]: Initialize node
[ros2_control_node-5] [INFO] [1617712911.343830900] [controller_manager]: update rate is 100 Hz
[rviz2-3] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-chaos'
[rviz2-3] [INFO] [1617712911.716335800] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-3] [INFO] [1617712911.716670300] [rviz2]: OpenGl version: 3.1 (GLSL 1.4)
[rviz2-3] [INFO] [1617712911.766087500] [rviz2]: Stereo is NOT SUPPORTED
[ros2_control_node-5] [INFO] [1617712911.834757000] [controller_manager]: Loading controller 'joint_state_controller'
[ros2 run controller_manager spawner.py panda_arm_controller-6] [INFO] [1617712911.838809300] [spawner_panda_arm_controller]: Waiting for /controller_manager services
[ros2 run controller_manager spawner.py joint_state_controller-7] [INFO] [1617712911.851489700] [spawner_joint_state_controller]: Loaded joint_state_controller
[ros2_control_node-5] [INFO] [1617712911.854822500] [controller_manager]: Configuring controller 'joint_state_controller'
[ros2 run controller_manager spawner.py joint_state_controller-7] [INFO] [1617712911.871518200] [spawner_joint_state_controller]: Configured and started joint_state_controller
[rviz2-3] Parsing robot urdf xml string.
[rviz2-3] [INFO] [1617712911.922562500] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.001968 seconds
[rviz2-3] [INFO] [1617712911.922770800] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[INFO] [ros2 run controller_manager spawner.py joint_state_controller-7]: process has finished cleanly [pid 5814]
[ros2_control_node-5] [INFO] [1617712912.044993900] [controller_manager]: Loading controller 'panda_arm_controller'
[ros2 run controller_manager spawner.py panda_arm_controller-6] [INFO] [1617712912.064005000] [spawner_panda_arm_controller]: Loaded panda_arm_controller
[ros2_control_node-5] [INFO] [1617712912.066913500] [controller_manager]: Configuring controller 'panda_arm_controller'
[ros2_control_node-5] [INFO] [1617712912.068224200] [panda_arm_controller]: Controller state will be published at 50Hz.
[ros2_control_node-5] [INFO] [1617712912.069107600] [panda_arm_controller]: Action status changes will be monitored at 20Hz.
[ros2 run controller_manager spawner.py panda_arm_controller-6] [INFO] [1617712912.084344700] [spawner_panda_arm_controller]: Configured and started panda_arm_controller
[INFO] [ros2 run controller_manager spawner.py panda_arm_controller-6]: process has finished cleanly [pid 5812]
[rviz2-3] Parsing robot urdf xml string.
[rviz2-3] [INFO] [1617712912.916208500] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.0011776 seconds
[rviz2-3] [INFO] [1617712912.916328900] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[rviz2-3] [WARN] [1617712912.934613700] [moveit_ros.robot_model_loader]: No kinematics plugins defined. Fill and load kinematics.yaml!
[rviz2-3] [INFO] [1617712913.339854900] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[rviz2-3] [INFO] [1617712913.341041300] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/moveit_cpp/publish_planning_scene'
[run_moveit_cpp-4] [INFO] [1617712916.387539300] [moveit_cpp_demo]: Initialize MoveItCpp
[run_moveit_cpp-4] Parsing robot urdf xml string.
[run_moveit_cpp-4] [INFO] [1617712916.393944500] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.0016346 seconds
[run_moveit_cpp-4] [INFO] [1617712916.394081900] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[run_moveit_cpp-4] Link panda_link1 had 1 children
[run_moveit_cpp-4] Link panda_link2 had 1 children
[run_moveit_cpp-4] Link panda_link3 had 1 children
[run_moveit_cpp-4] Link panda_link4 had 1 children
[run_moveit_cpp-4] Link panda_link5 had 1 children
[run_moveit_cpp-4] Link panda_link6 had 1 children
[run_moveit_cpp-4] Link panda_link7 had 1 children
[run_moveit_cpp-4] Link panda_link8 had 1 children
[run_moveit_cpp-4] Link panda_hand had 2 children
[run_moveit_cpp-4] Link panda_leftfinger had 0 children
[run_moveit_cpp-4] Link panda_rightfinger had 0 children
[run_moveit_cpp-4] [INFO] [1617712916.433776700] [moveit.ros_planning_interface.moveit_cpp]: Listening to '/joint_states' for joint states
[run_moveit_cpp-4] [INFO] [1617712916.435005000] [moveit_ros.current_state_monitor]: Listening to joint states on topic '/joint_states'
[run_moveit_cpp-4] [INFO] [1617712916.435921400] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/moveit_cpp/planning_scene_monitor' for attached collision objects
[run_moveit_cpp-4] [INFO] [1617712916.437028400] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Publishing maintained planning scene on '/moveit_cpp/publish_planning_scene'
[run_moveit_cpp-4] [INFO] [1617712916.437275000] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[run_moveit_cpp-4] [INFO] [1617712916.437757300] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/moveit_cpp/monitored_planning_scene'
[run_moveit_cpp-4] [INFO] [1617712916.437783300] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'ompl'
[run_moveit_cpp-4] [INFO] [1617712916.481142000] [moveit.ros_planning.planning_pipeline]: Using planning interface 'OMPL'
[run_moveit_cpp-4] [INFO] [1617712916.488023400] [moveit_ros.fix_workspace_bounds]: Param 'default_workspace_bounds' was not set. Using default value: 10.000000
[run_moveit_cpp-4] [INFO] [1617712916.488203400] [moveit_ros.fix_start_state_bounds]: Param 'ompl.start_state_max_bounds_error' was set to 0.100000
[run_moveit_cpp-4] [INFO] [1617712916.488285300] [moveit_ros.fix_start_state_bounds]: Param 'ompl.start_state_max_dt' was not set. Using default value: 0.500000
[run_moveit_cpp-4] [INFO] [1617712916.488328800] [moveit_ros.fix_start_state_collision]: Param 'start_state_max_dt' was not set. Using default value: 0.500000
[run_moveit_cpp-4] [INFO] [1617712916.488339300] [moveit_ros.fix_start_state_collision]: Param 'jiggle_fraction' was not set. Using default value: 0.020000
[run_moveit_cpp-4] [INFO] [1617712916.488352700] [moveit_ros.fix_start_state_collision]: Param 'max_sampling_attempts' was not set. Using default value: 0.000000,
[run_moveit_cpp-4] [INFO] [1617712916.488374200] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Add Time Optimal Parameterization'
[run_moveit_cpp-4] [INFO] [1617712916.488390300] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
[run_moveit_cpp-4] [INFO] [1617712916.488396700] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
[run_moveit_cpp-4] [INFO] [1617712916.488402000] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
[run_moveit_cpp-4] [INFO] [1617712916.488407100] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
[run_moveit_cpp-4] [WARN] [1617712916.493900600] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[run_moveit_cpp-4] [INFO] [1617712916.557579300] [moveit.plugins.moveit_simple_controller_manager]: Added FollowJointTrajectory controller for panda_arm_controller
[run_moveit_cpp-4] [INFO] [1617712916.557822600] [moveit.plugins.moveit_simple_controller_manager]: Returned 1 controllers in list
[run_moveit_cpp-4] [INFO] [1617712916.558923400] [moveit_ros.trajectory_execution_manager]: Trajectory execution is not managing controllers
[run_moveit_cpp-4] [INFO] [1617712916.561381400] [moveit_cpp_demo]: Initialize PlanningComponent
[run_moveit_cpp-4] [INFO] [1617712919.561751700] [moveit_cpp_demo]: Set goal
[run_moveit_cpp-4] [INFO] [1617712919.561909700] [moveit_cpp_demo]: Plan to goal
[run_moveit_cpp-4] [INFO] [1617712919.563358200] [moveit.ompl_planning.model_based_planning_context]: Planner configuration 'panda_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[run_moveit_cpp-4] [INFO] [1617712919.564544100] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[run_moveit_cpp-4] [INFO] [1617712919.564724400] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[run_moveit_cpp-4] [INFO] [1617712919.564796000] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[run_moveit_cpp-4] [INFO] [1617712919.564854900] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[run_moveit_cpp-4] [INFO] [1617712919.575757100] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - panda_arm/panda_arm: Created 4 states (2 start + 2 goal)
[run_moveit_cpp-4] [INFO] [1617712919.575878900] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - panda_arm/panda_arm: Created 4 states (2 start + 2 goal)
[run_moveit_cpp-4] [INFO] [1617712919.576930200] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - panda_arm/panda_arm: Created 6 states (4 start + 2 goal)
[run_moveit_cpp-4] [INFO] [1617712919.577000300] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - panda_arm/panda_arm: Created 6 states (4 start + 2 goal)
[run_moveit_cpp-4] [INFO] [1617712919.577171400] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/tools/multiplan/src/ParallelPlan.cpp:135 - ParallelPlan::solve(): Solution found by one or more threads in 0.013392 seconds
[run_moveit_cpp-4] [INFO] [1617712919.577385500] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[run_moveit_cpp-4] [INFO] [1617712919.577505700] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[run_moveit_cpp-4] [INFO] [1617712919.577544800] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[run_moveit_cpp-4] [INFO] [1617712919.577618400] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[run_moveit_cpp-4] [INFO] [1617712919.578424100] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - panda_arm/panda_arm: Created 5 states (2 start + 3 goal)
[run_moveit_cpp-4] [INFO] [1617712919.578494500] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - panda_arm/panda_arm: Created 5 states (3 start + 2 goal)
[run_moveit_cpp-4] [INFO] [1617712919.578682700] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - panda_arm/panda_arm: Created 5 states (2 start + 3 goal)
[run_moveit_cpp-4] [INFO] [1617712919.578793800] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - panda_arm/panda_arm: Created 5 states (2 start + 3 goal)
[run_moveit_cpp-4] [INFO] [1617712919.578963500] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/tools/multiplan/src/ParallelPlan.cpp:135 - ParallelPlan::solve(): Solution found by one or more threads in 0.001698 seconds
[run_moveit_cpp-4] [INFO] [1617712919.579179700] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[run_moveit_cpp-4] [INFO] [1617712919.579292700] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[run_moveit_cpp-4] [INFO] [1617712919.579989200] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - panda_arm/panda_arm: Created 4 states (2 start + 2 goal)
[run_moveit_cpp-4] [INFO] [1617712919.580206400] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - panda_arm/panda_arm: Created 5 states (2 start + 3 goal)
[run_moveit_cpp-4] [INFO] [1617712919.586058900] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/tools/multiplan/src/ParallelPlan.cpp:135 - ParallelPlan::solve(): Solution found by one or more threads in 0.006997 seconds
[run_moveit_cpp-4] [INFO] [1617712919.589368800] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/src/SimpleSetup.cpp:179 - SimpleSetup: Path simplification took 0.003129 seconds and changed from 3 to 3 states
[run_moveit_cpp-4] [ERROR] [1617712919.592907000] [moveit.ros_planning.planning_pipeline]: Computed path is not valid. Invalid states at index locations: [16 ] out of 34. Explanations follow in command line. Contacts are published on /display_contacts
[run_moveit_cpp-4] [INFO] [1617712919.593018100] [moveit_collision_detection_fcl.collision_common]: Found a contact between 'box' (type 'Object') and 'panda_leftfinger' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
[run_moveit_cpp-4] [INFO] [1617712919.593027200] [moveit_collision_detection_fcl.collision_common]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[run_moveit_cpp-4] [ERROR] [1617712919.593352100] [moveit.ros_planning.planning_pipeline]: Completed listing of explanations for invalid states.
[run_moveit_cpp-4] [ERROR] [1617712919.593835400] [moveit.ros_planning_interface.planning_component]: Could not compute plan successfully
[run_moveit_cpp-4] [INFO] [1617712919.593897500] [moveit.ros_planning_interface.planning_component]: Deleting PlanningComponent 'panda_arm'**

![rviz1](https://user-images.githubusercontent.com/80691913/113717983-2712e300-9727-11eb-9b87-4796f099a499.png)

you can see rviz2 node launched and added in windows task bar. But when I mouse over it, nothing happened just show a small white screen.

Then, I use command 「_rviz2 -d ~/ws_moveit2/src/moveit2/moveit_demo_nodes/run_moveit_cpp/launch/run_moveit_cpp.rviz_」in another teminal and rviz2 node launched twice and nothing happened too but show error message below with red word.
![rviz2](https://user-images.githubusercontent.com/80691913/113719346-7a396580-9728-11eb-891d-48e282b33c44.png)

Finally,I just use command 「_rviz2_」and this time RViz GUI luanched! I add the plugin manually and RobotModel is not loaded too. moveit tool also not works.

![rviz3](https://user-images.githubusercontent.com/80691913/113720361-8245d500-9729-11eb-80e6-e622f67cafd6.png)

that's all what happened.

**Comment by tylerjw** [comment]
Do you mind quoting the code block with three back ticks or using the code button in the wsiwyg edditor to do it so the block of errors is easier to read?

**Comment by tylerjw** [comment]
So it seems that there is some issue with launching rviz.  I don't see any errors about rviz which is odd.  Perhaps we are now missing some needed argument.  I don't have a windows machine to test this on, I'm sorry.

The errors you are getting when you launch rviz with that config instead of trying to do it through the demo is that you are just opening rviz with a config file (which specifies things like what topics it should listen to) and you are not starting the nodes.  If you open rviz using that command and then try to run the demo separately does that work?

**Comment by chaos4ros2** [comment]
I try two ways

**1.** 
step1: terminal_1 _「ros2 launch run_moveit_cpp run_moveit_cpp.launch.py」_
step2: terminal_2 _「ros2 launch run_moveit_cpp run_moveit_cpp.launch.py」_

result: both rviz2 can't launched.

step1

![rviz4](https://user-images.githubusercontent.com/80691913/113779939-682be700-9769-11eb-8361-ece55497ff89.png)

step2
![rviz5](https://user-images.githubusercontent.com/80691913/113779949-6b26d780-9769-11eb-8c14-c180003d9ca9.png)


**2.**
step1: terminal_1 _「rviz2」_
step2: terminal_2 _「ros2 launch run_moveit_cpp run_moveit_cpp.launch.py」_
step3: add plugins in rviz2

result: rviz launched but show error

step1
![rviz6](https://user-images.githubusercontent.com/80691913/113780205-da9cc700-9769-11eb-949a-a2093e77db4e.png)

step2
![rviz7](https://user-images.githubusercontent.com/80691913/113780229-e25c6b80-9769-11eb-8174-8c959b94d02b.png)

**Comment by chaos4ros2** [comment]
> 
> 
> So it seems that there is some issue with launching rviz. I don't see any errors about rviz which is odd. Perhaps we are now missing some needed argument. I don't have a windows machine to test this on, I'm sorry.
> 
> The errors you are getting when you launch rviz with that config instead of trying to do it through the demo is that you are just opening rviz with a config file (which specifies things like what topics it should listen to) and you are not starting the nodes. If you open rviz using that command and then try to run the demo separately does that work?

123

**Comment by chaos4ros2** [comment]
> 
> 
> Do you mind quoting the code block with three back ticks or using the code button in the wsiwyg edditor to do it so the block of errors is easier to read?

I am sorry I don't know how to use wsiwyg edditor but I turn code block to 「code」mode and add add line break.
Is it easier to read?

**Comment by tylerjw** [comment]
What I meant about the code blocks was to put this before and after a code block:

\`\`\`

**Comment by tylerjw** [comment]
@JafarAbdi @henningkayser have either of you seen this (and do you have a windows machine configured to easily try to reproduce this)?  I don't have a windows machine to test on and this does work for me on ubuntu.

**Comment by chaos4ros2** [comment]
> 
> 
> What I meant about the code blocks was to put this before and after a code block:
> 
> ```

got it, I will do this next time.

**Comment by chaos4ros2** [comment]
> 
> 
> What I meant about the code blocks was to put this before and after a code block:
> 
> ```


Thank you for your advice. I fixed it.

**Comment by JafarAbdi** [comment]
@chaos4ros2 This's fixed, right .? closing for now

**Comment by chaos4ros2** [comment]
I apologize for leaving this issue unresolved. I will try it later and reopen it if the problem still exists.
