### ISSUE TITLE
The run_move_group demo has the same problem like run_moveit_cpp demo

### ISSUE THREAD

**Issue by chaos4ros2** [ros-planning/moveit2#415]
Description

Face a error when execute run_move_group demo's launch file
ros2 luanch run_move_group run_movegroup_interface.launch.py
(see the capture below)

Finally find a solution in another issue

> The MoveIt cpp demo currently fails for me, any ideas?
> 
> `ros2 launch run_moveit_cpp run_moveit_cpp.launch.py`
> 
> `future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:271> exception=SubstitutionFailure("package 'run_moveit_cpp' found at '/home/andy/ws_schilling/install/run_moveit_cpp', but libexec directory '/home/andy/ws_schilling/install/run_moveit_cpp/lib/run_moveit_cpp' does not exist")>

Replace this [line](https://github.com/ros-planning/moveit2/blob/main/moveit_demo_nodes/run_moveit_cpp/CMakeLists.txt#L33) with `RUNTIME DESTINATION lib/${PROJECT_NAME}`

_Originally posted by @JafarAbdi in https://github.com/ros-planning/moveit2/issues/361#issuecomment-804996764_

fix this problem by JafarAbdi's advices
please reflect on repository.

![Screenshot from 2021-04-12 21-45-50](https://user-images.githubusercontent.com/80691913/114396886-0cce7e80-9bd9-11eb-8525-0ca7b12cfdb5.png)

### Your environment
* ROS Distro: ROS2 Foxy
* OS Version: Ubuntu 20.04 
* Source or Binary build? Source
* If source, which branch?  latest main

**Comment by JafarAbdi** [comment]
Fixed by https://github.com/ros-planning/moveit2/pull/418
