### ISSUE TITLE
Moveit2 should use move_group namespace

### ISSUE THREAD

**Issue by vatanaksoytezer** [ros-planning/moveit2#417]
### Description

move_group namespace is not used in moveit2 but rviz2 defaults to it when opening up MotionPlanning.

### Your environment
* ROS Distro: Foxy
* Ubuntu 20.04
* Source Build from master

### Steps to reproduce
Launch an empty rviz instance and run_move_group.demo.launch.py. Then add MotionPlanning to the rviz

### Expected behaviour
MotionPlanning topics should be published including move_group namespace.
### Actual behaviour
MotionPlanning topics does not currently include move_group, topics are published without move_group namespace.

**Comment by JafarAbdi** [comment]
Closed by https://github.com/ros-planning/moveit2/pull/420
