### ISSUE TITLE
Motion planning cannot avoid Octomap in planning scene

### ISSUE THREAD

**Issue by PrakarnJ** [ros-planning/moveit2#444]
### Description
I am working on robot motion planning with perception from point cloud topic (3d camera). I found that when I planned robot path, the robot cannot avoid the collision in planning scene as shown in Figure ![1](https://media.giphy.com/media/1Zpr9iZJ5JtrevjaUl/giphy.gif).

I tried to solve this problem and found that one of the solution is it need to add something to planning scene using Scene objects tab UI and push Publish button as shown in Figure ![Screenshot from 2021-04-28 20-49-43](https://user-images.githubusercontent.com/31307798/116421532-20304980-a869-11eb-83de-efdb25b10e91.jpg)

After that I planned robot path again and you can see robot can avoid the obstacle 
![3](https://media.giphy.com/media/AL9p2sgD0iPethJTOp/giphy.gif).

Do anyone have the way to solve this problem or the way to check this issue?

### Your environment
* ROS Distro: Foxy
* OS Version: Ubuntu 20.04

**Comment by swilcock0** [comment]
This looks like #407 and #429

**Comment by henningkayser** [comment]
This doesn't look like #407 to me, but it might really be related to #429 which also looks like planning scene updates not being synced properly. I'll check if there is something odd going on, collision checking working after the manual update is very suspicious.

**Comment by swilcock0** [comment]
@henningkayser the manual update thing is the same with #407

**Comment by PrakarnJ** [comment]
@JafarAbdi Yeah It can fixed.
