### ISSUE TITLE
Race condition between launching ros2_control and Servo demo

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#450]
Start one of the Servo demos like this:

`ros2 launch moveit_servo servo_cpp_interface_demo.launch.py`

`ros2 control list_controllers`

You will likely see that `panda_arm_controller` hasn't finished loading. It's in state `finalized` when it should be in state `active`.

We saw the same issue when creating the UR driver and with some other work as well. As a short-term fix, we can split the large launch file into 2 separate launch files and launch with a pause in-between (e.g. `panda_controllers.launch` and `panda_servo.launch`).

We might be able to add some type of wait condition in the launch file (new ROS2 feature?).

I don't know what the root cause is.

**Comment by destogl** [comment]
Is this maybe solved by ros-controls/ros2_control#403
