### ISSUE TITLE
Build error - Package failed : joint_state_broadcaster

### ISSUE THREAD

**Issue by ctruillet** [ros-planning/moveit2#462]
### Description
Cannot build successfully.

### Your environment
* ROS Distro: Foxy
* OS Version: e.g. Ubuntu 20.04 (WSL2)
* Source build

### Steps to reproduce
Follow build instructions (https://moveit.ros.org/install-moveit2/source/) and type:
`colcon build --event-handlers desktop_notification- status- --cmake-args -DCMAKE_BUILD_TYPE=Release`

### Backtrace or Console output
https://gist.github.com/ctruillet/1e781be096ec720a9b045317cc266406

**Comment by korosava** [comment]
Similar [issue](https://github.com/ros-controls/ros2_controllers/issues/203), closed in the ros2_controllers.
