### ISSUE TITLE
Re-enable Bullet, finalize Migration & Tests

### ISSUE THREAD

**Issue by henningkayser** [ros-planning/moveit2#473]
Bullet is still [disabled](https://github.com/ros-planning/moveit2/blob/main/moveit_core/CMakeLists.txt#L180) at this point even though the port has been completed with #322. We should remove the `BULLET_ENABLE` flag by default and always compile it. I'm open to support a build flag that allows configuring what collision environment should be compiled. Things to consider:

* Should we switch to Bullet as default plugin instead of FCL?
* Do we want to move bullet + fcl into a separate package `moveit_collision_detection_plugins` for faster compile times (`moveit_core` is a bottle-neck for multi-core systems)

**Comment by AndyZe** [comment]
I don't think Bullet is ready for prime time yet.

- Seg fault issue:  https://github.com/ros-planning/moveit/issues/2485

- Memory leak issue?  https://github.com/ros-planning/moveit_task_constructor/issues/232

- Also, I haven't personally seen any performance improvement.
