### ISSUE TITLE
trajectory_event_publisher_ in MoveGroupInterface seems redundant

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#507]
In move_group_interface.cpp, there is a `move_action_client_` and a `trajectory_event_publisher_`. It's not clear to me why we have both. The `trajectory_event_publisher_` is used to interrupt trajectories but nothing else. Shouldn't the `move_action_client_` be able to cancel trajectories too?

(The discussion started [here](https://github.com/ros-planning/moveit2/pull/506#issuecomment-863531348).)

**Comment by henningkayser** [comment]
The `trajectory_event_publisher_` allows stopping trajectories when using `asyncExecute()` or `asyncMove()`. I don't think it's redundant. However, it might be possible to implement the async calls by storing the active goal and future and using that one to terminate the action call. This would require quite some refactoring and testing, though.
