### ISSUE TITLE
Basic tutorial doesn't work

### ISSUE THREAD

**Issue by nkalupahana** [ros-planning/moveit2#522]
### Description

With the latest `moveit2` changes (42efad9), our team's MoveIt code suddenly stopped working. To see if it was an issue with our configuration, we tried the tutorials as well -- but they also seem to be broken. See "Steps to reproduce" for more.

### Your environment
* ROS Distro: Foxy
* OS Version: Ubuntu 20
* Source or Binary build? Source (42efad9)

### Steps to reproduce
- I created an empty Ubuntu 20 VM to start.
- [Install `ros-foxy-desktop`](https://docs.ros.org/en/foxy/Installation/Ubuntu-Install-Debians.html)
- [Follow the getting started instructions to install MoveIt2.](http://moveit2_tutorials.picknik.ai/doc/getting_started/getting_started.html)
- Run the MoveIt2 quickstart: `ros2 launch moveit2_tutorials demo.launch.py`

### Expected behaviour
You should get a screen that looks something like this (this is from my main Ubuntu VM, which has MoveIt2 at `a7d7798181cafd6a4e4614aeb0ab7b03e20aa370`:
![Working](https://cdn.discordapp.com/attachments/783194785975369738/859602517321842688/Screen_Shot_2021-06-29_at_6.13.26_PM.png)

### Actual behaviour
Instead, you get this:
![Not Working 1](https://cdn.discordapp.com/attachments/783194785975369738/859602341589680128/Screen_Shot_2021-06-29_at_5.59.56_PM.png)
In the "Context" tab of the MotionPlanning RViz plugin:
![Not Working 2](https://cdn.discordapp.com/attachments/783194785975369738/859602351462809621/Screen_Shot_2021-06-29_at_6.00.02_PM.png)

### Backtrace or Console output
Tutorial launch logs: https://gist.github.com/nkalupahana/09af17aa7f242bc73be5bd8495a7add5
My team's code launch logs: https://gist.github.com/nkalupahana/274d59bdaa42636109c00992cb124903
- Both the tutorial and my team's code work perfectly on MoveIt2 at `a7d7798`.

This is a serious issue for anyone getting started for MoveIt, since the basic tutorials don't work -- and considering my team's code has now stopped working, I think it's a pretty big issue for all users of MoveIt2.

I've now tested this on two clean Ubuntu VMs, and the issue persists -- this is a significant regression, especially for the Galactic release.

**Comment by nkalupahana** [comment]
I've verified this with my old MoveIt2 installation and the latest build of `moveit2_tutorials` (tutorials still work) -- so this seems to be a problem with MoveIt itself and not a quirk of the tutorials. @henningkayser I'm pinging you on this directly because I believe this is a serious regression that should be addressed quickly, especially with Galactic release coming up. Hope that's okay :) and I'm open to provide additional testing details on anything.

**Comment by JafarAbdi** [comment]
@nkalupahana Do you mind testing https://github.com/ros-planning/moveit2/pull/524 and see if it fixes the problem for you .?

**Comment by nkalupahana** [comment]
@JafarAbdi could you reopen this issue? This PR doesn't fix the problem -- I have the exact same issue. Y'all might want to run tutorials on `main` right now and see what happens for yourself. I'd be happy to test anything out too, my build machine is just somewhat slow.

https://gist.github.com/nkalupahana/08a294ad16dec6233c914910cf07c2f8

**Comment by vatanaksoytezer** [comment]
@nkalupahana I just tested the tutorials and moveit2 (and all other upstreams) on main and can't seem to reproduce on Foxy. Do you mind cleaning your workspace, updating all the deps (by pulling and apt-get update / upgrade) and trying again and let us know if the issue persists?

**Comment by JafarAbdi** [comment]
> @JafarAbdi could you reopen this issue? This PR doesn't fix the problem -- I have the exact same issue. Y'all might want to run tutorials on `main` right now and see what happens for yourself. I'd be happy to test anything out too, my build machine is just somewhat slow.
> 
> https://gist.github.com/nkalupahana/08a294ad16dec6233c914910cf07c2f8

@nkalupahana Do you mind trying to start the `panda_hand_controller` controller  https://github.com/ros-planning/moveit2_tutorials/pull/95#issuecomment-871364195

**Comment by nkalupahana** [comment]
I pulled up a blank VM and it looks like it's all working now -- not sure what was up with that :) #524 fixed it!
