### ISSUE TITLE
Laptop hangs after building 42/56 files

### ISSUE THREAD

**Issue by sharath-matada** [ros-planning/moveit2#538]
Hi,
I'm having building moveit2 on ROS foxy from source. My laptop repeatedly hangs after building 42/56 files.
Any help would be appreciated
I've been following the instructions in the link below
http://moveit2_tutorials.picknik.ai/doc/getting_started/getting_started.html

**Comment by JafarAbdi** [comment]
This means your PC run out of RAM+SWAP memory, you could fix it by either

1- Lower the number of parallel packages to build & number of threads per package 
```
MAKEFLAGS=-jNUMBER1 colcon build --parallel-workers=NUMBER2 --event-handlers desktop_notification- status- --cmake-args -DCMAKE_BUILD_TYPE=Release
``` 
where NUMBER1 is the max number of threads per package and NUMBER2 is the max number of parallel packages to build together
2- Or increase the swap memory size

You could see the number of threads for your PC by calling `nproc`
