### ISSUE TITLE
Remove "__has_includes" once we branch off for Galactic

### ISSUE THREAD

**Issue by vatanaksoytezer** [ros-planning/moveit2#618]
In #598 We decided to use C++ 17's new `__has_includes` feature to work around the deprecation problems to support both Galactic and Rolling from the main branch. When we branch off for Galactic, the includes should be fixed for both main and Galactic branches.

**Comment by JafarAbdi** [comment]
https://github.com/ros-planning/moveit_task_constructor/tree/ros2 has multiple occurrences, too
