### ISSUE TITLE
moveit_setup_assistant ros2 support

### ISSUE THREAD

**Issue by SalahSoliman** [ros-planning/moveit2#626]
I have checked all the branches for ros2 support for moveit_setup_assistant and I see that they're all depending on catkin, is it something I don't understand or it's still not updated?

**Comment by vatanaksoytezer** [comment]
Hey @SalahSoliman, thanks for the issue! MSA is not ported to MoveIt 2 and ROS 2 yet. We are working on redesigning and porting it. See https://github.com/ros-planning/moveit2/issues/449 for some design discussions.

**Comment by SalahSoliman** [comment]
@vatanaksoytezer thanks for you quick reply!
Do you have any suggestion for a work around until this part's done? also please lmk if I can help!

**Comment by vatanaksoytezer** [comment]
@SalahSoliman your best quick bet would be just using the ROS 1 (moveit) MSA for now and edit the launch files that you need manually to fit MoveIt 2 and ROS 2.

**Comment by vatanaksoytezer** [comment]
@SalahSoliman I am closing this issue for now but feel free to ask questions open discussions under the relevant issues or open a new one (or re-open this) if you need.
