### ISSUE TITLE
Planning Scene is missing TF frames

### ISSUE THREAD

**Issue by schornakj** [ros-planning/moveit2#646]
### Description

I think there's a regression in #310 that prevents the planning scene from tracking frames that are published to TF but aren't associated with links in the URDF.

### Your environment
* Rolling
* Ubuntu 20.04
* Source build, `main` branch at [974a7a174](https://github.com/ros-planning/moveit2/commit/974a7a1749afa9f8d57254b052056f3fe0c241d5).

### Steps to reproduce
- `ros2 launch run_move_group run_move_group.launch.py`
- Create a node with a TF publisher and publish "world" to "test_frame".
- `ros2 service call /get_planning_scene moveit_msgs/srv/GetPlanningScene '{}'`

### Expected behaviour
Planning scene should contain info about a transform from "world" to "test_frame".

### Actual behaviour
After #310, the planning scene service response does not contain info about this transform. A practical result of this is that MoveIt Task Constructor's `GeneratePose` stages fail while finding IK solutions for named target poses published through TF.

**Comment by jrgnicho** [comment]
I think I'm getting errors related to this issue.  I basically run the move_group node with the *occupancy_map_updater* expecting to see the octomap in rviz but no octomap is shown and in the terminal I get the following error messages:
```
Do not call canTransform or lookupTransform with a timeout unless you are using another thread for populating data. Without a dedicated thread it will always timeout.  If you have a separate thread servicing tf messages, call setUsingDedicatedThread(true) on your Buffer instance.
[move_group-1] [ERROR] [1630597665.236855007] [tf2_buffer]: Do not call canTransform or lookupTransform with a timeout unless you are using another thread for populating data. Without a dedicated thread it will always timeout.  If you have a separate thread servicing tf messages, call setUsingDedicatedThread(true) on your Buffer instance.
[move_group-1] [ERROR] [1630597665.236945719] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Transform error: "world_frame" passed to lookupTransform argument target_frame does not exist. 
[move_group-1] [ERROR] [1630597665.236971975] [moveit.ros.occupancy_map_updater]: Transform cache was not updated. Self-filtering may fail. If transforms were not available yet, consider setting robot_description_planning/shape_transform_cache_lookup_wait_time to wait longer for transforms
```
