### ISSUE TITLE
Colcon build Error: ControllerInterface has no member named 'get_state'

### ISSUE THREAD

**Issue by NebuDa** [ros-planning/moveit2#668]
### Description
Have tried to install Moveit2 like https://moveit.ros.org/install-moveit2/source/

Got stuck on 
`colcon build --event-handlers desktop_notification- status- --cmake-args -DCMAKE_BUILD_TYPE=Release`

### Your environment
* ROS Distro: Foxy
* OS Version:  Ubuntu 20.04 LTS
* ROS2 Debians / Moveit2 source Foxy

### Steps to reproduce
Just follow the installation instructions in the link above.

### Expected behaviour
clean build

### Actual behaviour
Build Error on controller_manager

I have changed all **get_state** in controller_manager.cpp and test_load_controller.cpp to **get_current_state**.
Hope that breaks nothing. Any mentions about it? After that I can build with colcon.

### Backtrace or Console output

```
Starting >>> controller_manager
--- stderr: controller_manager
/home/flo/ws_moveit2/src/ros2_control/controller_manager/src/controller_manager.cpp: In function ‘bool controller_manager::is_controller_inactive(const controller_interface::ControllerInterface&)’:
/home/flo/ws_moveit2/src/ros2_control/controller_manager/src/controller_manager.cpp:34:21: error: ‘const class controller_interface::ControllerInterface’ has no member named ‘get_state’
   34 |   return controller.get_state().id() == lifecycle_msgs::msg::State::PRIMARY_STATE_INACTIVE;
      |                     ^~~~~~~~~
make[2]: *** [CMakeFiles/controller_manager.dir/build.make:63: CMakeFiles/controller_manager.dir/src/controller_manager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:193: CMakeFiles/controller_manager.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:141: all] Error 2
---
Failed   <<< controller_manager [22.5s, exited with code 2]
```

**Comment by JafarAbdi** [comment]
This's an issue in the ros2_control repo, please open an issue there https://github.com/ros-controls/ros2_control/
