### ISSUE TITLE
Discussion: Use mergify for main -> foxy backports?

### ISSUE THREAD

**Issue by vatanaksoytezer** [ros-planning/moveit2#669]
Recently I came accross [Mergify](https://mergify.io/) in https://github.com/ros2/rcpputils/pull/133. Mergify is a nice Github bot that we can use to backport our PRs from main to foxy, which happens to be free for open source projects. As you may have seen from the PR above, you just put a comment to backport and it opens up the new PR for you!

Let me know if people think that is a good idea or not? (Tagging @rhaschke, @henningkayser, @v4hn  and @tylerjw for discussions but as always appreciate any comments)

 I imagine we can also use this for main->noetic->melodic ports as well in MoveIt if needed.

**Comment by henningkayser** [comment]
I like the idea! As discussed off-line we're thinking about a more light-weight approach like [GHA Backporting](https://github.com/marketplace/actions/backporting) (based on labels) or similar.
