### ISSUE TITLE
Removing `source` entry / dev job from ROS 2 buildfarm

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-planning/moveit2#691]
Would it be an idea to remove the `source` job from the ROS 2 buildfarm for the time being?

We already have CI here via GHA and the builds have been failing / unstable for at least 4 months now if not longer.

They're either timing out or failing due to something which doesn't come up on the GHA builds.

In addition to avoiding email spam, we would also save OR a couple of compute-dollars.

I'm talking about these entries:

 - in [foxy/distribution.yaml](https://github.com/ros/rosdistro/blob/9ac5f6c335336cac377c102bb48554bef9f54f87/foxy/distribution.yaml#L2058-L2061)
 - in [groovy/distribution.yaml](https://github.com/ros/rosdistro/blob/9ac5f6c335336cac377c102bb48554bef9f54f87/galactic/distribution.yaml#L1624-L1627), and
 - in [rolling/distribution.yaml](https://github.com/ros/rosdistro/blob/9ac5f6c335336cac377c102bb48554bef9f54f87/rolling/distribution.yaml#L1643-L1646)

**Comment by gavanderhoorn** [comment]
My plan is to submit PRs removing those entries at the end of this week if there are no comments here.

**Comment by gavanderhoorn** [comment]
https://github.com/ros/rosdistro/pull/30861

**Comment by henningkayser** [comment]
Hi @gavanderhoorn, I agree that these jobs are probably redundant. Rolling doesn't fail though, the others have unmet dependencies or breaking changes.

**Comment by gavanderhoorn** [comment]
The rolling job is only back to stable since last week. That was after I submitted my PR.

If we feel there is value in having a duplicate job for rolling running on the farm, it could be taken out of the removal-PR.
