### ISSUE TITLE
CHOMP doesn't compile, seems to not be ported to ROS2

### ISSUE THREAD

**Issue by RDaneelOlivav** [ros-planning/moveit2#694]
### Description

I removed the COLCN_IGNORE in the chomp package planner, because its seems odd that
it wasn't prepared.
Trying to compile seems that the package is not meant for colcon?

### Your environment
* ROS Distro: FOXY
* OS Version: Ubuntu 20.04
* Source or Binary build? BUILD
* If binary, which release version?
* If source, which branch? FOXY branch

### Steps to reproduce
cd ws_moevit2
colcon build --packages-select chomp_motion_planner

### Expected behavior
It should build

### Actual behavior
It doesn't build

### Backtrace or Console output

Starting >>> chomp_motion_planner
[0.242s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/tgrip/TheConstruct/WorkShopROS2Industrial/ws_moveit2/install/moveit2_tutorials' in the environment variable AMENT_PREFIX_PATH doesn't exist
[0.242s] WARNING:colcon.colcon_ros.prefix_path.catkin:The path '/home/tgrip/TheConstruct/WorkShopROS2Industrial/ws_moveit2/install/moveit2_tutorials' in the environment variable CMAKE_PREFIX_PATH doesn't exist
--- stderr: chomp_motion_planner
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

**Comment by JafarAbdi** [comment]
> I removed the COLCN_IGNORE in the chomp package planner, because its seems odd that
it wasn't prepared.

We add that file because the package isn't ported, yet

There's no plan to port it in the near future but if you're willing to do so we're happy to review it and get it merged
