### ISSUE TITLE
approximated_constraint_manifolds.launch fails to launch in Ros2 Foxy

### ISSUE THREAD

**Issue by Thijsons** [ros-planning/moveit2#703]
### Description
Trying to follow approximated constraint manifold [tutorial](http://moveit2_tutorials.picknik.ai/doc/planning_with_approximated_constraint_manifolds/planning_with_approximated_constraint_manifolds_tutorial.html) from Moveit1 and adapt it to Moveit2. using "generate_state_database.launch ". Launching this file fails.  Has this feature been ported to moveit2 already? 

### Your environment
* ROS Distro: Foxy
* OS Version: Ubuntu 20.04
* Moveit source build, foxy branch

### Steps to reproduce
Adapted the "moveit2/moveit2_planners/ompl/ompl_interface/cMakeList.txt" by adding "install(DIRECTORY launch DESTINATION share/${PROJECT_NAME})". This makes it so the launch file can actually be found when using the `ros2 launch` command in the console.

run `ros2 launch moveit_planners_ompl generate_state_database.launch`.

### Expected behaviour
errors should be returned stating `Included launch description missing required argument` since the arguments "planning_group" and "constraints_file" haven't been passed.

### Actual behaviour
launch fails:
![Screenshot from 2021-09-24 10-21-46](https://user-images.githubusercontent.com/16014840/134642538-e106bcdc-78d2-406d-89c5-6ecfa18d2f41.png)

**Comment by JafarAbdi** [comment]
As you can see in the warning it's not ported yet to ROS2, if you are willing to port it I would be really happy to support you with it
