### ISSUE TITLE
Replace the idx variable in trajectory processing plugins with the JointGroup API

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#717]
There was a [comment here](https://github.com/ros-planning/moveit2/pull/712#discussion_r718714860) on the Ruckig trajectory plugin PR which also applies to the other plugins in the `moveit_core/trajectory_processing` folder:

> 
The code would be much more readable and consistent with MoveIt if you would use the joint group instead of passing num_dof and joint_idx everywhere.

Essentially, replace the usage of `idx` and `num_dof` with usage of the Joint Group API.

**Comment by invincialok** [comment]
i am a beginer how can i solve this issue . plz guide me

**Comment by AndyZe** [comment]
Thanks @invincialok. I think what @henningkayser  meant is, you should go through the `moveit_core/trajectory_processing` folder and replace `num_dof` and `idx` arguments in places like this:

```
  static void getNextRuckigInput(const ruckig::OutputParameter<0>& ruckig_output,
                                 const moveit::core::RobotStatePtr& next_waypoint, size_t num_dof,
                                 const std::vector<int>& idx, ruckig::InputParameter<0>& ruckig_input);
```

With something like this:

```
  static void getNextRuckigInput(const ruckig::OutputParameter<0>& ruckig_output,
                                 const moveit::core::RobotStatePtr& next_waypoint,
                                 const moveit::core::JointModelGroup* joint_group,
                                 ruckig::InputParameter<0>& ruckig_input);
```

For example, you can replace `num_dof` with this:  `joint_group->getVariableCount();`
