### ISSUE TITLE
Publish hybrid planner whitepaper

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2#738]
An issue to track publishing a hybrid planner whitepaper.  Feel free to move this to a different repo (like the website).

**Comment by tylerjw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MoveIt-61675936b391800012280f6d/issues/ros-planning/moveit2/738?planning-poker) with ZenHub @abake48 @Abishalini @AndyZe @DLu @henningkayser @JafarAbdi @vatanaksoytezer

**Comment by henningkayser** [comment]
I decided that it would make most sense to publish the content as a concepts page. See https://github.com/ros-planning/moveit2_tutorials/pull/328
