### ISSUE TITLE
Add path_constraints to Moveit_Cpp interface

### ISSUE THREAD

**Issue by lapo5** [ros-planning/moveit2#751]
Up to now, I did not see any solution to set the path_constraints field to the MotionPlanRequest when using Moveit_cpp interface (http://moveit2_tutorials.picknik.ai/doc/moveit_cpp/moveitcpp_tutorial.html). 
Is it a feature that will be added in the future?

**Comment by henningkayser** [comment]
Closing this, the change was merged into main and foxy
