### ISSUE TITLE
Latched Strings for URDF and SRDF

### ISSUE THREAD

**Issue by DLu** [ros-planning/moveit2#755]
With the death of the one centralized parameter server to rule them all in ROS 2, it has become more cumbersome to have single instances of global parameters that everyone can use, i.e. often multiple nodes will need to individually load `/robot_description` into their parameter namespace. 

[`robot_state_publisher`](https://github.com/ros/robot_state_publisher/blob/361249090bdd8b089eb45318fd537034c6c42318/src/robot_state_publisher.cpp#L132) gets around that problem by publishing a `std_msgs::msg::String` message with the entire URDF file that other files can then use. 

Right now, [`rdf_loader`](https://github.com/ros-planning/moveit2/blob/df6dc7c340afc9e79c15f3b92a93db936a561ba9/moveit_ros/planning/rdf_loader/src/rdf_loader.cpp#L76) requires that a parameter with the robot description is set AND that a separate parameter is set with the SRDF is set. 

I find this most annoying when trying to plan from RViz, and you need to load the URDF/SRDF into the namespaces for both move_group and Rviz. 

There are three different things that I think would make things easier: 
 * `RDFLoader` allows for the parameter to be set for the URDF or reads it in from a topic.
 * `RDFLoader` publishes a `std_msgs::msg::String` with the SRDF
 * `RDFLoader` subscribes to the above String as an alternative to the parameter. 

There's two tricky parts that I foresee:
 * Defining the `RDFLoader` constructor in a sufficiently concise way that allows for parameter or topic. 
 * Making sure that a single instance `RDFLoader` doesn't subscribe to the topic it publishes.

**Comment by tylerjw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MoveIt-61675936b391800012280f6d/issues/ros-planning/moveit2/755?planning-poker) with ZenHub @abake48 @Abishalini @AndyZe @DLu @henningkayser @JafarAbdi @vatanaksoytezer
