### ISSUE TITLE
Moveit simple controller manager doesn't respond to changes of trajectory_execution.execution_duration_monitoring parameter

### ISSUE THREAD

**Issue by Thijsons** [ros-planning/moveit2#760]
### Description
To make the UR10e robot work properly with its internal speed set to low values the 'trajectory_execution.execution_duration_monitoring' parameter of the simple controller manager needs to be changed to false, see [here](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/192#issuecomment-947803923).

setting the 'trajectory_execution.execution_duration_monitoring' parameter to false via a launch file does not seem to affect the simple controller manager? Checking the parameter on the parameter server does show its value to be false.

Setting it manually via 
`ros2 service call /moveit_simple_controller_manager/set_parameters rcl_interfaces/srv/SetParameters "{parameters: [{name: "trajectory_execution.execution_duration_monitoring", value: {type: 1, bool_value: False}}]}"` 
does work.

### Your environment
* ROS Distro: Foxy
* OS Version: e.g. Ubuntu 20.04
* Source, foxy branch

### Steps to reproduce
adjust the parameter in the launch file in the way [described](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/192#issuecomment-947803923).

### Expected behaviour
This parameter should be altered in the simple controller manager and change the behavior of the controller

### Actual behaviour
The parameter is set on the ros2 parameter server, but the simple controller manager does not seem affected.

**Comment by henningkayser** [comment]
https://github.com/ros-planning/moveit2/pull/996 has fixed this, I'm backporting to Foxy

**Comment by henningkayser** [comment]
https://github.com/ros-planning/moveit2/pull/1898
