### ISSUE TITLE
Deprecating the start/stop services in Servo

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2#762]
As of https://github.com/ros-planning/moveit2/pull/761 the initialization of servo is done in the constructor and no longer in the service callback for start.  This simplifies the code but did not remove the start or stop endpoints.

The reason for this is there is some race condition in startup if you start servo in the constructor.  This can be seen by moving the call to start into the constructor of ServoNode.

Others have mentioned that we should probably move away from using the `tf2_ros::StaticTransformBroadcasterNode` to create the transform between `panda_link0` and `world`.  I suspect if we could create this transform programmatically or via configs it would help with the race condition.

**Comment by sjahr** [comment]
@ibrahiminfinite Will this be addressed by your refactoring?

**Comment by ibrahiminfinite** [comment]
The new implementation does not have a start/stop service.
We only have a 'pause' service that controls whether Servo accepts commands or not.

This issue can resolved once #2224 is merged, which should be pretty soon. Finishing upon the tests.
