### ISSUE TITLE
Error building Moveit2 in Jetson: ROS2-Eloquent

### ISSUE THREAD

**Issue by alexlt97** [ros-planning/moveit2#821]
Hello, I know Moveit2 is not maintained for ROS-eloquent. Nevertheless I give it a try as I am developing and application in a Jetson Xavier device.When I tried to compile the package moveit_core from the branch eloquent I received this error:

```bash
In file included from /home/jetson/ros2_eloquent_ws/src/ext/moveit2/moveit_core/robot_model/src/joint_model_group.cpp:38:0:
/home/jetson/ros2_eloquent_ws/src/ext/moveit2/moveit_core/robot_model/include/moveit/robot_model/robot_model.h:42:10: fatal error: srdfdom/model.h: No such file or directory
 #include <srdfdom/model.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.


```

The package srdfdom is built properlty so I was wondering if there is some internal changed that I am not able to find. I checked the CMakeList.txt and the declarations should reachable. I also followed the recommendations of the issue https://github.com/ros-planning/moveit2/issues/499 to make a clean install but it remains the same.

**Comment by JafarAbdi** [comment]
I'm pretty sure this's related to exporting targets/include dirs, what's the hash that you're using for srdfdom? 

As you mentioned we no longer support eloquent (its lifetime ended 1-year ago), so I'm going to close this, please let me know if you still have this problem in any of the supported distros
