### ISSUE TITLE
Standardize comment style

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2#852]
https://github.com/cpp-best-practices/cppbestpractices/blob/master/03-Style.md#comments

**Comment by samuelsont** [comment]
Hi! I would love to tackle this as a good first issue for my contribution to MoveIt! I hope to contribute to moveit on an ongoing basis, and this seems like something small enough to get started. I have read the contribution guidelines.

Any guidance on getting started on this particular issue @tylerjw? I have done some C++, but I hope to grow my C++ skills by contributing to open source. My background is in JS, python, and PHP.
