### ISSUE TITLE
Never Use using namespace in a Header File

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2#853]
https://github.com/cpp-best-practices/cppbestpractices/blob/master/03-Style.md#never-use-using-namespace-in-a-header-file

**Comment by JafarAbdi** [comment]
Fixed by https://github.com/ros-planning/moveit2/pull/994

**Comment by JafarAbdi** [comment]
Fixed by https://github.com/ros-planning/moveit2/pull/994
