### ISSUE TITLE
{} Are Required for Blocks.

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2#854]
https://github.com/cpp-best-practices/cppbestpractices/blob/master/03-Style.md#-are-required-for-blocks

**Comment by kiwipeace01** [comment]
Hi, I'd like to work on this issue if that's alright

**Comment by tylerjw** [comment]
hello @kiwipeace01 this issue is already taken by cory

**Comment by kiwipeace01** [comment]
oh okay sorry about that! I'm new to open-source so I was a little confused 😅
