### ISSUE TITLE
Do not pass and return simple types by const ref

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2#859]
https://github.com/cpp-best-practices/cppbestpractices/blob/master/04-Considering_Safety.md#do-not-pass-and-return-simple-types-by-const-ref

**Comment by Nils-ChristianIseke** [comment]
I made the necessary changes:
https://github.com/ros-planning/moveit2/pull/2047
Regarding this PR i have two more questions:
1. How to handle variables that are const ref?
2. Doesn't it make sense to replace not only const references of primitive data types, but also references without const? If that is desired, I can also do that quickly.

**Comment by Nils-ChristianIseke** [comment]
Made the necessary changes: https://github.com/ros-planning/moveit2/pull/2057.
