### ISSUE TITLE
Release rviz_visual_tools

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2#904]
- [x] Backport https://github.com/PickNikRobotics/rviz_visual_tools/pull/209 to foxy
- [x] Foxy
- [x] Galactic
- [x] Rolling

**Comment by JafarAbdi** [comment]
Foxy: https://github.com/ros/rosdistro/pull/31456
Galactic: https://github.com/ros/rosdistro/pull/31457
Rolling: https://github.com/ros/rosdistro/pull/31458
