### ISSUE TITLE
Release Upstream Repos [R/G/F]

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2#912]
Some of the upstream repos have changed and need to be released.  Check if each of these needs a release and create it if so:

- [x] moveit_msgs - https://github.com/ros-planning/moveit_msgs/pull/137
- [ ] geometric_shapes - https://github.com/ros-planning/geometric_shapes/pull/213, https://github.com/ros-planning/geometric_shapes/pull/212
- [x] random_numbers - I don't think we need to release this yet: https://github.com/ros-planning/random_numbers/commits/ros2
- [x] srdfdom - No recent changes https://github.com/ros-planning/srdfdom/commits/ros2
- [x] warehouse_ros - SSL dependency change, unsure if we need to release this.  @henningkayser ?
- [x] warehouse_ros_mongo - Boost dependency change, unsure if we need to release this.
- [x] warehouse_ros_sqlite - This hasn't been released yet, I don't think we have to do it this time.

**Comment by henningkayser** [comment]
Thanks for starting this! Do we even need new releases for the other packages, though?

**Comment by tylerjw** [comment]
I created the changelogs for geometric_shapes and added details for all the others.

**Comment by henningkayser** [comment]
@tylerjw I don't think that warehouse needs a new release for the fixed ssl dependency. afaik, that was only a fix required for a certain build setup.
