### ISSUE TITLE
Rebuild docker image to fetch the latest ROS 2 key

### ISSUE THREAD

**Issue by LanderU** [ros-planning/moveit2#92]
### Description

The image that is using for the CI is outdated and is failing because of changes in the key.

**Error**:

* https://travis-ci.org/ros-planning/moveit2/builds/539939904#L236-L237

I you rebuild the image solves the issue: https://discourse.ros.org/t/key-rotation-for-ros-2-apt-repositories/9363

**Comment by mlautman** [comment]
Noted. I re-triggered the build.

**Comment by mlautman** [comment]
Also, I changed the docker tags to master-ci and master-source since we do not have a crystal-devel branch

**Comment by mlautman** [comment]
https://github.com/ros-planning/moveit2/issues/94
