### ISSUE TITLE
Collision object not entirely removed from planning scene

### ISSUE THREAD

**Issue by juiceine** [ros-planning/moveit2#924]
### Description

Hello all,
I am currently running into trouble with removing collision objects from the planning scene. I attempt to make a robot do a pick and place task, where the collision objects are picked from the environment and attached to the robot. Approaching the object is done by servoing with the C++ interface, with collision detection enabled. However, during the servoing, it sometimes happens that a collision is detected with an object that previously was removed from the planning scene. The object is not visible in Rviz, it is not displayed in Rviz' Scene Objects tab and `ros2 service call /get_planning_scene moveit_msgs/srv/GetPlanningScene` also only shows the apples that are currently shown in Rviz. See image below for a visualisation.

The objects are removed by using `remove_object.REMOVE` and `planning_scene_interface.applyCollisionObject(remove_object)` from the planning scene interface. When such a collision occurs, creating e.g. a random box on another location and publishing the planning scene in the Rviz UI does resolve the collision. 

My issues seem to look very similar to #444, #429 and #407 , and I have seen that #464 should fix this. However, I tried to apt-get update and apt-get upgrade several times, but the problem persists. Hopefully this is a clear description and I hope anyone has a suggestion or solution. Thank you in advance!

### Your environment
* ROS Distro: Foxy
* OS Version: Ubuntu 20.04
* Source or Binary build? Binary

### Steps to reproduce
- Publish object to planning scene.
- Remove object from planning scene using the planning scene interface from another node.
- Move the robot to a location behind the location of the removed object.

### Expected behaviour
Collision objects are not causing collisions after they have been removed.

### Actual behaviour
The collision object appears to be removed, but does cause collisions.

**Comment by henningkayser** [comment]
closing since it's targeting Foxy. Please reopen if this still exists for Humble or Rolling.
